// Generated by tsbindgen - Architecture
// Namespace: Microsoft.AspNetCore.Routing.Constraints
// Assembly: Microsoft.AspNetCore.Routing

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { HttpContext } from "../../Microsoft.AspNetCore.Http/internal/index.js";
import * as Microsoft_AspNetCore_Routing_Matching_Internal from "../../Microsoft.AspNetCore.Routing.Matching/internal/index.js";
import type { IParameterLiteralNodeMatchingPolicy } from "../../Microsoft.AspNetCore.Routing.Matching/internal/index.js";
import * as Microsoft_AspNetCore_Routing_Internal from "../../Microsoft.AspNetCore.Routing/internal/index.js";
import type { IParameterPolicy, IRouteConstraint, IRouter, RouteDirection, RouteValueDictionary } from "../../Microsoft.AspNetCore.Routing/internal/index.js";
import type { IEnumerable_1, IList_1 } from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import type { Regex } from "@tsonic/dotnet/System.Text.RegularExpressions/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Boolean as ClrBoolean, Int32, Int64, Object as ClrObject, String as ClrString } from "@tsonic/dotnet/System/internal/index.js";

export interface AlphaRouteConstraint$instance extends RegexRouteConstraint$instance, IParameterPolicy, Microsoft_AspNetCore_Routing_Matching_Internal.IParameterLiteralNodeMatchingPolicy$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IRouteConstraint: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_Matching_ICachableParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_Matching_IParameterLiteralNodeMatchingPolicy: never;

    Match(httpContext: HttpContext, route: IRouter, routeKey: string, values: RouteValueDictionary, routeDirection: RouteDirection): boolean;
    MatchesLiteral(parameterName: string, literal: string): boolean;
}


export const AlphaRouteConstraint: {
    new(): AlphaRouteConstraint;
};


export interface __AlphaRouteConstraint$views {
    As_IParameterLiteralNodeMatchingPolicy(): Microsoft_AspNetCore_Routing_Matching_Internal.IParameterLiteralNodeMatchingPolicy$instance;
    As_IRouteConstraint(): Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance;
}

export type AlphaRouteConstraint = AlphaRouteConstraint$instance & __AlphaRouteConstraint$views;


export interface BoolRouteConstraint$instance extends IParameterPolicy, Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance, Microsoft_AspNetCore_Routing_Matching_Internal.IParameterLiteralNodeMatchingPolicy$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IRouteConstraint: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_Matching_ICachableParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_Matching_IParameterLiteralNodeMatchingPolicy: never;

    Match(httpContext: HttpContext, route: IRouter, routeKey: string, values: RouteValueDictionary, routeDirection: RouteDirection): boolean;
}


export const BoolRouteConstraint: {
    new(): BoolRouteConstraint;
};


export interface __BoolRouteConstraint$views {
    As_IParameterLiteralNodeMatchingPolicy(): Microsoft_AspNetCore_Routing_Matching_Internal.IParameterLiteralNodeMatchingPolicy$instance;
    As_IRouteConstraint(): Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance;
}

export type BoolRouteConstraint = BoolRouteConstraint$instance & __BoolRouteConstraint$views;


export interface CompositeRouteConstraint$instance extends IParameterPolicy, Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance, Microsoft_AspNetCore_Routing_Matching_Internal.IParameterLiteralNodeMatchingPolicy$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IRouteConstraint: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_Matching_IParameterLiteralNodeMatchingPolicy: never;

    Constraints: IEnumerable_1<IRouteConstraint>;
    Match(httpContext: HttpContext, route: IRouter, routeKey: string, values: RouteValueDictionary, routeDirection: RouteDirection): boolean;
}


export const CompositeRouteConstraint: {
    new(constraints: IEnumerable_1<IRouteConstraint>): CompositeRouteConstraint;
};


export interface __CompositeRouteConstraint$views {
    As_IParameterLiteralNodeMatchingPolicy(): Microsoft_AspNetCore_Routing_Matching_Internal.IParameterLiteralNodeMatchingPolicy$instance;
    As_IRouteConstraint(): Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance;
}

export type CompositeRouteConstraint = CompositeRouteConstraint$instance & __CompositeRouteConstraint$views;


export interface DateTimeRouteConstraint$instance extends IParameterPolicy, Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance, Microsoft_AspNetCore_Routing_Matching_Internal.IParameterLiteralNodeMatchingPolicy$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IRouteConstraint: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_Matching_ICachableParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_Matching_IParameterLiteralNodeMatchingPolicy: never;

    Match(httpContext: HttpContext, route: IRouter, routeKey: string, values: RouteValueDictionary, routeDirection: RouteDirection): boolean;
}


export const DateTimeRouteConstraint: {
    new(): DateTimeRouteConstraint;
};


export interface __DateTimeRouteConstraint$views {
    As_IParameterLiteralNodeMatchingPolicy(): Microsoft_AspNetCore_Routing_Matching_Internal.IParameterLiteralNodeMatchingPolicy$instance;
    As_IRouteConstraint(): Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance;
}

export type DateTimeRouteConstraint = DateTimeRouteConstraint$instance & __DateTimeRouteConstraint$views;


export interface DecimalRouteConstraint$instance extends IParameterPolicy, Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance, Microsoft_AspNetCore_Routing_Matching_Internal.IParameterLiteralNodeMatchingPolicy$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IRouteConstraint: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_Matching_ICachableParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_Matching_IParameterLiteralNodeMatchingPolicy: never;

    Match(httpContext: HttpContext, route: IRouter, routeKey: string, values: RouteValueDictionary, routeDirection: RouteDirection): boolean;
}


export const DecimalRouteConstraint: {
    new(): DecimalRouteConstraint;
};


export interface __DecimalRouteConstraint$views {
    As_IParameterLiteralNodeMatchingPolicy(): Microsoft_AspNetCore_Routing_Matching_Internal.IParameterLiteralNodeMatchingPolicy$instance;
    As_IRouteConstraint(): Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance;
}

export type DecimalRouteConstraint = DecimalRouteConstraint$instance & __DecimalRouteConstraint$views;


export interface DoubleRouteConstraint$instance extends IParameterPolicy, Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance, Microsoft_AspNetCore_Routing_Matching_Internal.IParameterLiteralNodeMatchingPolicy$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IRouteConstraint: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_Matching_ICachableParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_Matching_IParameterLiteralNodeMatchingPolicy: never;

    Match(httpContext: HttpContext, route: IRouter, routeKey: string, values: RouteValueDictionary, routeDirection: RouteDirection): boolean;
}


export const DoubleRouteConstraint: {
    new(): DoubleRouteConstraint;
};


export interface __DoubleRouteConstraint$views {
    As_IParameterLiteralNodeMatchingPolicy(): Microsoft_AspNetCore_Routing_Matching_Internal.IParameterLiteralNodeMatchingPolicy$instance;
    As_IRouteConstraint(): Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance;
}

export type DoubleRouteConstraint = DoubleRouteConstraint$instance & __DoubleRouteConstraint$views;


export interface FileNameRouteConstraint$instance extends IParameterPolicy, Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance, Microsoft_AspNetCore_Routing_Matching_Internal.IParameterLiteralNodeMatchingPolicy$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IRouteConstraint: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_Matching_ICachableParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_Matching_IParameterLiteralNodeMatchingPolicy: never;

    Match(httpContext: HttpContext, route: IRouter, routeKey: string, values: RouteValueDictionary, routeDirection: RouteDirection): boolean;
}


export const FileNameRouteConstraint: {
    new(): FileNameRouteConstraint;
};


export interface __FileNameRouteConstraint$views {
    As_IParameterLiteralNodeMatchingPolicy(): Microsoft_AspNetCore_Routing_Matching_Internal.IParameterLiteralNodeMatchingPolicy$instance;
    As_IRouteConstraint(): Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance;
}

export type FileNameRouteConstraint = FileNameRouteConstraint$instance & __FileNameRouteConstraint$views;


export interface FloatRouteConstraint$instance extends IParameterPolicy, Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance, Microsoft_AspNetCore_Routing_Matching_Internal.IParameterLiteralNodeMatchingPolicy$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IRouteConstraint: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_Matching_ICachableParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_Matching_IParameterLiteralNodeMatchingPolicy: never;

    Match(httpContext: HttpContext, route: IRouter, routeKey: string, values: RouteValueDictionary, routeDirection: RouteDirection): boolean;
}


export const FloatRouteConstraint: {
    new(): FloatRouteConstraint;
};


export interface __FloatRouteConstraint$views {
    As_IParameterLiteralNodeMatchingPolicy(): Microsoft_AspNetCore_Routing_Matching_Internal.IParameterLiteralNodeMatchingPolicy$instance;
    As_IRouteConstraint(): Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance;
}

export type FloatRouteConstraint = FloatRouteConstraint$instance & __FloatRouteConstraint$views;


export interface GuidRouteConstraint$instance extends IParameterPolicy, Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance, Microsoft_AspNetCore_Routing_Matching_Internal.IParameterLiteralNodeMatchingPolicy$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IRouteConstraint: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_Matching_ICachableParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_Matching_IParameterLiteralNodeMatchingPolicy: never;

    Match(httpContext: HttpContext, route: IRouter, routeKey: string, values: RouteValueDictionary, routeDirection: RouteDirection): boolean;
}


export const GuidRouteConstraint: {
    new(): GuidRouteConstraint;
};


export interface __GuidRouteConstraint$views {
    As_IParameterLiteralNodeMatchingPolicy(): Microsoft_AspNetCore_Routing_Matching_Internal.IParameterLiteralNodeMatchingPolicy$instance;
    As_IRouteConstraint(): Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance;
}

export type GuidRouteConstraint = GuidRouteConstraint$instance & __GuidRouteConstraint$views;


export interface HttpMethodRouteConstraint$instance extends IParameterPolicy, Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IRouteConstraint: never;

    readonly AllowedMethods: IList_1<System_Internal.String>;
    Match(httpContext: HttpContext, route: IRouter, routeKey: string, values: RouteValueDictionary, routeDirection: RouteDirection): boolean;
}


export const HttpMethodRouteConstraint: {
    new(allowedMethods: string[]): HttpMethodRouteConstraint;
};


export interface __HttpMethodRouteConstraint$views {
    As_IRouteConstraint(): Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance;
}

export type HttpMethodRouteConstraint = HttpMethodRouteConstraint$instance & __HttpMethodRouteConstraint$views;


export interface IntRouteConstraint$instance extends IParameterPolicy, Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance, Microsoft_AspNetCore_Routing_Matching_Internal.IParameterLiteralNodeMatchingPolicy$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IRouteConstraint: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_Matching_ICachableParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_Matching_IParameterLiteralNodeMatchingPolicy: never;

    Match(httpContext: HttpContext, route: IRouter, routeKey: string, values: RouteValueDictionary, routeDirection: RouteDirection): boolean;
}


export const IntRouteConstraint: {
    new(): IntRouteConstraint;
};


export interface __IntRouteConstraint$views {
    As_IParameterLiteralNodeMatchingPolicy(): Microsoft_AspNetCore_Routing_Matching_Internal.IParameterLiteralNodeMatchingPolicy$instance;
    As_IRouteConstraint(): Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance;
}

export type IntRouteConstraint = IntRouteConstraint$instance & __IntRouteConstraint$views;


export interface LengthRouteConstraint$instance extends IParameterPolicy, Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance, Microsoft_AspNetCore_Routing_Matching_Internal.IParameterLiteralNodeMatchingPolicy$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IRouteConstraint: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_Matching_ICachableParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_Matching_IParameterLiteralNodeMatchingPolicy: never;

    readonly MaxLength: int;
    readonly MinLength: int;
    Match(httpContext: HttpContext, route: IRouter, routeKey: string, values: RouteValueDictionary, routeDirection: RouteDirection): boolean;
}


export const LengthRouteConstraint: {
    new(length: int): LengthRouteConstraint;
    new(minLength: int, maxLength: int): LengthRouteConstraint;
};


export interface __LengthRouteConstraint$views {
    As_IParameterLiteralNodeMatchingPolicy(): Microsoft_AspNetCore_Routing_Matching_Internal.IParameterLiteralNodeMatchingPolicy$instance;
    As_IRouteConstraint(): Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance;
}

export type LengthRouteConstraint = LengthRouteConstraint$instance & __LengthRouteConstraint$views;


export interface LongRouteConstraint$instance extends IParameterPolicy, Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance, Microsoft_AspNetCore_Routing_Matching_Internal.IParameterLiteralNodeMatchingPolicy$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IRouteConstraint: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_Matching_ICachableParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_Matching_IParameterLiteralNodeMatchingPolicy: never;

    Match(httpContext: HttpContext, route: IRouter, routeKey: string, values: RouteValueDictionary, routeDirection: RouteDirection): boolean;
}


export const LongRouteConstraint: {
    new(): LongRouteConstraint;
};


export interface __LongRouteConstraint$views {
    As_IParameterLiteralNodeMatchingPolicy(): Microsoft_AspNetCore_Routing_Matching_Internal.IParameterLiteralNodeMatchingPolicy$instance;
    As_IRouteConstraint(): Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance;
}

export type LongRouteConstraint = LongRouteConstraint$instance & __LongRouteConstraint$views;


export interface MaxLengthRouteConstraint$instance extends IParameterPolicy, Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance, Microsoft_AspNetCore_Routing_Matching_Internal.IParameterLiteralNodeMatchingPolicy$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IRouteConstraint: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_Matching_ICachableParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_Matching_IParameterLiteralNodeMatchingPolicy: never;

    readonly MaxLength: int;
    Match(httpContext: HttpContext, route: IRouter, routeKey: string, values: RouteValueDictionary, routeDirection: RouteDirection): boolean;
}


export const MaxLengthRouteConstraint: {
    new(maxLength: int): MaxLengthRouteConstraint;
};


export interface __MaxLengthRouteConstraint$views {
    As_IParameterLiteralNodeMatchingPolicy(): Microsoft_AspNetCore_Routing_Matching_Internal.IParameterLiteralNodeMatchingPolicy$instance;
    As_IRouteConstraint(): Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance;
}

export type MaxLengthRouteConstraint = MaxLengthRouteConstraint$instance & __MaxLengthRouteConstraint$views;


export interface MaxRouteConstraint$instance extends IParameterPolicy, Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance, Microsoft_AspNetCore_Routing_Matching_Internal.IParameterLiteralNodeMatchingPolicy$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IRouteConstraint: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_Matching_ICachableParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_Matching_IParameterLiteralNodeMatchingPolicy: never;

    Max: long;
    Match(httpContext: HttpContext, route: IRouter, routeKey: string, values: RouteValueDictionary, routeDirection: RouteDirection): boolean;
}


export const MaxRouteConstraint: {
    new(max: long): MaxRouteConstraint;
};


export interface __MaxRouteConstraint$views {
    As_IParameterLiteralNodeMatchingPolicy(): Microsoft_AspNetCore_Routing_Matching_Internal.IParameterLiteralNodeMatchingPolicy$instance;
    As_IRouteConstraint(): Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance;
}

export type MaxRouteConstraint = MaxRouteConstraint$instance & __MaxRouteConstraint$views;


export interface MinLengthRouteConstraint$instance extends IParameterPolicy, Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance, Microsoft_AspNetCore_Routing_Matching_Internal.IParameterLiteralNodeMatchingPolicy$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IRouteConstraint: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_Matching_ICachableParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_Matching_IParameterLiteralNodeMatchingPolicy: never;

    MinLength: int;
    Match(httpContext: HttpContext, route: IRouter, routeKey: string, values: RouteValueDictionary, routeDirection: RouteDirection): boolean;
}


export const MinLengthRouteConstraint: {
    new(minLength: int): MinLengthRouteConstraint;
};


export interface __MinLengthRouteConstraint$views {
    As_IParameterLiteralNodeMatchingPolicy(): Microsoft_AspNetCore_Routing_Matching_Internal.IParameterLiteralNodeMatchingPolicy$instance;
    As_IRouteConstraint(): Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance;
}

export type MinLengthRouteConstraint = MinLengthRouteConstraint$instance & __MinLengthRouteConstraint$views;


export interface MinRouteConstraint$instance extends IParameterPolicy, Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance, Microsoft_AspNetCore_Routing_Matching_Internal.IParameterLiteralNodeMatchingPolicy$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IRouteConstraint: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_Matching_ICachableParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_Matching_IParameterLiteralNodeMatchingPolicy: never;

    readonly Min: long;
    Match(httpContext: HttpContext, route: IRouter, routeKey: string, values: RouteValueDictionary, routeDirection: RouteDirection): boolean;
}


export const MinRouteConstraint: {
    new(min: long): MinRouteConstraint;
};


export interface __MinRouteConstraint$views {
    As_IParameterLiteralNodeMatchingPolicy(): Microsoft_AspNetCore_Routing_Matching_Internal.IParameterLiteralNodeMatchingPolicy$instance;
    As_IRouteConstraint(): Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance;
}

export type MinRouteConstraint = MinRouteConstraint$instance & __MinRouteConstraint$views;


export interface NonFileNameRouteConstraint$instance extends IParameterPolicy, Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance, Microsoft_AspNetCore_Routing_Matching_Internal.IParameterLiteralNodeMatchingPolicy$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IRouteConstraint: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_Matching_ICachableParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_Matching_IParameterLiteralNodeMatchingPolicy: never;

    Match(httpContext: HttpContext, route: IRouter, routeKey: string, values: RouteValueDictionary, routeDirection: RouteDirection): boolean;
}


export const NonFileNameRouteConstraint: {
    new(): NonFileNameRouteConstraint;
};


export interface __NonFileNameRouteConstraint$views {
    As_IParameterLiteralNodeMatchingPolicy(): Microsoft_AspNetCore_Routing_Matching_Internal.IParameterLiteralNodeMatchingPolicy$instance;
    As_IRouteConstraint(): Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance;
}

export type NonFileNameRouteConstraint = NonFileNameRouteConstraint$instance & __NonFileNameRouteConstraint$views;


export interface OptionalRouteConstraint$instance extends IParameterPolicy, Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IRouteConstraint: never;

    readonly InnerConstraint: IRouteConstraint;
    Match(httpContext: HttpContext, route: IRouter, routeKey: string, values: RouteValueDictionary, routeDirection: RouteDirection): boolean;
}


export const OptionalRouteConstraint: {
    new(innerConstraint: IRouteConstraint): OptionalRouteConstraint;
};


export interface __OptionalRouteConstraint$views {
    As_IRouteConstraint(): Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance;
}

export type OptionalRouteConstraint = OptionalRouteConstraint$instance & __OptionalRouteConstraint$views;


export interface RangeRouteConstraint$instance extends IParameterPolicy, Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance, Microsoft_AspNetCore_Routing_Matching_Internal.IParameterLiteralNodeMatchingPolicy$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IRouteConstraint: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_Matching_ICachableParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_Matching_IParameterLiteralNodeMatchingPolicy: never;

    Max: long;
    Min: long;
    Match(httpContext: HttpContext, route: IRouter, routeKey: string, values: RouteValueDictionary, routeDirection: RouteDirection): boolean;
}


export const RangeRouteConstraint: {
    new(min: long, max: long): RangeRouteConstraint;
};


export interface __RangeRouteConstraint$views {
    As_IParameterLiteralNodeMatchingPolicy(): Microsoft_AspNetCore_Routing_Matching_Internal.IParameterLiteralNodeMatchingPolicy$instance;
    As_IRouteConstraint(): Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance;
}

export type RangeRouteConstraint = RangeRouteConstraint$instance & __RangeRouteConstraint$views;


export interface RegexInlineRouteConstraint$instance extends RegexRouteConstraint$instance, IParameterPolicy, Microsoft_AspNetCore_Routing_Matching_Internal.IParameterLiteralNodeMatchingPolicy$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IRouteConstraint: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_Matching_ICachableParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_Matching_IParameterLiteralNodeMatchingPolicy: never;

    Match(httpContext: HttpContext, route: IRouter, routeKey: string, values: RouteValueDictionary, routeDirection: RouteDirection): boolean;
    MatchesLiteral(parameterName: string, literal: string): boolean;
}


export const RegexInlineRouteConstraint: {
    new(regexPattern: string): RegexInlineRouteConstraint;
};


export interface __RegexInlineRouteConstraint$views {
    As_IParameterLiteralNodeMatchingPolicy(): Microsoft_AspNetCore_Routing_Matching_Internal.IParameterLiteralNodeMatchingPolicy$instance;
    As_IRouteConstraint(): Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance;
}

export type RegexInlineRouteConstraint = RegexInlineRouteConstraint$instance & __RegexInlineRouteConstraint$views;


export interface RegexRouteConstraint$instance extends IParameterPolicy, Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance, Microsoft_AspNetCore_Routing_Matching_Internal.IParameterLiteralNodeMatchingPolicy$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IRouteConstraint: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_Matching_IParameterLiteralNodeMatchingPolicy: never;

    readonly Constraint: Regex;
    Match(httpContext: HttpContext, route: IRouter, routeKey: string, values: RouteValueDictionary, routeDirection: RouteDirection): boolean;
}


export const RegexRouteConstraint: {
    new(regex: Regex): RegexRouteConstraint;
    new(regexPattern: string): RegexRouteConstraint;
};


export interface __RegexRouteConstraint$views {
    As_IParameterLiteralNodeMatchingPolicy(): Microsoft_AspNetCore_Routing_Matching_Internal.IParameterLiteralNodeMatchingPolicy$instance;
    As_IRouteConstraint(): Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance;
}

export type RegexRouteConstraint = RegexRouteConstraint$instance & __RegexRouteConstraint$views;


export interface RequiredRouteConstraint$instance extends IParameterPolicy, Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IRouteConstraint: never;

    Match(httpContext: HttpContext, route: IRouter, routeKey: string, values: RouteValueDictionary, routeDirection: RouteDirection): boolean;
}


export const RequiredRouteConstraint: {
    new(): RequiredRouteConstraint;
};


export interface __RequiredRouteConstraint$views {
    As_IRouteConstraint(): Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance;
}

export type RequiredRouteConstraint = RequiredRouteConstraint$instance & __RequiredRouteConstraint$views;


export interface StringRouteConstraint$instance extends IParameterPolicy, Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance, Microsoft_AspNetCore_Routing_Matching_Internal.IParameterLiteralNodeMatchingPolicy$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IRouteConstraint: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_Matching_ICachableParameterPolicy: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_Matching_IParameterLiteralNodeMatchingPolicy: never;

    Match(httpContext: HttpContext, route: IRouter, routeKey: string, values: RouteValueDictionary, routeDirection: RouteDirection): boolean;
}


export const StringRouteConstraint: {
    new(value: string): StringRouteConstraint;
};


export interface __StringRouteConstraint$views {
    As_IParameterLiteralNodeMatchingPolicy(): Microsoft_AspNetCore_Routing_Matching_Internal.IParameterLiteralNodeMatchingPolicy$instance;
    As_IRouteConstraint(): Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance;
}

export type StringRouteConstraint = StringRouteConstraint$instance & __StringRouteConstraint$views;


