// Generated by tsbindgen - Architecture
// Namespace: Microsoft.AspNetCore.Mvc.ViewComponents
// Assembly: Microsoft.AspNetCore.Mvc.ViewFeatures

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { IHtmlContent } from "../../Microsoft.AspNetCore.Html/internal/index.js";
import * as Microsoft_AspNetCore_Mvc_ApplicationParts_Internal from "../../Microsoft.AspNetCore.Mvc.ApplicationParts/internal/index.js";
import type { ApplicationPart, ApplicationPartManager, IApplicationFeatureProvider, IApplicationFeatureProvider_1 } from "../../Microsoft.AspNetCore.Mvc.ApplicationParts/internal/index.js";
import type { ViewContext } from "../../Microsoft.AspNetCore.Mvc.Rendering/internal/index.js";
import type { IViewEngine } from "../../Microsoft.AspNetCore.Mvc.ViewEngines/internal/index.js";
import type { IViewBufferScope } from "../../Microsoft.AspNetCore.Mvc.ViewFeatures.Buffers/internal/index.js";
import * as Microsoft_AspNetCore_Mvc_ViewFeatures_Internal from "../../Microsoft.AspNetCore.Mvc.ViewFeatures/internal/index.js";
import type { ITempDataDictionary, IViewContextAware, ViewDataDictionary } from "../../Microsoft.AspNetCore.Mvc.ViewFeatures/internal/index.js";
import * as Microsoft_AspNetCore_Mvc_Internal from "../../Microsoft.AspNetCore.Mvc/internal/index.js";
import type { IViewComponentHelper, IViewComponentResult } from "../../Microsoft.AspNetCore.Mvc/internal/index.js";
import type { IDictionary, IEnumerable, IList, IReadOnlyList } from "@tsonic/dotnet/System.Collections.Generic.js";
import type { TextWriter } from "@tsonic/dotnet/System.IO.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Attribute, Boolean as ClrBoolean, Int32, Object as ClrObject, String as ClrString, Type, Void } from "@tsonic/dotnet/System.js";
import type { MethodInfo, ParameterInfo, TypeInfo } from "@tsonic/dotnet/System.Reflection.js";
import type { HtmlEncoder } from "@tsonic/dotnet/System.Text.Encodings.Web.js";
import type { Task, ValueTask } from "@tsonic/dotnet/System.Threading.Tasks.js";

export interface IViewComponentActivator$instance {
    create(context: ViewComponentContext): unknown;
    release(context: ViewComponentContext, viewComponent: unknown): void;
    releaseAsync(context: ViewComponentContext, viewComponent: unknown): ValueTask;
}


export type IViewComponentActivator = IViewComponentActivator$instance;

export interface IViewComponentDescriptorCollectionProvider$instance {
    readonly viewComponents: ViewComponentDescriptorCollection;
}


export type IViewComponentDescriptorCollectionProvider = IViewComponentDescriptorCollectionProvider$instance;

export interface IViewComponentDescriptorProvider$instance {
    getViewComponents(): IEnumerable<ViewComponentDescriptor>;
}


export type IViewComponentDescriptorProvider = IViewComponentDescriptorProvider$instance;

export interface IViewComponentFactory$instance {
    createViewComponent(context: ViewComponentContext): unknown;
    releaseViewComponent(context: ViewComponentContext, component: unknown): void;
    releaseViewComponentAsync(context: ViewComponentContext, component: unknown): ValueTask;
}


export type IViewComponentFactory = IViewComponentFactory$instance;

export interface IViewComponentInvoker$instance {
    invokeAsync(context: ViewComponentContext): Task;
}


export type IViewComponentInvoker = IViewComponentInvoker$instance;

export interface IViewComponentInvokerFactory$instance {
    createInstance(context: ViewComponentContext): IViewComponentInvoker;
}


export type IViewComponentInvokerFactory = IViewComponentInvokerFactory$instance;

export interface IViewComponentSelector$instance {
    selectComponent(componentName: string): ViewComponentDescriptor;
}


export type IViewComponentSelector = IViewComponentSelector$instance;

export interface ContentViewComponentResult$instance {
    readonly content: string;
    execute(context: ViewComponentContext): void;
    executeAsync(context: ViewComponentContext): Task;
}


export const ContentViewComponentResult: {
    new(content: string): ContentViewComponentResult;
};


export interface __ContentViewComponentResult$views {
    As_IViewComponentResult(): Microsoft_AspNetCore_Mvc_Internal.IViewComponentResult$instance;
}

export interface ContentViewComponentResult$instance extends Microsoft_AspNetCore_Mvc_Internal.IViewComponentResult$instance {}

export type ContentViewComponentResult = ContentViewComponentResult$instance & __ContentViewComponentResult$views;


export interface DefaultViewComponentDescriptorCollectionProvider$instance {
    readonly viewComponents: ViewComponentDescriptorCollection;
}


export const DefaultViewComponentDescriptorCollectionProvider: {
    new(descriptorProvider: IViewComponentDescriptorProvider): DefaultViewComponentDescriptorCollectionProvider;
};


export interface __DefaultViewComponentDescriptorCollectionProvider$views {
    As_IViewComponentDescriptorCollectionProvider(): IViewComponentDescriptorCollectionProvider$instance;
}

export interface DefaultViewComponentDescriptorCollectionProvider$instance extends IViewComponentDescriptorCollectionProvider$instance {}

export type DefaultViewComponentDescriptorCollectionProvider = DefaultViewComponentDescriptorCollectionProvider$instance & __DefaultViewComponentDescriptorCollectionProvider$views;


export interface DefaultViewComponentDescriptorProvider$instance {
    getViewComponents(): IEnumerable<ViewComponentDescriptor>;
}


export const DefaultViewComponentDescriptorProvider: {
    new(partManager: ApplicationPartManager): DefaultViewComponentDescriptorProvider;
};


export interface __DefaultViewComponentDescriptorProvider$views {
    As_IViewComponentDescriptorProvider(): IViewComponentDescriptorProvider$instance;
}

export interface DefaultViewComponentDescriptorProvider$instance extends IViewComponentDescriptorProvider$instance {}

export type DefaultViewComponentDescriptorProvider = DefaultViewComponentDescriptorProvider$instance & __DefaultViewComponentDescriptorProvider$views;


export interface DefaultViewComponentFactory$instance {
    createViewComponent(context: ViewComponentContext): unknown;
    releaseViewComponent(context: ViewComponentContext, component: unknown): void;
    releaseViewComponentAsync(context: ViewComponentContext, component: unknown): ValueTask;
}


export const DefaultViewComponentFactory: {
    new(activator: IViewComponentActivator): DefaultViewComponentFactory;
};


export interface __DefaultViewComponentFactory$views {
    As_IViewComponentFactory(): IViewComponentFactory$instance;
}

export interface DefaultViewComponentFactory$instance extends IViewComponentFactory$instance {}

export type DefaultViewComponentFactory = DefaultViewComponentFactory$instance & __DefaultViewComponentFactory$views;


export interface DefaultViewComponentHelper$instance {
    contextualize(viewContext: ViewContext): void;
    invokeAsync(name: string, arguments: unknown): Task<IHtmlContent>;
    invokeAsync(componentType: Type, arguments: unknown): Task<IHtmlContent>;
}


export const DefaultViewComponentHelper: {
    new(descriptorProvider: IViewComponentDescriptorCollectionProvider, htmlEncoder: HtmlEncoder, selector: IViewComponentSelector, invokerFactory: IViewComponentInvokerFactory, viewBufferScope: IViewBufferScope): DefaultViewComponentHelper;
};


export interface __DefaultViewComponentHelper$views {
    As_IViewComponentHelper(): Microsoft_AspNetCore_Mvc_Internal.IViewComponentHelper$instance;
    As_IViewContextAware(): Microsoft_AspNetCore_Mvc_ViewFeatures_Internal.IViewContextAware$instance;
}

export interface DefaultViewComponentHelper$instance extends Microsoft_AspNetCore_Mvc_ViewFeatures_Internal.IViewContextAware$instance {}

export type DefaultViewComponentHelper = DefaultViewComponentHelper$instance & __DefaultViewComponentHelper$views;


export interface DefaultViewComponentSelector$instance {
    selectComponent(componentName: string): ViewComponentDescriptor;
}


export const DefaultViewComponentSelector: {
    new(descriptorProvider: IViewComponentDescriptorCollectionProvider): DefaultViewComponentSelector;
};


export interface __DefaultViewComponentSelector$views {
    As_IViewComponentSelector(): IViewComponentSelector$instance;
}

export interface DefaultViewComponentSelector$instance extends IViewComponentSelector$instance {}

export type DefaultViewComponentSelector = DefaultViewComponentSelector$instance & __DefaultViewComponentSelector$views;


export interface HtmlContentViewComponentResult$instance {
    readonly encodedContent: IHtmlContent;
    execute(context: ViewComponentContext): void;
    executeAsync(context: ViewComponentContext): Task;
}


export const HtmlContentViewComponentResult: {
    new(encodedContent: IHtmlContent): HtmlContentViewComponentResult;
};


export interface __HtmlContentViewComponentResult$views {
    As_IViewComponentResult(): Microsoft_AspNetCore_Mvc_Internal.IViewComponentResult$instance;
}

export interface HtmlContentViewComponentResult$instance extends Microsoft_AspNetCore_Mvc_Internal.IViewComponentResult$instance {}

export type HtmlContentViewComponentResult = HtmlContentViewComponentResult$instance & __HtmlContentViewComponentResult$views;


export interface ServiceBasedViewComponentActivator$instance {
    create(context: ViewComponentContext): unknown;
    release(context: ViewComponentContext, viewComponent: unknown): void;
}


export const ServiceBasedViewComponentActivator: {
    new(): ServiceBasedViewComponentActivator;
};


export interface __ServiceBasedViewComponentActivator$views {
    As_IViewComponentActivator(): IViewComponentActivator$instance;
}

export interface ServiceBasedViewComponentActivator$instance extends IViewComponentActivator$instance {}

export type ServiceBasedViewComponentActivator = ServiceBasedViewComponentActivator$instance & __ServiceBasedViewComponentActivator$views;


export interface ViewComponentContext$instance {
    arguments: IDictionary<System_Internal.String, unknown | undefined>;
    htmlEncoder: HtmlEncoder;
    readonly tempData: ITempDataDictionary;
    viewComponentDescriptor: ViewComponentDescriptor;
    viewContext: ViewContext;
    readonly viewData: ViewDataDictionary;
    readonly writer: TextWriter;
}


export const ViewComponentContext: {
    new(): ViewComponentContext;
    new(viewComponentDescriptor: ViewComponentDescriptor, arguments: IDictionary<System_Internal.String, unknown>, htmlEncoder: HtmlEncoder, viewContext: ViewContext, writer: TextWriter): ViewComponentContext;
};


export type ViewComponentContext = ViewComponentContext$instance;

export interface ViewComponentContextAttribute$instance extends Attribute {
}


export const ViewComponentContextAttribute: {
    new(): ViewComponentContextAttribute;
};


export type ViewComponentContextAttribute = ViewComponentContextAttribute$instance;

export interface ViewComponentDescriptor$instance {
    displayName: string;
    fullName: string;
    id: string;
    methodInfo: MethodInfo;
    parameters: IReadOnlyList<ParameterInfo>;
    shortName: string;
    typeInfo: TypeInfo;
}


export const ViewComponentDescriptor: {
    new(): ViewComponentDescriptor;
};


export type ViewComponentDescriptor = ViewComponentDescriptor$instance;

export interface ViewComponentDescriptorCollection$instance {
    readonly items: IReadOnlyList<ViewComponentDescriptor>;
    readonly version: int;
}


export const ViewComponentDescriptorCollection: {
    new(items: IEnumerable<ViewComponentDescriptor>, version: int): ViewComponentDescriptorCollection;
};


export type ViewComponentDescriptorCollection = ViewComponentDescriptorCollection$instance;

export interface ViewComponentFeature$instance {
    readonly viewComponents: IList<TypeInfo>;
}


export const ViewComponentFeature: {
    new(): ViewComponentFeature;
};


export type ViewComponentFeature = ViewComponentFeature$instance;

export interface ViewComponentFeatureProvider$instance extends IApplicationFeatureProvider {
    populateFeature(parts: IEnumerable<ApplicationPart>, feature: ViewComponentFeature): void;
}


export const ViewComponentFeatureProvider: {
    new(): ViewComponentFeatureProvider;
};


export interface __ViewComponentFeatureProvider$views {
    As_IApplicationFeatureProvider_1(): Microsoft_AspNetCore_Mvc_ApplicationParts_Internal.IApplicationFeatureProvider_1$instance<ViewComponentFeature>;
}

export interface ViewComponentFeatureProvider$instance extends Microsoft_AspNetCore_Mvc_ApplicationParts_Internal.IApplicationFeatureProvider_1$instance<ViewComponentFeature> {}

export type ViewComponentFeatureProvider = ViewComponentFeatureProvider$instance & __ViewComponentFeatureProvider$views;


export interface ViewViewComponentResult$instance {
    tempData: ITempDataDictionary;
    viewData: ViewDataDictionary;
    viewEngine: IViewEngine;
    viewName: string;
    execute(context: ViewComponentContext): void;
    executeAsync(context: ViewComponentContext): Task;
}


export const ViewViewComponentResult: {
    new(): ViewViewComponentResult;
};


export interface __ViewViewComponentResult$views {
    As_IViewComponentResult(): Microsoft_AspNetCore_Mvc_Internal.IViewComponentResult$instance;
}

export interface ViewViewComponentResult$instance extends Microsoft_AspNetCore_Mvc_Internal.IViewComponentResult$instance {}

export type ViewViewComponentResult = ViewViewComponentResult$instance & __ViewViewComponentResult$views;


export abstract class ViewComponentConventions$instance {
    static readonly viewComponentSuffix: string;
    static getComponentFullName(componentType: TypeInfo): string;
    static getComponentName(componentType: TypeInfo): string;
    static isComponent(typeInfo: TypeInfo): boolean;
}


export type ViewComponentConventions = ViewComponentConventions$instance;

