// Generated by tsbindgen - Architecture
// Namespace: Microsoft.AspNetCore.Http.Features.Authentication
// Assembly: Microsoft.AspNetCore.Http, Microsoft.AspNetCore.Http.Features

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Object as ClrObject } from "@tsonic/dotnet/System.js";
import type { ClaimsPrincipal } from "@tsonic/dotnet/System.Security.Claims.js";

export interface IHttpAuthenticationFeature$instance {
    User: ClaimsPrincipal;
}


export type IHttpAuthenticationFeature = IHttpAuthenticationFeature$instance;

export interface HttpAuthenticationFeature$instance {
    User: ClaimsPrincipal;
}


export const HttpAuthenticationFeature: {
    new(): HttpAuthenticationFeature;
};


export interface __HttpAuthenticationFeature$views {
    As_IHttpAuthenticationFeature(): IHttpAuthenticationFeature$instance;
}

export interface HttpAuthenticationFeature$instance extends IHttpAuthenticationFeature$instance {}

export type HttpAuthenticationFeature = HttpAuthenticationFeature$instance & __HttpAuthenticationFeature$views;


