// Generated by tsbindgen - Architecture
// Namespace: Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure
// Assembly: Microsoft.AspNetCore.Components.Web

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import * as Microsoft_AspNetCore_Components_RenderTree_Internal from "../../Microsoft.AspNetCore.Components.RenderTree/internal/index.js";
import type { EventFieldInfo, Renderer } from "../../Microsoft.AspNetCore.Components.RenderTree/internal/index.js";
import type { HtmlRootComponent } from "../../Microsoft.AspNetCore.Components.Web.HtmlRendering/internal/index.js";
import type { Dispatcher, IComponent, ParameterView } from "../../Microsoft.AspNetCore.Components/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Boolean as ClrBoolean, EventArgs, IAsyncDisposable, IDisposable, IServiceProvider, Type, UInt64, Void } from "@tsonic/dotnet/System.js";
import type { Task, ValueTask } from "@tsonic/dotnet/System.Threading.Tasks.js";
import type { ILoggerFactory } from "@tsonic/microsoft-extensions/Microsoft.Extensions.Logging.js";

export interface StaticHtmlRenderer$instance extends Renderer {
    readonly Dispatcher: Dispatcher;
    BeginRenderingComponent(componentType: Type, initialParameters: ParameterView): HtmlRootComponent;
    BeginRenderingComponent(component: IComponent, initialParameters: ParameterView): HtmlRootComponent;
}


export const StaticHtmlRenderer: {
    new(serviceProvider: IServiceProvider, loggerFactory: ILoggerFactory): StaticHtmlRenderer;
};


export type StaticHtmlRenderer = StaticHtmlRenderer$instance;

