// Generated by dotnet-bindgen - Architecture
// Namespace: Microsoft.AspNetCore
// Assembly: Microsoft.AspNetCore

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Import types from other namespaces
import type { IApplicationBuilder } from "../../Microsoft.AspNetCore.Builder/internal/index.js";
import type { IWebHost, IWebHostBuilder } from "../../Microsoft.AspNetCore.Hosting/internal/index.js";
import type { RequestDelegate } from "../../Microsoft.AspNetCore.Http/internal/index.js";
import type { IRouteBuilder } from "../../Microsoft.AspNetCore.Routing/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Action_1, Object as ClrObject, String as ClrString } from "@tsonic/dotnet/System/internal/index.js";

export abstract class WebHost$instance {
    static CreateDefaultBuilder(): IWebHostBuilder;
    static CreateDefaultBuilder(args: string[]): IWebHostBuilder;
    static Start(app: RequestDelegate): IWebHost;
    static Start(routeBuilder: Action_1<IRouteBuilder>): IWebHost;
    static Start(url: string, app: RequestDelegate): IWebHost;
    static Start(url: string, routeBuilder: Action_1<IRouteBuilder>): IWebHost;
    static StartWith(app: Action_1<IApplicationBuilder>): IWebHost;
    static StartWith(url: string, app: Action_1<IApplicationBuilder>): IWebHost;
}


export type WebHost = WebHost$instance;

