// Generated by tsbindgen - Architecture
// Namespace: Microsoft.AspNetCore.Http.HttpResults
// Assembly: Microsoft.AspNetCore.Components.Endpoints, Microsoft.AspNetCore.Http.Abstractions, Microsoft.AspNetCore.Http.Results

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { AuthenticationProperties } from "../../Microsoft.AspNetCore.Authentication/internal/index.js";
import type { EndpointBuilder } from "../../Microsoft.AspNetCore.Builder/internal/index.js";
import type { IComponent } from "../../Microsoft.AspNetCore.Components/internal/index.js";
import * as Microsoft_AspNetCore_Http_Metadata_Internal from "../../Microsoft.AspNetCore.Http.Metadata/internal/index.js";
import type { IEndpointMetadataProvider } from "../../Microsoft.AspNetCore.Http.Metadata/internal/index.js";
import * as Microsoft_AspNetCore_Http_Internal from "../../Microsoft.AspNetCore.Http/internal/index.js";
import type { HttpContext, HttpValidationProblemDetails, IContentTypeHttpResult, IFileHttpResult, INestedHttpResult, IResult, IStatusCodeHttpResult, IValueHttpResult, IValueHttpResult_1 } from "../../Microsoft.AspNetCore.Http/internal/index.js";
import * as Microsoft_AspNetCore_Mvc_Internal from "../../Microsoft.AspNetCore.Mvc/internal/index.js";
import type { ProblemDetails } from "../../Microsoft.AspNetCore.Mvc/internal/index.js";
import type { RouteValueDictionary } from "../../Microsoft.AspNetCore.Routing/internal/index.js";
import type { EntityTagHeaderValue } from "../../Microsoft.Net.Http.Headers/internal/index.js";
import type { IReadOnlyDictionary, IReadOnlyList } from "@tsonic/dotnet/System.Collections.Generic.js";
import type { Stream } from "@tsonic/dotnet/System.IO.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Boolean as ClrBoolean, Byte, DateTimeOffset, Int32, Int64, Nullable, Object as ClrObject, ReadOnlyMemory, String as ClrString, Type, Void } from "@tsonic/dotnet/System.js";
import type { MethodInfo } from "@tsonic/dotnet/System.Reflection.js";
import type { ClaimsPrincipal } from "@tsonic/dotnet/System.Security.Claims.js";
import type { JsonSerializerOptions } from "@tsonic/dotnet/System.Text.Json.js";
import type { Task } from "@tsonic/dotnet/System.Threading.Tasks.js";

export interface Accepted$instance {
    readonly location: string | undefined;
    readonly statusCode: int;
    executeAsync(httpContext: HttpContext): Task;
}


export const Accepted: {
    new(): Accepted;
};


export interface __Accepted$views {
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
    As_IStatusCodeHttpResult(): Microsoft_AspNetCore_Http_Internal.IStatusCodeHttpResult$instance;
    As_IEndpointMetadataProvider(): Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance;
}

export interface Accepted$instance extends Microsoft_AspNetCore_Http_Internal.IResult$instance, Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance {}

export type Accepted = Accepted$instance & __Accepted$views;


export interface Accepted_1$instance<TValue> {
    readonly location: string | undefined;
    readonly statusCode: int;
    readonly value: TValue;
    executeAsync(httpContext: HttpContext): Task;
}


export const Accepted_1: {
    new<TValue>(): Accepted_1<TValue>;
};


export interface __Accepted_1$views<TValue> {
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
    As_IStatusCodeHttpResult(): Microsoft_AspNetCore_Http_Internal.IStatusCodeHttpResult$instance;
    As_IValueHttpResult(): Microsoft_AspNetCore_Http_Internal.IValueHttpResult$instance;
    As_IValueHttpResult_1(): Microsoft_AspNetCore_Http_Internal.IValueHttpResult_1$instance<TValue>;
    As_IEndpointMetadataProvider(): Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance;
}

export interface Accepted_1$instance<TValue> extends Microsoft_AspNetCore_Http_Internal.IResult$instance, Microsoft_AspNetCore_Http_Internal.IValueHttpResult_1$instance<TValue>, Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance {}

export type Accepted_1<TValue> = Accepted_1$instance<TValue> & __Accepted_1$views<TValue>;


export interface AcceptedAtRoute$instance {
    readonly routeName: string | undefined;
    readonly routeValues: RouteValueDictionary;
    readonly statusCode: int;
    executeAsync(httpContext: HttpContext): Task;
}


export const AcceptedAtRoute: {
    new(): AcceptedAtRoute;
};


export interface __AcceptedAtRoute$views {
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
    As_IStatusCodeHttpResult(): Microsoft_AspNetCore_Http_Internal.IStatusCodeHttpResult$instance;
    As_IEndpointMetadataProvider(): Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance;
}

export interface AcceptedAtRoute$instance extends Microsoft_AspNetCore_Http_Internal.IResult$instance, Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance {}

export type AcceptedAtRoute = AcceptedAtRoute$instance & __AcceptedAtRoute$views;


export interface AcceptedAtRoute_1$instance<TValue> {
    readonly routeName: string | undefined;
    readonly routeValues: RouteValueDictionary;
    readonly statusCode: int;
    readonly value: TValue;
    executeAsync(httpContext: HttpContext): Task;
}


export const AcceptedAtRoute_1: {
    new<TValue>(): AcceptedAtRoute_1<TValue>;
};


export interface __AcceptedAtRoute_1$views<TValue> {
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
    As_IStatusCodeHttpResult(): Microsoft_AspNetCore_Http_Internal.IStatusCodeHttpResult$instance;
    As_IValueHttpResult(): Microsoft_AspNetCore_Http_Internal.IValueHttpResult$instance;
    As_IValueHttpResult_1(): Microsoft_AspNetCore_Http_Internal.IValueHttpResult_1$instance<TValue>;
    As_IEndpointMetadataProvider(): Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance;
}

export interface AcceptedAtRoute_1$instance<TValue> extends Microsoft_AspNetCore_Http_Internal.IResult$instance, Microsoft_AspNetCore_Http_Internal.IValueHttpResult_1$instance<TValue>, Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance {}

export type AcceptedAtRoute_1<TValue> = AcceptedAtRoute_1$instance<TValue> & __AcceptedAtRoute_1$views<TValue>;


export interface BadRequest$instance {
    readonly statusCode: int;
    executeAsync(httpContext: HttpContext): Task;
}


export const BadRequest: {
    new(): BadRequest;
};


export interface __BadRequest$views {
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
    As_IStatusCodeHttpResult(): Microsoft_AspNetCore_Http_Internal.IStatusCodeHttpResult$instance;
    As_IEndpointMetadataProvider(): Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance;
}

export interface BadRequest$instance extends Microsoft_AspNetCore_Http_Internal.IResult$instance, Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance {}

export type BadRequest = BadRequest$instance & __BadRequest$views;


export interface BadRequest_1$instance<TValue> {
    readonly statusCode: int;
    readonly value: TValue;
    executeAsync(httpContext: HttpContext): Task;
}


export const BadRequest_1: {
    new<TValue>(): BadRequest_1<TValue>;
};


export interface __BadRequest_1$views<TValue> {
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
    As_IStatusCodeHttpResult(): Microsoft_AspNetCore_Http_Internal.IStatusCodeHttpResult$instance;
    As_IValueHttpResult(): Microsoft_AspNetCore_Http_Internal.IValueHttpResult$instance;
    As_IValueHttpResult_1(): Microsoft_AspNetCore_Http_Internal.IValueHttpResult_1$instance<TValue>;
    As_IEndpointMetadataProvider(): Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance;
}

export interface BadRequest_1$instance<TValue> extends Microsoft_AspNetCore_Http_Internal.IResult$instance, Microsoft_AspNetCore_Http_Internal.IValueHttpResult_1$instance<TValue>, Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance {}

export type BadRequest_1<TValue> = BadRequest_1$instance<TValue> & __BadRequest_1$views<TValue>;


export interface ChallengeHttpResult$instance {
    readonly authenticationSchemes: IReadOnlyList<System_Internal.String>;
    readonly properties: AuthenticationProperties;
    executeAsync(httpContext: HttpContext): Task;
}


export const ChallengeHttpResult: {
    new(): ChallengeHttpResult;
};


export interface __ChallengeHttpResult$views {
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
}

export interface ChallengeHttpResult$instance extends Microsoft_AspNetCore_Http_Internal.IResult$instance {}

export type ChallengeHttpResult = ChallengeHttpResult$instance & __ChallengeHttpResult$views;


export interface Conflict$instance {
    readonly statusCode: int;
    executeAsync(httpContext: HttpContext): Task;
}


export const Conflict: {
    new(): Conflict;
};


export interface __Conflict$views {
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
    As_IStatusCodeHttpResult(): Microsoft_AspNetCore_Http_Internal.IStatusCodeHttpResult$instance;
    As_IEndpointMetadataProvider(): Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance;
}

export interface Conflict$instance extends Microsoft_AspNetCore_Http_Internal.IResult$instance, Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance {}

export type Conflict = Conflict$instance & __Conflict$views;


export interface Conflict_1$instance<TValue> {
    readonly statusCode: int;
    readonly value: TValue;
    executeAsync(httpContext: HttpContext): Task;
}


export const Conflict_1: {
    new<TValue>(): Conflict_1<TValue>;
};


export interface __Conflict_1$views<TValue> {
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
    As_IStatusCodeHttpResult(): Microsoft_AspNetCore_Http_Internal.IStatusCodeHttpResult$instance;
    As_IValueHttpResult(): Microsoft_AspNetCore_Http_Internal.IValueHttpResult$instance;
    As_IValueHttpResult_1(): Microsoft_AspNetCore_Http_Internal.IValueHttpResult_1$instance<TValue>;
    As_IEndpointMetadataProvider(): Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance;
}

export interface Conflict_1$instance<TValue> extends Microsoft_AspNetCore_Http_Internal.IResult$instance, Microsoft_AspNetCore_Http_Internal.IValueHttpResult_1$instance<TValue>, Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance {}

export type Conflict_1<TValue> = Conflict_1$instance<TValue> & __Conflict_1$views<TValue>;


export interface ContentHttpResult$instance {
    readonly contentType: string;
    readonly responseContent: string | undefined;
    readonly statusCode: Nullable<System_Internal.Int32>;
    executeAsync(httpContext: HttpContext): Task;
}


export const ContentHttpResult: {
    new(): ContentHttpResult;
};


export interface __ContentHttpResult$views {
    As_IContentTypeHttpResult(): Microsoft_AspNetCore_Http_Internal.IContentTypeHttpResult$instance;
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
    As_IStatusCodeHttpResult(): Microsoft_AspNetCore_Http_Internal.IStatusCodeHttpResult$instance;
}

export interface ContentHttpResult$instance extends Microsoft_AspNetCore_Http_Internal.IContentTypeHttpResult$instance, Microsoft_AspNetCore_Http_Internal.IResult$instance, Microsoft_AspNetCore_Http_Internal.IStatusCodeHttpResult$instance {}

export type ContentHttpResult = ContentHttpResult$instance & __ContentHttpResult$views;


export interface Created$instance {
    readonly location: string | undefined;
    readonly statusCode: int;
    executeAsync(httpContext: HttpContext): Task;
}


export const Created: {
    new(): Created;
};


export interface __Created$views {
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
    As_IStatusCodeHttpResult(): Microsoft_AspNetCore_Http_Internal.IStatusCodeHttpResult$instance;
    As_IEndpointMetadataProvider(): Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance;
}

export interface Created$instance extends Microsoft_AspNetCore_Http_Internal.IResult$instance, Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance {}

export type Created = Created$instance & __Created$views;


export interface Created_1$instance<TValue> {
    readonly location: string | undefined;
    readonly statusCode: int;
    readonly value: TValue;
    executeAsync(httpContext: HttpContext): Task;
}


export const Created_1: {
    new<TValue>(): Created_1<TValue>;
};


export interface __Created_1$views<TValue> {
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
    As_IStatusCodeHttpResult(): Microsoft_AspNetCore_Http_Internal.IStatusCodeHttpResult$instance;
    As_IValueHttpResult(): Microsoft_AspNetCore_Http_Internal.IValueHttpResult$instance;
    As_IValueHttpResult_1(): Microsoft_AspNetCore_Http_Internal.IValueHttpResult_1$instance<TValue>;
    As_IEndpointMetadataProvider(): Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance;
}

export interface Created_1$instance<TValue> extends Microsoft_AspNetCore_Http_Internal.IResult$instance, Microsoft_AspNetCore_Http_Internal.IValueHttpResult_1$instance<TValue>, Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance {}

export type Created_1<TValue> = Created_1$instance<TValue> & __Created_1$views<TValue>;


export interface CreatedAtRoute$instance {
    readonly routeName: string | undefined;
    readonly routeValues: RouteValueDictionary;
    readonly statusCode: int;
    executeAsync(httpContext: HttpContext): Task;
}


export const CreatedAtRoute: {
    new(): CreatedAtRoute;
};


export interface __CreatedAtRoute$views {
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
    As_IStatusCodeHttpResult(): Microsoft_AspNetCore_Http_Internal.IStatusCodeHttpResult$instance;
    As_IEndpointMetadataProvider(): Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance;
}

export interface CreatedAtRoute$instance extends Microsoft_AspNetCore_Http_Internal.IResult$instance, Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance {}

export type CreatedAtRoute = CreatedAtRoute$instance & __CreatedAtRoute$views;


export interface CreatedAtRoute_1$instance<TValue> {
    readonly routeName: string | undefined;
    readonly routeValues: RouteValueDictionary;
    readonly statusCode: int;
    readonly value: TValue;
    executeAsync(httpContext: HttpContext): Task;
}


export const CreatedAtRoute_1: {
    new<TValue>(): CreatedAtRoute_1<TValue>;
};


export interface __CreatedAtRoute_1$views<TValue> {
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
    As_IStatusCodeHttpResult(): Microsoft_AspNetCore_Http_Internal.IStatusCodeHttpResult$instance;
    As_IValueHttpResult(): Microsoft_AspNetCore_Http_Internal.IValueHttpResult$instance;
    As_IValueHttpResult_1(): Microsoft_AspNetCore_Http_Internal.IValueHttpResult_1$instance<TValue>;
    As_IEndpointMetadataProvider(): Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance;
}

export interface CreatedAtRoute_1$instance<TValue> extends Microsoft_AspNetCore_Http_Internal.IResult$instance, Microsoft_AspNetCore_Http_Internal.IValueHttpResult_1$instance<TValue>, Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance {}

export type CreatedAtRoute_1<TValue> = CreatedAtRoute_1$instance<TValue> & __CreatedAtRoute_1$views<TValue>;


export interface EmptyHttpResult$instance {
    executeAsync(httpContext: HttpContext): Task;
}


export const EmptyHttpResult: {
    new(): EmptyHttpResult;
    readonly instance: EmptyHttpResult;
};


export interface __EmptyHttpResult$views {
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
}

export interface EmptyHttpResult$instance extends Microsoft_AspNetCore_Http_Internal.IResult$instance {}

export type EmptyHttpResult = EmptyHttpResult$instance & __EmptyHttpResult$views;


export interface FileContentHttpResult$instance {
    readonly contentType: string;
    readonly enableRangeProcessing: boolean;
    readonly entityTag: EntityTagHeaderValue | undefined;
    readonly fileContents: ReadOnlyMemory<System_Internal.Byte>;
    readonly fileDownloadName: string;
    readonly fileLength: Nullable<System_Internal.Int64>;
    readonly lastModified: Nullable<DateTimeOffset>;
    executeAsync(httpContext: HttpContext): Task;
}


export const FileContentHttpResult: {
    new(): FileContentHttpResult;
};


export interface __FileContentHttpResult$views {
    As_IContentTypeHttpResult(): Microsoft_AspNetCore_Http_Internal.IContentTypeHttpResult$instance;
    As_IFileHttpResult(): Microsoft_AspNetCore_Http_Internal.IFileHttpResult$instance;
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
}

export interface FileContentHttpResult$instance extends Microsoft_AspNetCore_Http_Internal.IContentTypeHttpResult$instance, Microsoft_AspNetCore_Http_Internal.IFileHttpResult$instance, Microsoft_AspNetCore_Http_Internal.IResult$instance {}

export type FileContentHttpResult = FileContentHttpResult$instance & __FileContentHttpResult$views;


export interface FileStreamHttpResult$instance {
    readonly contentType: string;
    readonly enableRangeProcessing: boolean;
    readonly entityTag: EntityTagHeaderValue | undefined;
    readonly fileDownloadName: string;
    readonly fileLength: Nullable<System_Internal.Int64>;
    readonly fileStream: Stream;
    readonly lastModified: Nullable<DateTimeOffset>;
    executeAsync(httpContext: HttpContext): Task;
}


export const FileStreamHttpResult: {
    new(): FileStreamHttpResult;
};


export interface __FileStreamHttpResult$views {
    As_IContentTypeHttpResult(): Microsoft_AspNetCore_Http_Internal.IContentTypeHttpResult$instance;
    As_IFileHttpResult(): Microsoft_AspNetCore_Http_Internal.IFileHttpResult$instance;
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
}

export interface FileStreamHttpResult$instance extends Microsoft_AspNetCore_Http_Internal.IContentTypeHttpResult$instance, Microsoft_AspNetCore_Http_Internal.IFileHttpResult$instance, Microsoft_AspNetCore_Http_Internal.IResult$instance {}

export type FileStreamHttpResult = FileStreamHttpResult$instance & __FileStreamHttpResult$views;


export interface ForbidHttpResult$instance {
    readonly authenticationSchemes: IReadOnlyList<System_Internal.String>;
    readonly properties: AuthenticationProperties;
    executeAsync(httpContext: HttpContext): Task;
}


export const ForbidHttpResult: {
    new(): ForbidHttpResult;
};


export interface __ForbidHttpResult$views {
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
}

export interface ForbidHttpResult$instance extends Microsoft_AspNetCore_Http_Internal.IResult$instance {}

export type ForbidHttpResult = ForbidHttpResult$instance & __ForbidHttpResult$views;


export interface InternalServerError$instance {
    readonly statusCode: int;
    executeAsync(httpContext: HttpContext): Task;
}


export const InternalServerError: {
    new(): InternalServerError;
};


export interface __InternalServerError$views {
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
    As_IStatusCodeHttpResult(): Microsoft_AspNetCore_Http_Internal.IStatusCodeHttpResult$instance;
    As_IEndpointMetadataProvider(): Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance;
}

export interface InternalServerError$instance extends Microsoft_AspNetCore_Http_Internal.IResult$instance, Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance {}

export type InternalServerError = InternalServerError$instance & __InternalServerError$views;


export interface InternalServerError_1$instance<TValue> {
    readonly statusCode: int;
    readonly value: TValue;
    executeAsync(httpContext: HttpContext): Task;
}


export const InternalServerError_1: {
    new<TValue>(): InternalServerError_1<TValue>;
};


export interface __InternalServerError_1$views<TValue> {
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
    As_IStatusCodeHttpResult(): Microsoft_AspNetCore_Http_Internal.IStatusCodeHttpResult$instance;
    As_IValueHttpResult(): Microsoft_AspNetCore_Http_Internal.IValueHttpResult$instance;
    As_IValueHttpResult_1(): Microsoft_AspNetCore_Http_Internal.IValueHttpResult_1$instance<TValue>;
    As_IEndpointMetadataProvider(): Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance;
}

export interface InternalServerError_1$instance<TValue> extends Microsoft_AspNetCore_Http_Internal.IResult$instance, Microsoft_AspNetCore_Http_Internal.IValueHttpResult_1$instance<TValue>, Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance {}

export type InternalServerError_1<TValue> = InternalServerError_1$instance<TValue> & __InternalServerError_1$views<TValue>;


export interface JsonHttpResult_1$instance<TValue> {
    readonly contentType: string;
    readonly jsonSerializerOptions: JsonSerializerOptions;
    readonly statusCode: Nullable<System_Internal.Int32>;
    readonly value: TValue;
    executeAsync(httpContext: HttpContext): Task;
}


export const JsonHttpResult_1: {
    new<TValue>(): JsonHttpResult_1<TValue>;
};


export interface __JsonHttpResult_1$views<TValue> {
    As_IContentTypeHttpResult(): Microsoft_AspNetCore_Http_Internal.IContentTypeHttpResult$instance;
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
    As_IStatusCodeHttpResult(): Microsoft_AspNetCore_Http_Internal.IStatusCodeHttpResult$instance;
    As_IValueHttpResult(): Microsoft_AspNetCore_Http_Internal.IValueHttpResult$instance;
    As_IValueHttpResult_1(): Microsoft_AspNetCore_Http_Internal.IValueHttpResult_1$instance<TValue>;
    As_IEndpointMetadataProvider(): Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance;
}

export interface JsonHttpResult_1$instance<TValue> extends Microsoft_AspNetCore_Http_Internal.IContentTypeHttpResult$instance, Microsoft_AspNetCore_Http_Internal.IResult$instance, Microsoft_AspNetCore_Http_Internal.IStatusCodeHttpResult$instance, Microsoft_AspNetCore_Http_Internal.IValueHttpResult_1$instance<TValue>, Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance {}

export type JsonHttpResult_1<TValue> = JsonHttpResult_1$instance<TValue> & __JsonHttpResult_1$views<TValue>;


export interface NoContent$instance {
    readonly statusCode: int;
    executeAsync(httpContext: HttpContext): Task;
}


export const NoContent: {
    new(): NoContent;
};


export interface __NoContent$views {
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
    As_IStatusCodeHttpResult(): Microsoft_AspNetCore_Http_Internal.IStatusCodeHttpResult$instance;
    As_IEndpointMetadataProvider(): Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance;
}

export interface NoContent$instance extends Microsoft_AspNetCore_Http_Internal.IResult$instance, Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance {}

export type NoContent = NoContent$instance & __NoContent$views;


export interface NotFound$instance {
    readonly statusCode: int;
    executeAsync(httpContext: HttpContext): Task;
}


export const NotFound: {
    new(): NotFound;
};


export interface __NotFound$views {
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
    As_IStatusCodeHttpResult(): Microsoft_AspNetCore_Http_Internal.IStatusCodeHttpResult$instance;
    As_IEndpointMetadataProvider(): Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance;
}

export interface NotFound$instance extends Microsoft_AspNetCore_Http_Internal.IResult$instance, Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance {}

export type NotFound = NotFound$instance & __NotFound$views;


export interface NotFound_1$instance<TValue> {
    readonly statusCode: int;
    readonly value: TValue;
    executeAsync(httpContext: HttpContext): Task;
}


export const NotFound_1: {
    new<TValue>(): NotFound_1<TValue>;
};


export interface __NotFound_1$views<TValue> {
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
    As_IStatusCodeHttpResult(): Microsoft_AspNetCore_Http_Internal.IStatusCodeHttpResult$instance;
    As_IValueHttpResult(): Microsoft_AspNetCore_Http_Internal.IValueHttpResult$instance;
    As_IValueHttpResult_1(): Microsoft_AspNetCore_Http_Internal.IValueHttpResult_1$instance<TValue>;
    As_IEndpointMetadataProvider(): Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance;
}

export interface NotFound_1$instance<TValue> extends Microsoft_AspNetCore_Http_Internal.IResult$instance, Microsoft_AspNetCore_Http_Internal.IValueHttpResult_1$instance<TValue>, Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance {}

export type NotFound_1<TValue> = NotFound_1$instance<TValue> & __NotFound_1$views<TValue>;


export interface Ok$instance {
    readonly statusCode: int;
    executeAsync(httpContext: HttpContext): Task;
}


export const Ok: {
    new(): Ok;
};


export interface __Ok$views {
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
    As_IStatusCodeHttpResult(): Microsoft_AspNetCore_Http_Internal.IStatusCodeHttpResult$instance;
    As_IEndpointMetadataProvider(): Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance;
}

export interface Ok$instance extends Microsoft_AspNetCore_Http_Internal.IResult$instance, Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance {}

export type Ok = Ok$instance & __Ok$views;


export interface Ok_1$instance<TValue> {
    readonly statusCode: int;
    readonly value: TValue;
    executeAsync(httpContext: HttpContext): Task;
}


export const Ok_1: {
    new<TValue>(): Ok_1<TValue>;
};


export interface __Ok_1$views<TValue> {
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
    As_IStatusCodeHttpResult(): Microsoft_AspNetCore_Http_Internal.IStatusCodeHttpResult$instance;
    As_IValueHttpResult(): Microsoft_AspNetCore_Http_Internal.IValueHttpResult$instance;
    As_IValueHttpResult_1(): Microsoft_AspNetCore_Http_Internal.IValueHttpResult_1$instance<TValue>;
    As_IEndpointMetadataProvider(): Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance;
}

export interface Ok_1$instance<TValue> extends Microsoft_AspNetCore_Http_Internal.IResult$instance, Microsoft_AspNetCore_Http_Internal.IValueHttpResult_1$instance<TValue>, Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance {}

export type Ok_1<TValue> = Ok_1$instance<TValue> & __Ok_1$views<TValue>;


export interface PhysicalFileHttpResult$instance {
    readonly contentType: string;
    readonly enableRangeProcessing: boolean;
    readonly entityTag: EntityTagHeaderValue | undefined;
    readonly fileDownloadName: string;
    readonly fileLength: Nullable<System_Internal.Int64>;
    readonly fileName: string;
    readonly lastModified: Nullable<DateTimeOffset>;
    executeAsync(httpContext: HttpContext): Task;
}


export const PhysicalFileHttpResult: {
    new(): PhysicalFileHttpResult;
};


export interface __PhysicalFileHttpResult$views {
    As_IContentTypeHttpResult(): Microsoft_AspNetCore_Http_Internal.IContentTypeHttpResult$instance;
    As_IFileHttpResult(): Microsoft_AspNetCore_Http_Internal.IFileHttpResult$instance;
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
}

export interface PhysicalFileHttpResult$instance extends Microsoft_AspNetCore_Http_Internal.IContentTypeHttpResult$instance, Microsoft_AspNetCore_Http_Internal.IFileHttpResult$instance, Microsoft_AspNetCore_Http_Internal.IResult$instance {}

export type PhysicalFileHttpResult = PhysicalFileHttpResult$instance & __PhysicalFileHttpResult$views;


export interface ProblemHttpResult$instance {
    readonly contentType: string;
    readonly problemDetails: ProblemDetails;
    readonly statusCode: int;
    executeAsync(httpContext: HttpContext): Task;
}


export const ProblemHttpResult: {
    new(): ProblemHttpResult;
};


export interface __ProblemHttpResult$views {
    As_IContentTypeHttpResult(): Microsoft_AspNetCore_Http_Internal.IContentTypeHttpResult$instance;
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
    As_IStatusCodeHttpResult(): Microsoft_AspNetCore_Http_Internal.IStatusCodeHttpResult$instance;
    As_IValueHttpResult(): Microsoft_AspNetCore_Http_Internal.IValueHttpResult$instance;
    As_IValueHttpResult_1(): Microsoft_AspNetCore_Http_Internal.IValueHttpResult_1$instance<ProblemDetails>;
    As_IEndpointMetadataProvider(): Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance;
}

export interface ProblemHttpResult$instance extends Microsoft_AspNetCore_Http_Internal.IContentTypeHttpResult$instance, Microsoft_AspNetCore_Http_Internal.IResult$instance, Microsoft_AspNetCore_Http_Internal.IValueHttpResult$instance, Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance {}

export type ProblemHttpResult = ProblemHttpResult$instance & __ProblemHttpResult$views;


export interface PushStreamHttpResult$instance {
    readonly contentType: string;
    readonly enableRangeProcessing: boolean;
    readonly entityTag: EntityTagHeaderValue | undefined;
    readonly fileDownloadName: string;
    readonly fileLength: Nullable<System_Internal.Int64>;
    readonly lastModified: Nullable<DateTimeOffset>;
    executeAsync(httpContext: HttpContext): Task;
}


export const PushStreamHttpResult: {
    new(): PushStreamHttpResult;
};


export interface __PushStreamHttpResult$views {
    As_IContentTypeHttpResult(): Microsoft_AspNetCore_Http_Internal.IContentTypeHttpResult$instance;
    As_IFileHttpResult(): Microsoft_AspNetCore_Http_Internal.IFileHttpResult$instance;
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
}

export interface PushStreamHttpResult$instance extends Microsoft_AspNetCore_Http_Internal.IContentTypeHttpResult$instance, Microsoft_AspNetCore_Http_Internal.IFileHttpResult$instance, Microsoft_AspNetCore_Http_Internal.IResult$instance {}

export type PushStreamHttpResult = PushStreamHttpResult$instance & __PushStreamHttpResult$views;


export interface RazorComponentResult$instance {
    readonly componentType: Type;
    contentType: string;
    readonly parameters: IReadOnlyDictionary<System_Internal.String, unknown | undefined>;
    preventStreamingRendering: boolean;
    statusCode: Nullable<System_Internal.Int32>;
    executeAsync(httpContext: HttpContext): Task;
}


export const RazorComponentResult: {
    new(componentType: Type): RazorComponentResult;
    new(componentType: Type, parameters: unknown): RazorComponentResult;
    new(componentType: Type, parameters: IReadOnlyDictionary<System_Internal.String, unknown>): RazorComponentResult;
};


export interface __RazorComponentResult$views {
    As_IContentTypeHttpResult(): Microsoft_AspNetCore_Http_Internal.IContentTypeHttpResult$instance;
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
    As_IStatusCodeHttpResult(): Microsoft_AspNetCore_Http_Internal.IStatusCodeHttpResult$instance;
}

export interface RazorComponentResult$instance extends Microsoft_AspNetCore_Http_Internal.IResult$instance {}

export type RazorComponentResult = RazorComponentResult$instance & __RazorComponentResult$views;


export interface RazorComponentResult_1$instance<TComponent extends IComponent> extends RazorComponentResult$instance {
    executeAsync(httpContext: HttpContext): Task;
}


export const RazorComponentResult_1: {
    new<TComponent extends IComponent>(): RazorComponentResult_1<TComponent>;
    new<TComponent extends IComponent>(parameters: unknown): RazorComponentResult_1<TComponent>;
    new<TComponent extends IComponent>(parameters: IReadOnlyDictionary<System_Internal.String, unknown>): RazorComponentResult_1<TComponent>;
};


export interface __RazorComponentResult_1$views<TComponent extends IComponent> {
    As_IContentTypeHttpResult(): Microsoft_AspNetCore_Http_Internal.IContentTypeHttpResult$instance;
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
    As_IStatusCodeHttpResult(): Microsoft_AspNetCore_Http_Internal.IStatusCodeHttpResult$instance;
}

export type RazorComponentResult_1<TComponent extends IComponent> = RazorComponentResult_1$instance<TComponent> & __RazorComponentResult_1$views<TComponent>;


export interface RedirectHttpResult$instance {
    readonly acceptLocalUrlOnly: boolean;
    readonly permanent: boolean;
    readonly preserveMethod: boolean;
    readonly url: string;
    executeAsync(httpContext: HttpContext): Task;
}


export const RedirectHttpResult: {
    new(): RedirectHttpResult;
    isLocalUrl(url: string): boolean;
};


export interface __RedirectHttpResult$views {
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
}

export interface RedirectHttpResult$instance extends Microsoft_AspNetCore_Http_Internal.IResult$instance {}

export type RedirectHttpResult = RedirectHttpResult$instance & __RedirectHttpResult$views;


export interface RedirectToRouteHttpResult$instance {
    readonly fragment: string | undefined;
    readonly permanent: boolean;
    readonly preserveMethod: boolean;
    readonly routeName: string | undefined;
    readonly routeValues: RouteValueDictionary;
    executeAsync(httpContext: HttpContext): Task;
}


export const RedirectToRouteHttpResult: {
    new(): RedirectToRouteHttpResult;
};


export interface __RedirectToRouteHttpResult$views {
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
}

export interface RedirectToRouteHttpResult$instance extends Microsoft_AspNetCore_Http_Internal.IResult$instance {}

export type RedirectToRouteHttpResult = RedirectToRouteHttpResult$instance & __RedirectToRouteHttpResult$views;


export interface Results_2$instance<TResult1 extends IResult, TResult2 extends IResult> {
    readonly result: IResult;
    executeAsync(httpContext: HttpContext): Task;
}


export const Results_2: {
    new<TResult1 extends IResult, TResult2 extends IResult>(): Results_2<TResult1, TResult2>;
};


export interface __Results_2$views<TResult1 extends IResult, TResult2 extends IResult> {
    As_INestedHttpResult(): Microsoft_AspNetCore_Http_Internal.INestedHttpResult$instance;
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
    As_IEndpointMetadataProvider(): Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance;
}

export interface Results_2$instance<TResult1 extends IResult, TResult2 extends IResult> extends Microsoft_AspNetCore_Http_Internal.INestedHttpResult$instance, Microsoft_AspNetCore_Http_Internal.IResult$instance, Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance {}

export type Results_2<TResult1 extends IResult, TResult2 extends IResult> = Results_2$instance<TResult1, TResult2> & __Results_2$views<TResult1, TResult2>;


export interface Results_3$instance<TResult1 extends IResult, TResult2 extends IResult, TResult3 extends IResult> {
    readonly result: IResult;
    executeAsync(httpContext: HttpContext): Task;
}


export const Results_3: {
    new<TResult1 extends IResult, TResult2 extends IResult, TResult3 extends IResult>(): Results_3<TResult1, TResult2, TResult3>;
};


export interface __Results_3$views<TResult1 extends IResult, TResult2 extends IResult, TResult3 extends IResult> {
    As_INestedHttpResult(): Microsoft_AspNetCore_Http_Internal.INestedHttpResult$instance;
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
    As_IEndpointMetadataProvider(): Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance;
}

export interface Results_3$instance<TResult1 extends IResult, TResult2 extends IResult, TResult3 extends IResult> extends Microsoft_AspNetCore_Http_Internal.INestedHttpResult$instance, Microsoft_AspNetCore_Http_Internal.IResult$instance, Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance {}

export type Results_3<TResult1 extends IResult, TResult2 extends IResult, TResult3 extends IResult> = Results_3$instance<TResult1, TResult2, TResult3> & __Results_3$views<TResult1, TResult2, TResult3>;


export interface Results_4$instance<TResult1 extends IResult, TResult2 extends IResult, TResult3 extends IResult, TResult4 extends IResult> {
    readonly result: IResult;
    executeAsync(httpContext: HttpContext): Task;
}


export const Results_4: {
    new<TResult1 extends IResult, TResult2 extends IResult, TResult3 extends IResult, TResult4 extends IResult>(): Results_4<TResult1, TResult2, TResult3, TResult4>;
};


export interface __Results_4$views<TResult1 extends IResult, TResult2 extends IResult, TResult3 extends IResult, TResult4 extends IResult> {
    As_INestedHttpResult(): Microsoft_AspNetCore_Http_Internal.INestedHttpResult$instance;
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
    As_IEndpointMetadataProvider(): Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance;
}

export interface Results_4$instance<TResult1 extends IResult, TResult2 extends IResult, TResult3 extends IResult, TResult4 extends IResult> extends Microsoft_AspNetCore_Http_Internal.INestedHttpResult$instance, Microsoft_AspNetCore_Http_Internal.IResult$instance, Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance {}

export type Results_4<TResult1 extends IResult, TResult2 extends IResult, TResult3 extends IResult, TResult4 extends IResult> = Results_4$instance<TResult1, TResult2, TResult3, TResult4> & __Results_4$views<TResult1, TResult2, TResult3, TResult4>;


export interface Results_5$instance<TResult1 extends IResult, TResult2 extends IResult, TResult3 extends IResult, TResult4 extends IResult, TResult5 extends IResult> {
    readonly result: IResult;
    executeAsync(httpContext: HttpContext): Task;
}


export const Results_5: {
    new<TResult1 extends IResult, TResult2 extends IResult, TResult3 extends IResult, TResult4 extends IResult, TResult5 extends IResult>(): Results_5<TResult1, TResult2, TResult3, TResult4, TResult5>;
};


export interface __Results_5$views<TResult1 extends IResult, TResult2 extends IResult, TResult3 extends IResult, TResult4 extends IResult, TResult5 extends IResult> {
    As_INestedHttpResult(): Microsoft_AspNetCore_Http_Internal.INestedHttpResult$instance;
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
    As_IEndpointMetadataProvider(): Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance;
}

export interface Results_5$instance<TResult1 extends IResult, TResult2 extends IResult, TResult3 extends IResult, TResult4 extends IResult, TResult5 extends IResult> extends Microsoft_AspNetCore_Http_Internal.INestedHttpResult$instance, Microsoft_AspNetCore_Http_Internal.IResult$instance, Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance {}

export type Results_5<TResult1 extends IResult, TResult2 extends IResult, TResult3 extends IResult, TResult4 extends IResult, TResult5 extends IResult> = Results_5$instance<TResult1, TResult2, TResult3, TResult4, TResult5> & __Results_5$views<TResult1, TResult2, TResult3, TResult4, TResult5>;


export interface Results_6$instance<TResult1 extends IResult, TResult2 extends IResult, TResult3 extends IResult, TResult4 extends IResult, TResult5 extends IResult, TResult6 extends IResult> {
    readonly result: IResult;
    executeAsync(httpContext: HttpContext): Task;
}


export const Results_6: {
    new<TResult1 extends IResult, TResult2 extends IResult, TResult3 extends IResult, TResult4 extends IResult, TResult5 extends IResult, TResult6 extends IResult>(): Results_6<TResult1, TResult2, TResult3, TResult4, TResult5, TResult6>;
};


export interface __Results_6$views<TResult1 extends IResult, TResult2 extends IResult, TResult3 extends IResult, TResult4 extends IResult, TResult5 extends IResult, TResult6 extends IResult> {
    As_INestedHttpResult(): Microsoft_AspNetCore_Http_Internal.INestedHttpResult$instance;
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
    As_IEndpointMetadataProvider(): Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance;
}

export interface Results_6$instance<TResult1 extends IResult, TResult2 extends IResult, TResult3 extends IResult, TResult4 extends IResult, TResult5 extends IResult, TResult6 extends IResult> extends Microsoft_AspNetCore_Http_Internal.INestedHttpResult$instance, Microsoft_AspNetCore_Http_Internal.IResult$instance, Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance {}

export type Results_6<TResult1 extends IResult, TResult2 extends IResult, TResult3 extends IResult, TResult4 extends IResult, TResult5 extends IResult, TResult6 extends IResult> = Results_6$instance<TResult1, TResult2, TResult3, TResult4, TResult5, TResult6> & __Results_6$views<TResult1, TResult2, TResult3, TResult4, TResult5, TResult6>;


export interface ServerSentEventsResult_1$instance<T> {
    readonly statusCode: Nullable<System_Internal.Int32>;
    executeAsync(httpContext: HttpContext): Task;
}


export const ServerSentEventsResult_1: {
    new<T>(): ServerSentEventsResult_1<T>;
};


export interface __ServerSentEventsResult_1$views<T> {
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
    As_IStatusCodeHttpResult(): Microsoft_AspNetCore_Http_Internal.IStatusCodeHttpResult$instance;
    As_IEndpointMetadataProvider(): Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance;
}

export interface ServerSentEventsResult_1$instance<T> extends Microsoft_AspNetCore_Http_Internal.IResult$instance, Microsoft_AspNetCore_Http_Internal.IStatusCodeHttpResult$instance, Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance {}

export type ServerSentEventsResult_1<T> = ServerSentEventsResult_1$instance<T> & __ServerSentEventsResult_1$views<T>;


export interface SignInHttpResult$instance {
    readonly authenticationScheme: string;
    readonly principal: ClaimsPrincipal;
    readonly properties: AuthenticationProperties;
    executeAsync(httpContext: HttpContext): Task;
}


export const SignInHttpResult: {
    new(): SignInHttpResult;
};


export interface __SignInHttpResult$views {
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
}

export interface SignInHttpResult$instance extends Microsoft_AspNetCore_Http_Internal.IResult$instance {}

export type SignInHttpResult = SignInHttpResult$instance & __SignInHttpResult$views;


export interface SignOutHttpResult$instance {
    readonly authenticationSchemes: IReadOnlyList<System_Internal.String>;
    readonly properties: AuthenticationProperties;
    executeAsync(httpContext: HttpContext): Task;
}


export const SignOutHttpResult: {
    new(): SignOutHttpResult;
};


export interface __SignOutHttpResult$views {
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
}

export interface SignOutHttpResult$instance extends Microsoft_AspNetCore_Http_Internal.IResult$instance {}

export type SignOutHttpResult = SignOutHttpResult$instance & __SignOutHttpResult$views;


export interface StatusCodeHttpResult$instance {
    readonly statusCode: int;
    executeAsync(httpContext: HttpContext): Task;
}


export const StatusCodeHttpResult: {
    new(): StatusCodeHttpResult;
};


export interface __StatusCodeHttpResult$views {
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
    As_IStatusCodeHttpResult(): Microsoft_AspNetCore_Http_Internal.IStatusCodeHttpResult$instance;
}

export interface StatusCodeHttpResult$instance extends Microsoft_AspNetCore_Http_Internal.IResult$instance {}

export type StatusCodeHttpResult = StatusCodeHttpResult$instance & __StatusCodeHttpResult$views;


export interface UnauthorizedHttpResult$instance {
    readonly statusCode: int;
    executeAsync(httpContext: HttpContext): Task;
}


export const UnauthorizedHttpResult: {
    new(): UnauthorizedHttpResult;
};


export interface __UnauthorizedHttpResult$views {
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
    As_IStatusCodeHttpResult(): Microsoft_AspNetCore_Http_Internal.IStatusCodeHttpResult$instance;
}

export interface UnauthorizedHttpResult$instance extends Microsoft_AspNetCore_Http_Internal.IResult$instance {}

export type UnauthorizedHttpResult = UnauthorizedHttpResult$instance & __UnauthorizedHttpResult$views;


export interface UnprocessableEntity$instance {
    readonly statusCode: int;
    executeAsync(httpContext: HttpContext): Task;
}


export const UnprocessableEntity: {
    new(): UnprocessableEntity;
};


export interface __UnprocessableEntity$views {
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
    As_IStatusCodeHttpResult(): Microsoft_AspNetCore_Http_Internal.IStatusCodeHttpResult$instance;
    As_IEndpointMetadataProvider(): Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance;
}

export interface UnprocessableEntity$instance extends Microsoft_AspNetCore_Http_Internal.IResult$instance, Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance {}

export type UnprocessableEntity = UnprocessableEntity$instance & __UnprocessableEntity$views;


export interface UnprocessableEntity_1$instance<TValue> {
    readonly statusCode: int;
    readonly value: TValue;
    executeAsync(httpContext: HttpContext): Task;
}


export const UnprocessableEntity_1: {
    new<TValue>(): UnprocessableEntity_1<TValue>;
};


export interface __UnprocessableEntity_1$views<TValue> {
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
    As_IStatusCodeHttpResult(): Microsoft_AspNetCore_Http_Internal.IStatusCodeHttpResult$instance;
    As_IValueHttpResult(): Microsoft_AspNetCore_Http_Internal.IValueHttpResult$instance;
    As_IValueHttpResult_1(): Microsoft_AspNetCore_Http_Internal.IValueHttpResult_1$instance<TValue>;
    As_IEndpointMetadataProvider(): Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance;
}

export interface UnprocessableEntity_1$instance<TValue> extends Microsoft_AspNetCore_Http_Internal.IResult$instance, Microsoft_AspNetCore_Http_Internal.IValueHttpResult_1$instance<TValue>, Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance {}

export type UnprocessableEntity_1<TValue> = UnprocessableEntity_1$instance<TValue> & __UnprocessableEntity_1$views<TValue>;


export interface Utf8ContentHttpResult$instance {
    readonly contentType: string;
    readonly responseContent: ReadOnlyMemory<System_Internal.Byte>;
    readonly statusCode: Nullable<System_Internal.Int32>;
    executeAsync(httpContext: HttpContext): Task;
}


export const Utf8ContentHttpResult: {
    new(): Utf8ContentHttpResult;
};


export interface __Utf8ContentHttpResult$views {
    As_IContentTypeHttpResult(): Microsoft_AspNetCore_Http_Internal.IContentTypeHttpResult$instance;
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
    As_IStatusCodeHttpResult(): Microsoft_AspNetCore_Http_Internal.IStatusCodeHttpResult$instance;
}

export interface Utf8ContentHttpResult$instance extends Microsoft_AspNetCore_Http_Internal.IContentTypeHttpResult$instance, Microsoft_AspNetCore_Http_Internal.IResult$instance, Microsoft_AspNetCore_Http_Internal.IStatusCodeHttpResult$instance {}

export type Utf8ContentHttpResult = Utf8ContentHttpResult$instance & __Utf8ContentHttpResult$views;


export interface ValidationProblem$instance {
    readonly contentType: string;
    readonly problemDetails: HttpValidationProblemDetails;
    readonly statusCode: int;
    executeAsync(httpContext: HttpContext): Task;
}


export const ValidationProblem: {
    new(): ValidationProblem;
};


export interface __ValidationProblem$views {
    As_IContentTypeHttpResult(): Microsoft_AspNetCore_Http_Internal.IContentTypeHttpResult$instance;
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
    As_IStatusCodeHttpResult(): Microsoft_AspNetCore_Http_Internal.IStatusCodeHttpResult$instance;
    As_IValueHttpResult(): Microsoft_AspNetCore_Http_Internal.IValueHttpResult$instance;
    As_IValueHttpResult_1(): Microsoft_AspNetCore_Http_Internal.IValueHttpResult_1$instance<HttpValidationProblemDetails>;
    As_IEndpointMetadataProvider(): Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance;
}

export interface ValidationProblem$instance extends Microsoft_AspNetCore_Http_Internal.IContentTypeHttpResult$instance, Microsoft_AspNetCore_Http_Internal.IResult$instance, Microsoft_AspNetCore_Http_Internal.IValueHttpResult$instance, Microsoft_AspNetCore_Http_Metadata_Internal.IEndpointMetadataProvider$instance {}

export type ValidationProblem = ValidationProblem$instance & __ValidationProblem$views;


export interface VirtualFileHttpResult$instance {
    readonly contentType: string;
    readonly enableRangeProcessing: boolean;
    readonly entityTag: EntityTagHeaderValue | undefined;
    readonly fileDownloadName: string;
    readonly fileLength: Nullable<System_Internal.Int64>;
    readonly fileName: string;
    readonly lastModified: Nullable<DateTimeOffset>;
    executeAsync(httpContext: HttpContext): Task;
}


export const VirtualFileHttpResult: {
    new(): VirtualFileHttpResult;
};


export interface __VirtualFileHttpResult$views {
    As_IContentTypeHttpResult(): Microsoft_AspNetCore_Http_Internal.IContentTypeHttpResult$instance;
    As_IFileHttpResult(): Microsoft_AspNetCore_Http_Internal.IFileHttpResult$instance;
    As_IResult(): Microsoft_AspNetCore_Http_Internal.IResult$instance;
}

export interface VirtualFileHttpResult$instance extends Microsoft_AspNetCore_Http_Internal.IContentTypeHttpResult$instance, Microsoft_AspNetCore_Http_Internal.IFileHttpResult$instance, Microsoft_AspNetCore_Http_Internal.IResult$instance {}

export type VirtualFileHttpResult = VirtualFileHttpResult$instance & __VirtualFileHttpResult$views;


