// Generated by dotnet-bindgen - Architecture
// Namespace: Microsoft.AspNetCore.WebSockets
// Assembly: Microsoft.AspNetCore.WebSockets

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Import types from other namespaces
import type { WebSocketOptions } from "../../Microsoft.AspNetCore.Builder/internal/index.js";
import * as Microsoft_AspNetCore_Http_Internal from "../../Microsoft.AspNetCore.Http/internal/index.js";
import type { HttpContext, RequestDelegate, WebSocketAcceptContext } from "../../Microsoft.AspNetCore.Http/internal/index.js";
import type { Task } from "@tsonic/dotnet/System.Threading.Tasks/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Action_1, Boolean as ClrBoolean, Int32, Nullable_1, Object as ClrObject, String as ClrString, TimeSpan } from "@tsonic/dotnet/System/internal/index.js";
import type { IServiceCollection } from "@tsonic/microsoft-extensions/Microsoft.Extensions.DependencyInjection/internal/index.js";
import type { ILoggerFactory } from "@tsonic/microsoft-extensions/Microsoft.Extensions.Logging/internal/index.js";
import type { IOptions_1 } from "@tsonic/microsoft-extensions/Microsoft.Extensions.Options/internal/index.js";

export interface ExtendedWebSocketAcceptContext$instance extends WebSocketAcceptContext {
    readonly __tsonic_type_Microsoft_AspNetCore_WebSockets_ExtendedWebSocketAcceptContext: never;

    get KeepAliveInterval(): Nullable_1<TimeSpan>;
    set KeepAliveInterval(value: Nullable_1<TimeSpan> | TimeSpan);
    get ReceiveBufferSize(): Nullable_1<System_Internal.Int32>;
    set ReceiveBufferSize(value: Nullable_1<System_Internal.Int32> | int);
    get SubProtocol(): string | null;
    set SubProtocol(value: string | null);
}


export const ExtendedWebSocketAcceptContext: {
    new(): ExtendedWebSocketAcceptContext;
};


export type ExtendedWebSocketAcceptContext = ExtendedWebSocketAcceptContext$instance;

export interface WebSocketMiddleware$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_WebSockets_WebSocketMiddleware: never;

    Invoke(context: HttpContext): Task;
}


export const WebSocketMiddleware: {
    new(next: RequestDelegate, options: IOptions_1<WebSocketOptions>, loggerFactory: ILoggerFactory): WebSocketMiddleware;
};


export type WebSocketMiddleware = WebSocketMiddleware$instance;

export abstract class WebSocketsDependencyInjectionExtensions$instance {
    static AddWebSockets(services: IServiceCollection, configure: Action_1<WebSocketOptions>): IServiceCollection;
}


export type WebSocketsDependencyInjectionExtensions = WebSocketsDependencyInjectionExtensions$instance;
