// Generated by tsbindgen - Architecture
// Namespace: Microsoft.AspNetCore.Http.Features.Authentication
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.AspNetCore.Http.Features.Authentication/internal/index.js';

// Cross-namespace type imports for constraints
import type { Object as ClrObject } from '@tsonic/dotnet/System.js';
import type { ClaimsPrincipal } from '@tsonic/dotnet/System.Security.Claims.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { HttpAuthenticationFeature as HttpAuthenticationFeature } from './Microsoft.AspNetCore.Http.Features.Authentication/internal/index.js';
export type IHttpAuthenticationFeature = Internal.IHttpAuthenticationFeature;
