// Generated by tsbindgen - Architecture
// Namespace: Microsoft.AspNetCore.Components.Web.HtmlRendering
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.AspNetCore.Components.Web.HtmlRendering/internal/index.js';

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Cross-namespace type imports for constraints
import type { TextWriter } from '@tsonic/dotnet/System.IO.js';
import type { String as ClrString, ValueType, Void } from '@tsonic/dotnet/System.js';
import type { Task } from '@tsonic/dotnet/System.Threading.Tasks.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { HtmlRootComponent as HtmlRootComponent } from './Microsoft.AspNetCore.Components.Web.HtmlRendering/internal/index.js';
