// Generated by tsbindgen - Architecture
// Namespace: Microsoft.AspNetCore.Diagnostics.HealthChecks
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.AspNetCore.Diagnostics.HealthChecks/internal/index.js';

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Cross-namespace type imports for constraints
import type { HttpContext, RequestDelegate } from './Microsoft.AspNetCore.Http/internal/index.js';
import type { IDictionary } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { Boolean as ClrBoolean, Func, Int32, Object as ClrObject } from '@tsonic/dotnet/System.js';
import type { Task } from '@tsonic/dotnet/System.Threading.Tasks.js';
import type { HealthCheckRegistration, HealthCheckService, HealthReport, HealthStatus } from '@tsonic/microsoft-extensions/Microsoft.Extensions.Diagnostics.HealthChecks.js';
import type { IOptions } from '@tsonic/microsoft-extensions/Microsoft.Extensions.Options.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { HealthCheckMiddleware as HealthCheckMiddleware } from './Microsoft.AspNetCore.Diagnostics.HealthChecks/internal/index.js';
export { HealthCheckOptions as HealthCheckOptions } from './Microsoft.AspNetCore.Diagnostics.HealthChecks/internal/index.js';
