// Generated by tsbindgen - Architecture
// Namespace: Microsoft.AspNetCore.Hosting.StaticWebAssets
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.AspNetCore.Hosting.StaticWebAssets/internal/index.js';

// Cross-namespace type imports for constraints
import type { IWebHostEnvironment } from './Microsoft.AspNetCore.Hosting/internal/index.js';
import type { Object as ClrObject, Void } from '@tsonic/dotnet/System.js';
import type { IConfiguration } from '@tsonic/microsoft-extensions/Microsoft.Extensions.Configuration.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { StaticWebAssetsLoader as StaticWebAssetsLoader } from './Microsoft.AspNetCore.Hosting.StaticWebAssets/internal/index.js';
