// Generated by tsbindgen - Architecture
// Namespace: Microsoft.AspNetCore.Components.Authorization
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.AspNetCore.Components.Authorization/internal/index.js';

// Cross-namespace type imports for constraints
import type { IAuthorizeData } from './Microsoft.AspNetCore.Authorization/internal/index.js';
import type { RenderTreeBuilder } from './Microsoft.AspNetCore.Components.Rendering/internal/index.js';
import type { ComponentBase, EventCallbackWorkItem, IComponent, IComponentRenderMode, IHandleAfterRender, IHandleEvent, ParameterView, RendererInfo, RenderFragment, RenderFragment_1, RenderHandle, ResourceAssetCollection, RouteData, RouteView } from './Microsoft.AspNetCore.Components/internal/index.js';
import type { IList } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { Action, AsyncCallback, Boolean as ClrBoolean, Exception, Func, IAsyncResult, ICloneable, IDisposable, IntPtr, MulticastDelegate, Object as ClrObject, String as ClrString, Type, ValueType, Void } from '@tsonic/dotnet/System.js';
import type { ISerializable } from '@tsonic/dotnet/System.Runtime.Serialization.js';
import type { Claim, ClaimsPrincipal } from '@tsonic/dotnet/System.Security.Claims.js';
import type { Task } from '@tsonic/dotnet/System.Threading.Tasks.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { AuthenticationState as AuthenticationState } from './Microsoft.AspNetCore.Components.Authorization/internal/index.js';
export { AuthenticationStateData as AuthenticationStateData } from './Microsoft.AspNetCore.Components.Authorization/internal/index.js';
export { AuthenticationStateProvider as AuthenticationStateProvider } from './Microsoft.AspNetCore.Components.Authorization/internal/index.js';
export type AuthenticationStateChangedHandler = Internal.AuthenticationStateChangedHandler;
export { AuthorizeRouteView as AuthorizeRouteView } from './Microsoft.AspNetCore.Components.Authorization/internal/index.js';
export { AuthorizeView as AuthorizeView } from './Microsoft.AspNetCore.Components.Authorization/internal/index.js';
export { AuthorizeViewCore as AuthorizeViewCore } from './Microsoft.AspNetCore.Components.Authorization/internal/index.js';
export { ClaimData as ClaimData } from './Microsoft.AspNetCore.Components.Authorization/internal/index.js';
export type IHostEnvironmentAuthenticationStateProvider = Internal.IHostEnvironmentAuthenticationStateProvider;
export { CascadingAuthenticationState as CascadingAuthenticationState } from './Microsoft.AspNetCore.Components.Authorization/internal/index.js';
