// Generated by tsbindgen - Architecture
// Namespace: Microsoft.AspNetCore.SignalR
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.AspNetCore.SignalR/internal/index.js';

// Cross-namespace type imports for constraints
import type { ConnectionContext, ConnectionHandler, IConnectionBuilder } from './Microsoft.AspNetCore.Connections/internal/index.js';
import type { IFeatureCollection } from './Microsoft.AspNetCore.Http.Features/internal/index.js';
import type { HttpContext } from './Microsoft.AspNetCore.Http/internal/index.js';
import type { CompletionMessage, HubMessage, IHubProtocol } from './Microsoft.AspNetCore.SignalR.Protocol/internal/index.js';
import type { IDictionary, IEnumerable, IEnumerator as IEnumerator__System_Collections_Generic, IList, IReadOnlyList } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { IEnumerator } from '@tsonic/dotnet/System.Collections.js';
import type { Attribute, Boolean as ClrBoolean, Byte, Exception, Func, IDisposable, Int32, Int64, IServiceProvider, Nullable, Object as ClrObject, ReadOnlyMemory, ReadOnlySpan, String as ClrString, TimeSpan, Type, ValueType, Void } from '@tsonic/dotnet/System.js';
import type { MethodInfo } from '@tsonic/dotnet/System.Reflection.js';
import type { ISerializable, SerializationInfo, StreamingContext } from '@tsonic/dotnet/System.Runtime.Serialization.js';
import type { ClaimsPrincipal } from '@tsonic/dotnet/System.Security.Claims.js';
import type { JsonSerializerOptions } from '@tsonic/dotnet/System.Text.Json.js';
import type { CancellationToken } from '@tsonic/dotnet/System.Threading.js';
import type { Task, ValueTask } from '@tsonic/dotnet/System.Threading.Tasks.js';
import type { IServiceCollection, IServiceScopeFactory } from '@tsonic/microsoft-extensions/Microsoft.Extensions.DependencyInjection.js';
import type { ILogger, ILoggerFactory } from '@tsonic/microsoft-extensions/Microsoft.Extensions.Logging.js';
import type { IConfigureOptions, IOptions } from '@tsonic/microsoft-extensions/Microsoft.Extensions.Options.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { GetHttpContextExtensions$instance as GetHttpContextExtensions } from './Microsoft.AspNetCore.SignalR/internal/index.js';
export { HubException as HubException } from './Microsoft.AspNetCore.SignalR/internal/index.js';
export type IInvocationBinder = Internal.IInvocationBinder;
export type ISignalRBuilder = Internal.ISignalRBuilder;
export { ClientProxyExtensions$instance as ClientProxyExtensions } from './Microsoft.AspNetCore.SignalR/internal/index.js';
export { DefaultHubLifetimeManager_1 as DefaultHubLifetimeManager } from './Microsoft.AspNetCore.SignalR/internal/index.js';
export { DefaultUserIdProvider as DefaultUserIdProvider } from './Microsoft.AspNetCore.SignalR/internal/index.js';
export { DynamicHub as DynamicHub } from './Microsoft.AspNetCore.SignalR/internal/index.js';
export { DynamicHubClients as DynamicHubClients } from './Microsoft.AspNetCore.SignalR/internal/index.js';
export { HubCallerContext as HubCallerContext } from './Microsoft.AspNetCore.SignalR/internal/index.js';
export { HubClientsExtensions$instance as HubClientsExtensions } from './Microsoft.AspNetCore.SignalR/internal/index.js';
export { HubConnectionContext as HubConnectionContext } from './Microsoft.AspNetCore.SignalR/internal/index.js';
export { HubConnectionContextOptions as HubConnectionContextOptions } from './Microsoft.AspNetCore.SignalR/internal/index.js';
export { HubConnectionHandler_1 as HubConnectionHandler } from './Microsoft.AspNetCore.SignalR/internal/index.js';
export { HubConnectionStore as HubConnectionStore } from './Microsoft.AspNetCore.SignalR/internal/index.js';
export { HubConnectionStore_Enumerator as HubConnectionStore_Enumerator } from './Microsoft.AspNetCore.SignalR/internal/index.js';
export { HubInvocationContext as HubInvocationContext } from './Microsoft.AspNetCore.SignalR/internal/index.js';
export { HubLifetimeContext as HubLifetimeContext } from './Microsoft.AspNetCore.SignalR/internal/index.js';
export { HubLifetimeManager_1 as HubLifetimeManager } from './Microsoft.AspNetCore.SignalR/internal/index.js';
export { HubMetadata as HubMetadata } from './Microsoft.AspNetCore.SignalR/internal/index.js';
export { HubMethodNameAttribute as HubMethodNameAttribute } from './Microsoft.AspNetCore.SignalR/internal/index.js';
export { HubOptionsExtensions$instance as HubOptionsExtensions } from './Microsoft.AspNetCore.SignalR/internal/index.js';
export type IClientProxy = Internal.IClientProxy;
export type IGroupManager = Internal.IGroupManager;
export type IHubActivator<THub extends Internal.Hub> = Internal.IHubActivator_1<THub>;
export type IHubFilter = Internal.IHubFilter;
export type IHubProtocolResolver = Internal.IHubProtocolResolver;
export type ISignalRServerBuilder = Internal.ISignalRServerBuilder;
export type ISingleClientProxy = Internal.ISingleClientProxy;
export type IUserIdProvider = Internal.IUserIdProvider;
export { SerializedHubMessage as SerializedHubMessage } from './Microsoft.AspNetCore.SignalR/internal/index.js';
export { SerializedMessage as SerializedMessage } from './Microsoft.AspNetCore.SignalR/internal/index.js';
export { SignalRConnectionBuilderExtensions$instance as SignalRConnectionBuilderExtensions } from './Microsoft.AspNetCore.SignalR/internal/index.js';
export { JsonHubProtocolOptions as JsonHubProtocolOptions } from './Microsoft.AspNetCore.SignalR/internal/index.js';

// Multi-arity family value exports (arity-0 constructors/static namespaces)
export const Hub: typeof Internal.Hub;
export const HubOptions: typeof Internal.HubOptions;
export const HubOptionsSetup: typeof Internal.HubOptionsSetup;

// Multi-arity family sentinel (detects unspecified type parameters)
declare const __unspecified: unique symbol;
export type __ = typeof __unspecified;

export type Hub<
  T1 = __,
> =
  [T1] extends [__] ? Internal.Hub :
  Internal.Hub_1<T1>;

export type HubOptions<
  T1 = __,
> =
  [T1] extends [__] ? Internal.HubOptions :
  [T1] extends [Internal.Hub] ? Internal.HubOptions_1<T1> : never;

export type HubOptionsSetup<
  T1 = __,
> =
  [T1] extends [__] ? Internal.HubOptionsSetup :
  [T1] extends [Internal.Hub] ? Internal.HubOptionsSetup_1<T1> : never;

export type IHubCallerClients<
  T1 = __,
> =
  [T1] extends [__] ? Internal.IHubCallerClients :
  Internal.IHubCallerClients_1<T1>;

export type IHubClients<
  T1 = __,
> =
  [T1] extends [__] ? Internal.IHubClients :
  Internal.IHubClients_1<T1>;

export type IHubContext<
  T1 = __,
  T2 = __,
> =
  [T1] extends [__] ? Internal.IHubContext :
  [T2] extends [__] ? [T1] extends [Internal.Hub] ? Internal.IHubContext_1<T1> : never :
  [T1] extends [Internal.Hub_1<T>] ? Internal.IHubContext_2<T1, T2> : never;

// Extension methods (C# using semantics)
export type { ExtensionMethods_Microsoft_AspNetCore_SignalR as ExtensionMethods } from './__internal/extensions/index.js';

