// Generated by dotnet-bindgen - Architecture
// Namespace: Microsoft.AspNetCore.Http.HttpResults
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.AspNetCore.Http.HttpResults/internal/index.js';

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Cross-namespace type imports for constraints
import type { AuthenticationProperties } from './Microsoft.AspNetCore.Authentication/internal/index.js';
import type { EndpointBuilder } from './Microsoft.AspNetCore.Builder/internal/index.js';
import type { IComponent } from './Microsoft.AspNetCore.Components/internal/index.js';
import type { IEndpointMetadataProvider } from './Microsoft.AspNetCore.Http.Metadata/internal/index.js';
import type { HttpContext, HttpValidationProblemDetails, IContentTypeHttpResult, IFileHttpResult, INestedHttpResult, IResult, IStatusCodeHttpResult, IValueHttpResult, IValueHttpResult_1 } from './Microsoft.AspNetCore.Http/internal/index.js';
import type { ProblemDetails } from './Microsoft.AspNetCore.Mvc/internal/index.js';
import type { RouteValueDictionary } from './Microsoft.AspNetCore.Routing/internal/index.js';
import type { EntityTagHeaderValue } from './Microsoft.Net.Http.Headers/internal/index.js';
import type { IReadOnlyDictionary, IReadOnlyList } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { Stream } from '@tsonic/dotnet/System.IO.js';
import type { Boolean as ClrBoolean, Byte, DateTimeOffset, Int32, Int64, Nullable, Object as ClrObject, ReadOnlyMemory, String as ClrString, Type, Void } from '@tsonic/dotnet/System.js';
import type { MethodInfo } from '@tsonic/dotnet/System.Reflection.js';
import type { ClaimsPrincipal } from '@tsonic/dotnet/System.Security.Claims.js';
import type { JsonSerializerOptions } from '@tsonic/dotnet/System.Text.Json.js';
import type { Task } from '@tsonic/dotnet/System.Threading.Tasks.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { EmptyHttpResult as EmptyHttpResult } from './Microsoft.AspNetCore.Http.HttpResults/internal/index.js';
export { ChallengeHttpResult as ChallengeHttpResult } from './Microsoft.AspNetCore.Http.HttpResults/internal/index.js';
export { ContentHttpResult as ContentHttpResult } from './Microsoft.AspNetCore.Http.HttpResults/internal/index.js';
export { FileContentHttpResult as FileContentHttpResult } from './Microsoft.AspNetCore.Http.HttpResults/internal/index.js';
export { FileStreamHttpResult as FileStreamHttpResult } from './Microsoft.AspNetCore.Http.HttpResults/internal/index.js';
export { ForbidHttpResult as ForbidHttpResult } from './Microsoft.AspNetCore.Http.HttpResults/internal/index.js';
export { JsonHttpResult_1 as JsonHttpResult } from './Microsoft.AspNetCore.Http.HttpResults/internal/index.js';
export { NoContent as NoContent } from './Microsoft.AspNetCore.Http.HttpResults/internal/index.js';
export { PhysicalFileHttpResult as PhysicalFileHttpResult } from './Microsoft.AspNetCore.Http.HttpResults/internal/index.js';
export { ProblemHttpResult as ProblemHttpResult } from './Microsoft.AspNetCore.Http.HttpResults/internal/index.js';
export { PushStreamHttpResult as PushStreamHttpResult } from './Microsoft.AspNetCore.Http.HttpResults/internal/index.js';
export { RedirectHttpResult as RedirectHttpResult } from './Microsoft.AspNetCore.Http.HttpResults/internal/index.js';
export { RedirectToRouteHttpResult as RedirectToRouteHttpResult } from './Microsoft.AspNetCore.Http.HttpResults/internal/index.js';
export { ServerSentEventsResult_1 as ServerSentEventsResult } from './Microsoft.AspNetCore.Http.HttpResults/internal/index.js';
export { SignInHttpResult as SignInHttpResult } from './Microsoft.AspNetCore.Http.HttpResults/internal/index.js';
export { SignOutHttpResult as SignOutHttpResult } from './Microsoft.AspNetCore.Http.HttpResults/internal/index.js';
export { StatusCodeHttpResult as StatusCodeHttpResult } from './Microsoft.AspNetCore.Http.HttpResults/internal/index.js';
export { UnauthorizedHttpResult as UnauthorizedHttpResult } from './Microsoft.AspNetCore.Http.HttpResults/internal/index.js';
export { Utf8ContentHttpResult as Utf8ContentHttpResult } from './Microsoft.AspNetCore.Http.HttpResults/internal/index.js';
export { ValidationProblem as ValidationProblem } from './Microsoft.AspNetCore.Http.HttpResults/internal/index.js';
export { VirtualFileHttpResult as VirtualFileHttpResult } from './Microsoft.AspNetCore.Http.HttpResults/internal/index.js';

// Multi-arity family value exports (arity-0 constructors/static namespaces)
export const Accepted: typeof Internal.Accepted;
export const AcceptedAtRoute: typeof Internal.AcceptedAtRoute;
export const BadRequest: typeof Internal.BadRequest;
export const Conflict: typeof Internal.Conflict;
export const Created: typeof Internal.Created;
export const CreatedAtRoute: typeof Internal.CreatedAtRoute;
export const InternalServerError: typeof Internal.InternalServerError;
export const NotFound: typeof Internal.NotFound;
export const Ok: typeof Internal.Ok;
export const RazorComponentResult: typeof Internal.RazorComponentResult;
export const UnprocessableEntity: typeof Internal.UnprocessableEntity;

// Multi-arity family sentinel (detects unspecified type parameters)
declare const __unspecified: unique symbol;
export type __ = typeof __unspecified;

export type Accepted<
  T1 extends unknown | __ = __,
> =
  [T1] extends [__] ? Internal.Accepted :
  [T1] extends [unknown] ? Internal.Accepted_1<T1> : never;

export type AcceptedAtRoute<
  T1 extends unknown | __ = __,
> =
  [T1] extends [__] ? Internal.AcceptedAtRoute :
  [T1] extends [unknown] ? Internal.AcceptedAtRoute_1<T1> : never;

export type BadRequest<
  T1 extends unknown | __ = __,
> =
  [T1] extends [__] ? Internal.BadRequest :
  [T1] extends [unknown] ? Internal.BadRequest_1<T1> : never;

export type Conflict<
  T1 extends unknown | __ = __,
> =
  [T1] extends [__] ? Internal.Conflict :
  [T1] extends [unknown] ? Internal.Conflict_1<T1> : never;

export type Created<
  T1 extends unknown | __ = __,
> =
  [T1] extends [__] ? Internal.Created :
  [T1] extends [unknown] ? Internal.Created_1<T1> : never;

export type CreatedAtRoute<
  T1 extends unknown | __ = __,
> =
  [T1] extends [__] ? Internal.CreatedAtRoute :
  [T1] extends [unknown] ? Internal.CreatedAtRoute_1<T1> : never;

export type InternalServerError<
  T1 extends unknown | __ = __,
> =
  [T1] extends [__] ? Internal.InternalServerError :
  [T1] extends [unknown] ? Internal.InternalServerError_1<T1> : never;

export type NotFound<
  T1 extends unknown | __ = __,
> =
  [T1] extends [__] ? Internal.NotFound :
  [T1] extends [unknown] ? Internal.NotFound_1<T1> : never;

export type Ok<
  T1 extends unknown | __ = __,
> =
  [T1] extends [__] ? Internal.Ok :
  [T1] extends [unknown] ? Internal.Ok_1<T1> : never;

export type RazorComponentResult<
  T1 extends unknown & IComponent | __ = __,
> =
  [T1] extends [__] ? Internal.RazorComponentResult :
  [T1] extends [unknown & IComponent] ? Internal.RazorComponentResult_1<T1> : never;

export type Results<
  T1 extends unknown & IResult | __ = __,
  T2 extends unknown & IResult | __ = __,
  T3 extends unknown & IResult | __ = __,
  T4 extends unknown & IResult | __ = __,
  T5 extends unknown & IResult | __ = __,
  T6 extends unknown & IResult | __ = __,
> =
  [T3] extends [__] ? [T1] extends [unknown & IResult] ? [T2] extends [unknown & IResult] ? Internal.Results_2<T1, T2> : never : never :
  [T4] extends [__] ? [T1] extends [unknown & IResult] ? [T2] extends [unknown & IResult] ? [T3] extends [unknown & IResult] ? Internal.Results_3<T1, T2, T3> : never : never : never :
  [T5] extends [__] ? [T1] extends [unknown & IResult] ? [T2] extends [unknown & IResult] ? [T3] extends [unknown & IResult] ? [T4] extends [unknown & IResult] ? Internal.Results_4<T1, T2, T3, T4> : never : never : never : never :
  [T6] extends [__] ? [T1] extends [unknown & IResult] ? [T2] extends [unknown & IResult] ? [T3] extends [unknown & IResult] ? [T4] extends [unknown & IResult] ? [T5] extends [unknown & IResult] ? Internal.Results_5<T1, T2, T3, T4, T5> : never : never : never : never : never :
  [T1] extends [unknown & IResult] ? [T2] extends [unknown & IResult] ? [T3] extends [unknown & IResult] ? [T4] extends [unknown & IResult] ? [T5] extends [unknown & IResult] ? [T6] extends [unknown & IResult] ? Internal.Results_6<T1, T2, T3, T4, T5, T6> : never : never : never : never : never : never;

export type UnprocessableEntity<
  T1 extends unknown | __ = __,
> =
  [T1] extends [__] ? Internal.UnprocessableEntity :
  [T1] extends [unknown] ? Internal.UnprocessableEntity_1<T1> : never;

