// Generated by tsbindgen - Architecture
// Namespace: Microsoft.AspNetCore.Mvc.Razor
// Module Stub - Do Not Execute

throw new Error(
  'Cannot import CLR namespace Microsoft.AspNetCore.Mvc.Razor in JavaScript runtime. ' +
  'This module provides TypeScript type definitions only. ' +
  'Actual implementation requires .NET runtime via Tsonic compiler.'
);
