// Generated by tsbindgen - Architecture
// Namespace: Microsoft.AspNetCore.SignalR.Protocol
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.AspNetCore.SignalR.Protocol/internal/index.js';

// Cross-namespace type imports for constraints
import type { TransferFormat } from './Microsoft.AspNetCore.Connections/internal/index.js';
import type { IInvocationBinder, JsonHubProtocolOptions } from './Microsoft.AspNetCore.SignalR/internal/index.js';
import type { IBufferWriter, ReadOnlySequence } from '@tsonic/dotnet/System.Buffers.js';
import type { IDictionary } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { Boolean as ClrBoolean, Byte, Int32, Int64, Object as ClrObject, ReadOnlyMemory, ReadOnlySpan, String as ClrString, Void } from '@tsonic/dotnet/System.js';
import type { ExceptionDispatchInfo } from '@tsonic/dotnet/System.Runtime.ExceptionServices.js';
import type { IOptions } from '@tsonic/microsoft-extensions/Microsoft.Extensions.Options.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { AckMessage as AckMessage } from './Microsoft.AspNetCore.SignalR.Protocol/internal/index.js';
export { CancelInvocationMessage as CancelInvocationMessage } from './Microsoft.AspNetCore.SignalR.Protocol/internal/index.js';
export { CloseMessage as CloseMessage } from './Microsoft.AspNetCore.SignalR.Protocol/internal/index.js';
export { CompletionMessage as CompletionMessage } from './Microsoft.AspNetCore.SignalR.Protocol/internal/index.js';
export { HandshakeProtocol$instance as HandshakeProtocol } from './Microsoft.AspNetCore.SignalR.Protocol/internal/index.js';
export { HandshakeRequestMessage as HandshakeRequestMessage } from './Microsoft.AspNetCore.SignalR.Protocol/internal/index.js';
export { HandshakeResponseMessage as HandshakeResponseMessage } from './Microsoft.AspNetCore.SignalR.Protocol/internal/index.js';
export { HubInvocationMessage as HubInvocationMessage } from './Microsoft.AspNetCore.SignalR.Protocol/internal/index.js';
export { HubMessage as HubMessage } from './Microsoft.AspNetCore.SignalR.Protocol/internal/index.js';
export { HubMethodInvocationMessage as HubMethodInvocationMessage } from './Microsoft.AspNetCore.SignalR.Protocol/internal/index.js';
export { InvocationMessage as InvocationMessage } from './Microsoft.AspNetCore.SignalR.Protocol/internal/index.js';
export { StreamInvocationMessage as StreamInvocationMessage } from './Microsoft.AspNetCore.SignalR.Protocol/internal/index.js';
export { HubProtocolConstants$instance as HubProtocolConstants } from './Microsoft.AspNetCore.SignalR.Protocol/internal/index.js';
export { HubProtocolExtensions$instance as HubProtocolExtensions } from './Microsoft.AspNetCore.SignalR.Protocol/internal/index.js';
export type IHubProtocol = Internal.IHubProtocol;
export { InvocationBindingFailureMessage as InvocationBindingFailureMessage } from './Microsoft.AspNetCore.SignalR.Protocol/internal/index.js';
export { PingMessage as PingMessage } from './Microsoft.AspNetCore.SignalR.Protocol/internal/index.js';
export { RawResult as RawResult } from './Microsoft.AspNetCore.SignalR.Protocol/internal/index.js';
export { SequenceMessage as SequenceMessage } from './Microsoft.AspNetCore.SignalR.Protocol/internal/index.js';
export { StreamBindingFailureMessage as StreamBindingFailureMessage } from './Microsoft.AspNetCore.SignalR.Protocol/internal/index.js';
export { StreamItemMessage as StreamItemMessage } from './Microsoft.AspNetCore.SignalR.Protocol/internal/index.js';
export { JsonHubProtocol as JsonHubProtocol } from './Microsoft.AspNetCore.SignalR.Protocol/internal/index.js';
// Extension methods (C# using semantics)
export type { ExtensionMethods_Microsoft_AspNetCore_SignalR_Protocol as ExtensionMethods } from './__internal/extensions/index.js';

