// Generated by tsbindgen - Architecture
// Namespace: Microsoft.AspNetCore.Authentication.OAuth.Claims
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.AspNetCore.Authentication.OAuth.Claims/internal/index.js';

// Cross-namespace type imports for constraints
import type { IEnumerable as IEnumerable__System_Collections_Generic, IEnumerator } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { IEnumerable } from '@tsonic/dotnet/System.Collections.js';
import type { Func, Object as ClrObject, String as ClrString, Void } from '@tsonic/dotnet/System.js';
import type { ClaimsIdentity } from '@tsonic/dotnet/System.Security.Claims.js';
import type { JsonElement } from '@tsonic/dotnet/System.Text.Json.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { ClaimAction as ClaimAction } from './Microsoft.AspNetCore.Authentication.OAuth.Claims/internal/index.js';
export { ClaimActionCollection as ClaimActionCollection } from './Microsoft.AspNetCore.Authentication.OAuth.Claims/internal/index.js';
export { CustomJsonClaimAction as CustomJsonClaimAction } from './Microsoft.AspNetCore.Authentication.OAuth.Claims/internal/index.js';
export { DeleteClaimAction as DeleteClaimAction } from './Microsoft.AspNetCore.Authentication.OAuth.Claims/internal/index.js';
export { JsonKeyClaimAction as JsonKeyClaimAction } from './Microsoft.AspNetCore.Authentication.OAuth.Claims/internal/index.js';
export { JsonSubKeyClaimAction as JsonSubKeyClaimAction } from './Microsoft.AspNetCore.Authentication.OAuth.Claims/internal/index.js';
export { MapAllClaimsAction as MapAllClaimsAction } from './Microsoft.AspNetCore.Authentication.OAuth.Claims/internal/index.js';
