// Generated by tsbindgen - Architecture
// Namespace: Microsoft.AspNetCore.Components.RenderTree
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.AspNetCore.Components.RenderTree/internal/index.js';

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Cross-namespace type imports for constraints
import type { ComponentState } from './Microsoft.AspNetCore.Components.Rendering/internal/index.js';
import type { JSComponentInterop } from './Microsoft.AspNetCore.Components.Web.Infrastructure/internal/index.js';
import type { Dispatcher, ElementReference, ElementReferenceContext, IComponent, IComponentActivator, IComponentRenderMode, ParameterView, RendererInfo, ResourceAssetCollection } from './Microsoft.AspNetCore.Components/internal/index.js';
import type { IEnumerable as IEnumerable__System_Collections_Generic } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { IEnumerable } from '@tsonic/dotnet/System.Collections.js';
import type { Action, Boolean as ClrBoolean, Byte, Enum, EventArgs, Exception, IAsyncDisposable, IComparable, IConvertible, IDisposable, IFormattable, Int16, Int32, IServiceProvider, ISpanFormattable, Nullable, Object as ClrObject, String as ClrString, Type, UInt64, UnhandledExceptionEventHandler, ValueType, Void } from '@tsonic/dotnet/System.js';
import type { JsonSerializerOptions } from '@tsonic/dotnet/System.Text.Json.js';
import type { Task, ValueTask } from '@tsonic/dotnet/System.Threading.Tasks.js';
import type { ILoggerFactory } from '@tsonic/microsoft-extensions/Microsoft.Extensions.Logging.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { ArrayBuilderSegment_1 as ArrayBuilderSegment } from './Microsoft.AspNetCore.Components.RenderTree/internal/index.js';
export { ArrayRange_1 as ArrayRange } from './Microsoft.AspNetCore.Components.RenderTree/internal/index.js';
export { ComponentFrameFlags as ComponentFrameFlags } from './Microsoft.AspNetCore.Components.RenderTree/internal/index.js';
export { EventFieldInfo as EventFieldInfo } from './Microsoft.AspNetCore.Components.RenderTree/internal/index.js';
export { NamedEventChange as NamedEventChange } from './Microsoft.AspNetCore.Components.RenderTree/internal/index.js';
export { NamedEventChangeType as NamedEventChangeType } from './Microsoft.AspNetCore.Components.RenderTree/internal/index.js';
export { RenderBatch as RenderBatch } from './Microsoft.AspNetCore.Components.RenderTree/internal/index.js';
export { Renderer as Renderer } from './Microsoft.AspNetCore.Components.RenderTree/internal/index.js';
export { RenderTreeDiff as RenderTreeDiff } from './Microsoft.AspNetCore.Components.RenderTree/internal/index.js';
export { RenderTreeEdit as RenderTreeEdit } from './Microsoft.AspNetCore.Components.RenderTree/internal/index.js';
export { RenderTreeEditType as RenderTreeEditType } from './Microsoft.AspNetCore.Components.RenderTree/internal/index.js';
export { RenderTreeFrame as RenderTreeFrame } from './Microsoft.AspNetCore.Components.RenderTree/internal/index.js';
export { RenderTreeFrameType as RenderTreeFrameType } from './Microsoft.AspNetCore.Components.RenderTree/internal/index.js';
export { WebEventDescriptor as WebEventDescriptor } from './Microsoft.AspNetCore.Components.RenderTree/internal/index.js';
export { WebRenderer as WebRenderer } from './Microsoft.AspNetCore.Components.RenderTree/internal/index.js';
