// Generated by tsbindgen - Architecture
// Namespace: Microsoft.AspNetCore.Server.Kestrel.Transport.NamedPipes
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.AspNetCore.Server.Kestrel.Transport.NamedPipes/internal/index.js';

// Cross-namespace type imports for constraints
import type { NamedPipeEndPoint } from './Microsoft.AspNetCore.Connections/internal/index.js';
import type { NamedPipeServerStream, PipeOptions, PipeSecurity } from '@tsonic/dotnet/System.IO.Pipes.js';
import type { Boolean as ClrBoolean, Func, Int32, Int64, Nullable, Object as ClrObject } from '@tsonic/dotnet/System.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { CreateNamedPipeServerStreamContext as CreateNamedPipeServerStreamContext } from './Microsoft.AspNetCore.Server.Kestrel.Transport.NamedPipes/internal/index.js';
export { NamedPipeTransportOptions as NamedPipeTransportOptions } from './Microsoft.AspNetCore.Server.Kestrel.Transport.NamedPipes/internal/index.js';
