// Generated by tsbindgen - Architecture
// Namespace: Microsoft.AspNetCore.Mvc.ModelBinding.Binders
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.AspNetCore.Mvc.ModelBinding.Binders/internal/index.js';

// Cross-namespace type imports for constraints
import type { IInputFormatter } from './Microsoft.AspNetCore.Mvc.Formatters/internal/index.js';
import type { IHttpRequestStreamReaderFactory } from './Microsoft.AspNetCore.Mvc.Infrastructure/internal/index.js';
import type { ICollectionModelBinder, IModelBinder, IModelBinderProvider, ModelBinderProviderContext, ModelBindingContext, ModelMetadata } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
import type { MvcOptions } from './Microsoft.AspNetCore.Mvc/internal/index.js';
import type { IDictionary, IList, KeyValuePair } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { DateTimeStyles, NumberStyles } from '@tsonic/dotnet/System.Globalization.js';
import type { Boolean as ClrBoolean, Object as ClrObject, Type } from '@tsonic/dotnet/System.js';
import type { Task } from '@tsonic/dotnet/System.Threading.Tasks.js';
import type { ILoggerFactory } from '@tsonic/microsoft-extensions/Microsoft.Extensions.Logging.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { ArrayModelBinder_1 as ArrayModelBinder } from './Microsoft.AspNetCore.Mvc.ModelBinding.Binders/internal/index.js';
export { ArrayModelBinderProvider as ArrayModelBinderProvider } from './Microsoft.AspNetCore.Mvc.ModelBinding.Binders/internal/index.js';
export { BinderTypeModelBinder as BinderTypeModelBinder } from './Microsoft.AspNetCore.Mvc.ModelBinding.Binders/internal/index.js';
export { BinderTypeModelBinderProvider as BinderTypeModelBinderProvider } from './Microsoft.AspNetCore.Mvc.ModelBinding.Binders/internal/index.js';
export { BodyModelBinder as BodyModelBinder } from './Microsoft.AspNetCore.Mvc.ModelBinding.Binders/internal/index.js';
export { BodyModelBinderProvider as BodyModelBinderProvider } from './Microsoft.AspNetCore.Mvc.ModelBinding.Binders/internal/index.js';
export { ByteArrayModelBinder as ByteArrayModelBinder } from './Microsoft.AspNetCore.Mvc.ModelBinding.Binders/internal/index.js';
export { ByteArrayModelBinderProvider as ByteArrayModelBinderProvider } from './Microsoft.AspNetCore.Mvc.ModelBinding.Binders/internal/index.js';
export { CancellationTokenModelBinder as CancellationTokenModelBinder } from './Microsoft.AspNetCore.Mvc.ModelBinding.Binders/internal/index.js';
export { CancellationTokenModelBinderProvider as CancellationTokenModelBinderProvider } from './Microsoft.AspNetCore.Mvc.ModelBinding.Binders/internal/index.js';
export { CollectionModelBinder_1 as CollectionModelBinder } from './Microsoft.AspNetCore.Mvc.ModelBinding.Binders/internal/index.js';
export { CollectionModelBinderProvider as CollectionModelBinderProvider } from './Microsoft.AspNetCore.Mvc.ModelBinding.Binders/internal/index.js';
export { ComplexObjectModelBinder as ComplexObjectModelBinder } from './Microsoft.AspNetCore.Mvc.ModelBinding.Binders/internal/index.js';
export { ComplexObjectModelBinderProvider as ComplexObjectModelBinderProvider } from './Microsoft.AspNetCore.Mvc.ModelBinding.Binders/internal/index.js';
export { ComplexTypeModelBinder as ComplexTypeModelBinder } from './Microsoft.AspNetCore.Mvc.ModelBinding.Binders/internal/index.js';
export { ComplexTypeModelBinderProvider as ComplexTypeModelBinderProvider } from './Microsoft.AspNetCore.Mvc.ModelBinding.Binders/internal/index.js';
export { DateTimeModelBinder as DateTimeModelBinder } from './Microsoft.AspNetCore.Mvc.ModelBinding.Binders/internal/index.js';
export { DateTimeModelBinderProvider as DateTimeModelBinderProvider } from './Microsoft.AspNetCore.Mvc.ModelBinding.Binders/internal/index.js';
export { DecimalModelBinder as DecimalModelBinder } from './Microsoft.AspNetCore.Mvc.ModelBinding.Binders/internal/index.js';
export { DictionaryModelBinder_2 as DictionaryModelBinder } from './Microsoft.AspNetCore.Mvc.ModelBinding.Binders/internal/index.js';
export { DictionaryModelBinderProvider as DictionaryModelBinderProvider } from './Microsoft.AspNetCore.Mvc.ModelBinding.Binders/internal/index.js';
export { DoubleModelBinder as DoubleModelBinder } from './Microsoft.AspNetCore.Mvc.ModelBinding.Binders/internal/index.js';
export { EnumTypeModelBinder as EnumTypeModelBinder } from './Microsoft.AspNetCore.Mvc.ModelBinding.Binders/internal/index.js';
export { EnumTypeModelBinderProvider as EnumTypeModelBinderProvider } from './Microsoft.AspNetCore.Mvc.ModelBinding.Binders/internal/index.js';
export { FloatingPointTypeModelBinderProvider as FloatingPointTypeModelBinderProvider } from './Microsoft.AspNetCore.Mvc.ModelBinding.Binders/internal/index.js';
export { FloatModelBinder as FloatModelBinder } from './Microsoft.AspNetCore.Mvc.ModelBinding.Binders/internal/index.js';
export { FormCollectionModelBinder as FormCollectionModelBinder } from './Microsoft.AspNetCore.Mvc.ModelBinding.Binders/internal/index.js';
export { FormCollectionModelBinderProvider as FormCollectionModelBinderProvider } from './Microsoft.AspNetCore.Mvc.ModelBinding.Binders/internal/index.js';
export { FormFileModelBinder as FormFileModelBinder } from './Microsoft.AspNetCore.Mvc.ModelBinding.Binders/internal/index.js';
export { FormFileModelBinderProvider as FormFileModelBinderProvider } from './Microsoft.AspNetCore.Mvc.ModelBinding.Binders/internal/index.js';
export { HeaderModelBinder as HeaderModelBinder } from './Microsoft.AspNetCore.Mvc.ModelBinding.Binders/internal/index.js';
export { HeaderModelBinderProvider as HeaderModelBinderProvider } from './Microsoft.AspNetCore.Mvc.ModelBinding.Binders/internal/index.js';
export { KeyValuePairModelBinder_2 as KeyValuePairModelBinder } from './Microsoft.AspNetCore.Mvc.ModelBinding.Binders/internal/index.js';
export { KeyValuePairModelBinderProvider as KeyValuePairModelBinderProvider } from './Microsoft.AspNetCore.Mvc.ModelBinding.Binders/internal/index.js';
export { ServicesModelBinder as ServicesModelBinder } from './Microsoft.AspNetCore.Mvc.ModelBinding.Binders/internal/index.js';
export { ServicesModelBinderProvider as ServicesModelBinderProvider } from './Microsoft.AspNetCore.Mvc.ModelBinding.Binders/internal/index.js';
export { SimpleTypeModelBinder as SimpleTypeModelBinder } from './Microsoft.AspNetCore.Mvc.ModelBinding.Binders/internal/index.js';
export { SimpleTypeModelBinderProvider as SimpleTypeModelBinderProvider } from './Microsoft.AspNetCore.Mvc.ModelBinding.Binders/internal/index.js';
export { TryParseModelBinderProvider as TryParseModelBinderProvider } from './Microsoft.AspNetCore.Mvc.ModelBinding.Binders/internal/index.js';
