// Generated by tsbindgen - Architecture
// Namespace: Microsoft.AspNetCore.HostFiltering
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.AspNetCore.HostFiltering/internal/index.js';

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Cross-namespace type imports for constraints
import type { HttpContext, RequestDelegate } from './Microsoft.AspNetCore.Http/internal/index.js';
import type { IList } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { Boolean as ClrBoolean, Object as ClrObject, String as ClrString } from '@tsonic/dotnet/System.js';
import type { Task } from '@tsonic/dotnet/System.Threading.Tasks.js';
import type { ILogger } from '@tsonic/microsoft-extensions/Microsoft.Extensions.Logging.js';
import type { IOptionsMonitor } from '@tsonic/microsoft-extensions/Microsoft.Extensions.Options.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { HostFilteringMiddleware as HostFilteringMiddleware } from './Microsoft.AspNetCore.HostFiltering/internal/index.js';
export { HostFilteringOptions as HostFilteringOptions } from './Microsoft.AspNetCore.HostFiltering/internal/index.js';
