// Generated by tsbindgen - Architecture
// Namespace: Microsoft.AspNetCore.Mvc.Diagnostics
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';

// Cross-namespace type imports for constraints
import type { HttpContext } from './Microsoft.AspNetCore.Http/internal/index.js';
import type { ActionDescriptor } from './Microsoft.AspNetCore.Mvc.Abstractions/internal/index.js';
import type { ActionExecutedContext, ActionExecutingContext, AuthorizationFilterContext, ExceptionContext, IAsyncPageFilter, IFilterMetadata, IPageFilter, PageHandlerExecutedContext, PageHandlerExecutingContext, PageHandlerSelectedContext, ResourceExecutedContext, ResourceExecutingContext, ResultExecutedContext, ResultExecutingContext } from './Microsoft.AspNetCore.Mvc.Filters/internal/index.js';
import type { IRazorPage } from './Microsoft.AspNetCore.Mvc.Razor/internal/index.js';
import type { HandlerMethodDescriptor } from './Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure/internal/index.js';
import type { CompiledPageActionDescriptor } from './Microsoft.AspNetCore.Mvc.RazorPages/internal/index.js';
import type { ViewContext } from './Microsoft.AspNetCore.Mvc.Rendering/internal/index.js';
import type { ViewComponentContext } from './Microsoft.AspNetCore.Mvc.ViewComponents/internal/index.js';
import type { IView } from './Microsoft.AspNetCore.Mvc.ViewEngines/internal/index.js';
import type { ActionContext, ActionResult, IActionResult, IViewComponentResult } from './Microsoft.AspNetCore.Mvc/internal/index.js';
import type { RouteData } from './Microsoft.AspNetCore.Routing/internal/index.js';
import type { IEnumerable as IEnumerable__System_Collections_Generic, IEnumerator as IEnumerator__System_Collections_Generic, IReadOnlyCollection, IReadOnlyDictionary, IReadOnlyList, KeyValuePair } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { IEnumerable, IEnumerator } from '@tsonic/dotnet/System.Collections.js';
import type { Boolean as ClrBoolean, IDisposable, Object as ClrObject, String as ClrString, ValueType, Void } from '@tsonic/dotnet/System.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { EventData as EventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { BeforeActionEventData as BeforeActionEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { AfterActionEventData as AfterActionEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { BeforeAuthorizationFilterOnAuthorizationEventData as BeforeAuthorizationFilterOnAuthorizationEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { AfterAuthorizationFilterOnAuthorizationEventData as AfterAuthorizationFilterOnAuthorizationEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { BeforeResourceFilterOnResourceExecutionEventData as BeforeResourceFilterOnResourceExecutionEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { AfterResourceFilterOnResourceExecutionEventData as AfterResourceFilterOnResourceExecutionEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { BeforeResourceFilterOnResourceExecutingEventData as BeforeResourceFilterOnResourceExecutingEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { AfterResourceFilterOnResourceExecutingEventData as AfterResourceFilterOnResourceExecutingEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { BeforeResourceFilterOnResourceExecutedEventData as BeforeResourceFilterOnResourceExecutedEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { AfterResourceFilterOnResourceExecutedEventData as AfterResourceFilterOnResourceExecutedEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { BeforeExceptionFilterOnException as BeforeExceptionFilterOnException } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { AfterExceptionFilterOnExceptionEventData as AfterExceptionFilterOnExceptionEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { BeforeActionFilterOnActionExecutionEventData as BeforeActionFilterOnActionExecutionEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { AfterActionFilterOnActionExecutionEventData as AfterActionFilterOnActionExecutionEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { BeforeActionFilterOnActionExecutingEventData as BeforeActionFilterOnActionExecutingEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { AfterActionFilterOnActionExecutingEventData as AfterActionFilterOnActionExecutingEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { BeforeActionFilterOnActionExecutedEventData as BeforeActionFilterOnActionExecutedEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { AfterActionFilterOnActionExecutedEventData as AfterActionFilterOnActionExecutedEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { BeforeControllerActionMethodEventData as BeforeControllerActionMethodEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { AfterControllerActionMethodEventData as AfterControllerActionMethodEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { BeforeResultFilterOnResultExecutionEventData as BeforeResultFilterOnResultExecutionEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { AfterResultFilterOnResultExecutionEventData as AfterResultFilterOnResultExecutionEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { BeforeResultFilterOnResultExecutingEventData as BeforeResultFilterOnResultExecutingEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { AfterResultFilterOnResultExecutingEventData as AfterResultFilterOnResultExecutingEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { BeforeResultFilterOnResultExecutedEventData as BeforeResultFilterOnResultExecutedEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { AfterResultFilterOnResultExecutedEventData as AfterResultFilterOnResultExecutedEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { BeforeActionResultEventData as BeforeActionResultEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { AfterActionResultEventData as AfterActionResultEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { EventData_Enumerator as EventData_Enumerator } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { BeforeViewPageEventData as BeforeViewPageEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { AfterViewPageEventData as AfterViewPageEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { BeforeHandlerMethodEventData as BeforeHandlerMethodEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { AfterHandlerMethodEventData as AfterHandlerMethodEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { BeforePageFilterOnPageHandlerExecutionEventData as BeforePageFilterOnPageHandlerExecutionEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { AfterPageFilterOnPageHandlerExecutionEventData as AfterPageFilterOnPageHandlerExecutionEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { BeforePageFilterOnPageHandlerExecutingEventData as BeforePageFilterOnPageHandlerExecutingEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { AfterPageFilterOnPageHandlerExecutingEventData as AfterPageFilterOnPageHandlerExecutingEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { BeforePageFilterOnPageHandlerExecutedEventData as BeforePageFilterOnPageHandlerExecutedEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { AfterPageFilterOnPageHandlerExecutedEventData as AfterPageFilterOnPageHandlerExecutedEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { BeforePageFilterOnPageHandlerSelectionEventData as BeforePageFilterOnPageHandlerSelectionEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { AfterPageFilterOnPageHandlerSelectionEventData as AfterPageFilterOnPageHandlerSelectionEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { BeforePageFilterOnPageHandlerSelectedEventData as BeforePageFilterOnPageHandlerSelectedEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { AfterPageFilterOnPageHandlerSelectedEventData as AfterPageFilterOnPageHandlerSelectedEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { BeforeViewComponentEventData as BeforeViewComponentEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { AfterViewComponentEventData as AfterViewComponentEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { ViewComponentBeforeViewExecuteEventData as ViewComponentBeforeViewExecuteEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { ViewComponentAfterViewExecuteEventData as ViewComponentAfterViewExecuteEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { BeforeViewEventData as BeforeViewEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { AfterViewEventData as AfterViewEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { ViewFoundEventData as ViewFoundEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
export { ViewNotFoundEventData as ViewNotFoundEventData } from './Microsoft.AspNetCore.Mvc.Diagnostics/internal/index.js';
