// Generated by dotnet-bindgen - Architecture
// Namespace: Microsoft.AspNetCore.Hosting.Builder
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.AspNetCore.Hosting.Builder/internal/index.js';

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Cross-namespace type imports for constraints
import type { IApplicationBuilder } from './Microsoft.AspNetCore.Builder/internal/index.js';
import type { IFeatureCollection } from './Microsoft.AspNetCore.Http.Features/internal/index.js';
import type { IServiceProvider, Object as ClrObject } from '@tsonic/dotnet/System.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { ApplicationBuilderFactory as ApplicationBuilderFactory } from './Microsoft.AspNetCore.Hosting.Builder/internal/index.js';
export type IApplicationBuilderFactory = Internal.IApplicationBuilderFactory;
