// Generated by tsbindgen - Architecture
// Namespace: Microsoft.AspNetCore.Http.Features
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.AspNetCore.Http.Features/internal/index.js';

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Cross-namespace type imports for constraints
import type { ConnectionContext } from './Microsoft.AspNetCore.Connections/internal/index.js';
import type { Endpoint, HttpContext, HttpRequest, IFormCollection, IHeaderDictionary, IQueryCollection, IRequestCookieCollection, IResponseCookies, ISession, WebSocketAcceptContext } from './Microsoft.AspNetCore.Http/internal/index.js';
import type { RouteValueDictionary } from './Microsoft.AspNetCore.Routing/internal/index.js';
import type { ICollection, IDictionary, IEnumerable as IEnumerable__System_Collections_Generic, IEnumerator, KeyValuePair } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { IEnumerable } from '@tsonic/dotnet/System.Collections.js';
import type { Activity } from '@tsonic/dotnet/System.Diagnostics.js';
import type { Stream } from '@tsonic/dotnet/System.IO.js';
import type { PipeReader, PipeWriter } from '@tsonic/dotnet/System.IO.Pipelines.js';
import type { Boolean as ClrBoolean, Byte, Enum, Exception, Func, IAsyncDisposable, IComparable, IConvertible, IDisposable, IFormattable, Int32, Int64, IServiceProvider, ISpanFormattable, Nullable, Object as ClrObject, String as ClrString, Type, ValueType, Void } from '@tsonic/dotnet/System.js';
import type { IPAddress } from '@tsonic/dotnet/System.Net.js';
import type { WebSocket } from '@tsonic/dotnet/System.Net.WebSockets.js';
import type { X509Certificate2 } from '@tsonic/dotnet/System.Security.Cryptography.X509Certificates.js';
import type { StringBuilder } from '@tsonic/dotnet/System.Text.js';
import type { CancellationToken } from '@tsonic/dotnet/System.Threading.js';
import type { Task, ValueTask } from '@tsonic/dotnet/System.Threading.Tasks.js';
import type { IServiceScopeFactory } from '@tsonic/microsoft-extensions/Microsoft.Extensions.DependencyInjection.js';
import type { ObjectPool } from '@tsonic/microsoft-extensions/Microsoft.Extensions.ObjectPool.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { DefaultSessionFeature as DefaultSessionFeature } from './Microsoft.AspNetCore.Http.Features/internal/index.js';
export { FormFeature as FormFeature } from './Microsoft.AspNetCore.Http.Features/internal/index.js';
export { FormOptions as FormOptions } from './Microsoft.AspNetCore.Http.Features/internal/index.js';
export { HttpConnectionFeature as HttpConnectionFeature } from './Microsoft.AspNetCore.Http.Features/internal/index.js';
export { HttpRequestFeature as HttpRequestFeature } from './Microsoft.AspNetCore.Http.Features/internal/index.js';
export { HttpRequestIdentifierFeature as HttpRequestIdentifierFeature } from './Microsoft.AspNetCore.Http.Features/internal/index.js';
export { HttpRequestLifetimeFeature as HttpRequestLifetimeFeature } from './Microsoft.AspNetCore.Http.Features/internal/index.js';
export { HttpResponseFeature as HttpResponseFeature } from './Microsoft.AspNetCore.Http.Features/internal/index.js';
export type IHttpActivityFeature = Internal.IHttpActivityFeature;
export { ItemsFeature as ItemsFeature } from './Microsoft.AspNetCore.Http.Features/internal/index.js';
export { QueryFeature as QueryFeature } from './Microsoft.AspNetCore.Http.Features/internal/index.js';
export { RequestBodyPipeFeature as RequestBodyPipeFeature } from './Microsoft.AspNetCore.Http.Features/internal/index.js';
export { RequestCookiesFeature as RequestCookiesFeature } from './Microsoft.AspNetCore.Http.Features/internal/index.js';
export { RequestServicesFeature as RequestServicesFeature } from './Microsoft.AspNetCore.Http.Features/internal/index.js';
export { ResponseCookiesFeature as ResponseCookiesFeature } from './Microsoft.AspNetCore.Http.Features/internal/index.js';
export { RouteValuesFeature as RouteValuesFeature } from './Microsoft.AspNetCore.Http.Features/internal/index.js';
export { ServiceProvidersFeature as ServiceProvidersFeature } from './Microsoft.AspNetCore.Http.Features/internal/index.js';
export { TlsConnectionFeature as TlsConnectionFeature } from './Microsoft.AspNetCore.Http.Features/internal/index.js';
export type IEndpointFeature = Internal.IEndpointFeature;
export type IRouteValuesFeature = Internal.IRouteValuesFeature;
export { HttpsCompressionMode as HttpsCompressionMode } from './Microsoft.AspNetCore.Http.Features/internal/index.js';
export type IBadRequestExceptionFeature = Internal.IBadRequestExceptionFeature;
export type IFormFeature = Internal.IFormFeature;
export type IHttpBodyControlFeature = Internal.IHttpBodyControlFeature;
export type IHttpConnectionFeature = Internal.IHttpConnectionFeature;
export type IHttpExtendedConnectFeature = Internal.IHttpExtendedConnectFeature;
export type IHttpMaxRequestBodySizeFeature = Internal.IHttpMaxRequestBodySizeFeature;
export type IHttpMetricsTagsFeature = Internal.IHttpMetricsTagsFeature;
export type IHttpRequestBodyDetectionFeature = Internal.IHttpRequestBodyDetectionFeature;
export type IHttpRequestFeature = Internal.IHttpRequestFeature;
export type IHttpRequestIdentifierFeature = Internal.IHttpRequestIdentifierFeature;
export type IHttpRequestLifetimeFeature = Internal.IHttpRequestLifetimeFeature;
export type IHttpRequestTrailersFeature = Internal.IHttpRequestTrailersFeature;
export type IHttpResetFeature = Internal.IHttpResetFeature;
export type IHttpResponseBodyFeature = Internal.IHttpResponseBodyFeature;
export type IHttpResponseFeature = Internal.IHttpResponseFeature;
export type IHttpResponseTrailersFeature = Internal.IHttpResponseTrailersFeature;
export type IHttpsCompressionFeature = Internal.IHttpsCompressionFeature;
export type IHttpUpgradeFeature = Internal.IHttpUpgradeFeature;
export type IHttpWebSocketFeature = Internal.IHttpWebSocketFeature;
export type IHttpWebTransportFeature = Internal.IHttpWebTransportFeature;
export type IItemsFeature = Internal.IItemsFeature;
export type IQueryFeature = Internal.IQueryFeature;
export type IRequestBodyPipeFeature = Internal.IRequestBodyPipeFeature;
export type IRequestCookiesFeature = Internal.IRequestCookiesFeature;
export type IResponseCookiesFeature = Internal.IResponseCookiesFeature;
export type IServerVariablesFeature = Internal.IServerVariablesFeature;
export type IServiceProvidersFeature = Internal.IServiceProvidersFeature;
export type ISessionFeature = Internal.ISessionFeature;
export type ITlsConnectionFeature = Internal.ITlsConnectionFeature;
export type ITlsTokenBindingFeature = Internal.ITlsTokenBindingFeature;
export type ITrackingConsentFeature = Internal.ITrackingConsentFeature;
export type IWebTransportSession = Internal.IWebTransportSession;
export { FeatureCollection as FeatureCollection } from './Microsoft.AspNetCore.Http.Features/internal/index.js';
export { FeatureCollectionExtensions$instance as FeatureCollectionExtensions } from './Microsoft.AspNetCore.Http.Features/internal/index.js';
export { FeatureReference_1 as FeatureReference } from './Microsoft.AspNetCore.Http.Features/internal/index.js';
export { FeatureReferences_1 as FeatureReferences } from './Microsoft.AspNetCore.Http.Features/internal/index.js';
export type IFeatureCollection = Internal.IFeatureCollection;
// Extension methods (C# using semantics)
export type { ExtensionMethods_Microsoft_AspNetCore_Http_Features as ExtensionMethods } from './__internal/extensions/index.js';

