// Generated by tsbindgen - Architecture
// Namespace: Microsoft.AspNetCore.Mvc.ModelBinding
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';

// Cross-namespace type imports for constraints
import type { HttpContext, IFormCollection, IFormFileCollection, IQueryCollection } from './Microsoft.AspNetCore.Http/internal/index.js';
import type { ParameterDescriptor } from './Microsoft.AspNetCore.Mvc.Abstractions/internal/index.js';
import type { ActionExecutedContext, ActionExecutingContext, IActionFilter, IFilterMetadata, IOrderedFilter } from './Microsoft.AspNetCore.Mvc.Filters/internal/index.js';
import type { DefaultMetadataDetails, DefaultModelBindingMessageProvider, DefaultModelMetadataProvider, ICompositeMetadataDetailsProvider, IMetadataDetailsProvider, IValidationMetadataProvider, ModelBindingMessageProvider, ModelMetadataIdentity, ModelMetadataKind, ValidationMetadataProviderContext } from './Microsoft.AspNetCore.Mvc.ModelBinding.Metadata/internal/index.js';
import type { IModelValidatorProvider, IObjectModelValidator, IPropertyValidationFilter, ValidationStateDictionary, ValidationVisitor, ValidatorCache } from './Microsoft.AspNetCore.Mvc.ModelBinding.Validation/internal/index.js';
import type { ActionContext, ControllerContext, MvcOptions } from './Microsoft.AspNetCore.Mvc/internal/index.js';
import type { RouteValueDictionary } from './Microsoft.AspNetCore.Routing/internal/index.js';
import type { ICollection as ICollection__System_Collections_Generic, IDictionary, IEnumerable as IEnumerable__System_Collections_Generic, IEnumerator as IEnumerator__System_Collections_Generic, IList as IList__System_Collections_Generic, IReadOnlyCollection, IReadOnlyDictionary, IReadOnlyList, KeyValuePair } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { ICollection, IEnumerable, IEnumerator, IList } from '@tsonic/dotnet/System.Collections.js';
import type { Collection, ReadOnlyCollection } from '@tsonic/dotnet/System.Collections.ObjectModel.js';
import type { CultureInfo } from '@tsonic/dotnet/System.Globalization.js';
import type { Action, Attribute, Boolean as ClrBoolean, Enum, Exception, Func, IComparable, IConvertible, IDisposable, IEquatable, IFormattable, Int32, IServiceProvider, ISpanFormattable, Nullable, Object as ClrObject, String as ClrString, Type, ValueType, Void } from '@tsonic/dotnet/System.js';
import type { Expression } from '@tsonic/dotnet/System.Linq.Expressions.js';
import type { ConstructorInfo, ParameterInfo, PropertyInfo } from '@tsonic/dotnet/System.Reflection.js';
import type { ISerializable } from '@tsonic/dotnet/System.Runtime.Serialization.js';
import type { Task, ValueTask } from '@tsonic/dotnet/System.Threading.Tasks.js';
import type { ILogger, ILoggerFactory } from '@tsonic/microsoft-extensions/Microsoft.Extensions.Logging.js';
import type { IOptions } from '@tsonic/microsoft-extensions/Microsoft.Extensions.Options.js';
import type { StringValues } from '@tsonic/microsoft-extensions/Microsoft.Extensions.Primitives.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { BindingInfo as BindingInfo } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { BindingSource as BindingSource } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { CompositeBindingSource as CompositeBindingSource } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { EmptyBodyBehavior as EmptyBodyBehavior } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { EnumGroupAndName as EnumGroupAndName } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export type IBinderTypeProviderMetadata = Internal.IBinderTypeProviderMetadata;
export type IBindingSourceMetadata = Internal.IBindingSourceMetadata;
export type IModelBinder = Internal.IModelBinder;
export type IModelBinderProvider = Internal.IModelBinderProvider;
export type IModelMetadataProvider = Internal.IModelMetadataProvider;
export type IModelNameProvider = Internal.IModelNameProvider;
export type IPropertyFilterProvider = Internal.IPropertyFilterProvider;
export type IRequestPredicateProvider = Internal.IRequestPredicateProvider;
export type IValueProvider = Internal.IValueProvider;
export type IValueProviderFactory = Internal.IValueProviderFactory;
export { ModelBinderProviderContext as ModelBinderProviderContext } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { ModelBindingContext as ModelBindingContext } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { ModelBindingContext_NestedScope as ModelBindingContext_NestedScope } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { ModelBindingResult as ModelBindingResult } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { ModelError as ModelError } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { ModelErrorCollection as ModelErrorCollection } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { ModelMetadata as ModelMetadata } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { ModelMetadataProvider as ModelMetadataProvider } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { ModelPropertyCollection as ModelPropertyCollection } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { ModelStateDictionary as ModelStateDictionary } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { ModelStateDictionary_PrefixEnumerable as ModelStateDictionary_PrefixEnumerable } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { ModelStateDictionary_Enumerator as ModelStateDictionary_Enumerator } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { ModelStateDictionary_KeyEnumerable as ModelStateDictionary_KeyEnumerable } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { ModelStateDictionary_KeyEnumerator as ModelStateDictionary_KeyEnumerator } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { ModelStateDictionary_ValueEnumerable as ModelStateDictionary_ValueEnumerable } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { ModelStateDictionary_ValueEnumerator as ModelStateDictionary_ValueEnumerator } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { ModelStateEntry as ModelStateEntry } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { ModelValidationState as ModelValidationState } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { TooManyModelErrorsException as TooManyModelErrorsException } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { ValueProviderException as ValueProviderException } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { ValueProviderFactoryContext as ValueProviderFactoryContext } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { ValueProviderResult as ValueProviderResult } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { BindingBehavior as BindingBehavior } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { BindingBehaviorAttribute as BindingBehaviorAttribute } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { BindingSourceValueProvider as BindingSourceValueProvider } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { BindNeverAttribute as BindNeverAttribute } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { BindRequiredAttribute as BindRequiredAttribute } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { CompositeValueProvider as CompositeValueProvider } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { DefaultModelBindingContext as DefaultModelBindingContext } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { DefaultPropertyFilterProvider_1 as DefaultPropertyFilterProvider } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { EmptyModelMetadataProvider as EmptyModelMetadataProvider } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { FormFileValueProvider as FormFileValueProvider } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { FormFileValueProviderFactory as FormFileValueProviderFactory } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { FormValueProvider as FormValueProvider } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { FormValueProviderFactory as FormValueProviderFactory } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export type IBindingSourceValueProvider = Internal.IBindingSourceValueProvider;
export type ICollectionModelBinder = Internal.ICollectionModelBinder;
export type IEnumerableValueProvider = Internal.IEnumerableValueProvider;
export type IKeyRewriterValueProvider = Internal.IKeyRewriterValueProvider;
export type IModelBinderFactory = Internal.IModelBinderFactory;
export { JQueryFormValueProvider as JQueryFormValueProvider } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { JQueryFormValueProviderFactory as JQueryFormValueProviderFactory } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { JQueryQueryStringValueProvider as JQueryQueryStringValueProvider } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { JQueryQueryStringValueProviderFactory as JQueryQueryStringValueProviderFactory } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { JQueryValueProvider as JQueryValueProvider } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { ModelAttributes as ModelAttributes } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { ModelBinderFactory as ModelBinderFactory } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { ModelBinderFactoryContext as ModelBinderFactoryContext } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { ModelBinderProviderExtensions$instance as ModelBinderProviderExtensions } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { ModelMetadataProviderExtensions$instance as ModelMetadataProviderExtensions } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { ModelNames$instance as ModelNames } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { ObjectModelValidator as ObjectModelValidator } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { ParameterBinder as ParameterBinder } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { PrefixContainer as PrefixContainer } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { QueryStringValueProvider as QueryStringValueProvider } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { QueryStringValueProviderFactory as QueryStringValueProviderFactory } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { RouteValueProvider as RouteValueProvider } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { RouteValueProviderFactory as RouteValueProviderFactory } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { SuppressChildValidationMetadataProvider as SuppressChildValidationMetadataProvider } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { UnsupportedContentTypeException as UnsupportedContentTypeException } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { UnsupportedContentTypeFilter as UnsupportedContentTypeFilter } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { ValueProviderFactoryExtensions$instance as ValueProviderFactoryExtensions } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
export { ModelStateDictionaryExtensions$instance as ModelStateDictionaryExtensions } from './Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js';
// Extension methods (C# using semantics)
export type { ExtensionMethods_Microsoft_AspNetCore_Mvc_ModelBinding as ExtensionMethods } from './__internal/extensions/index.js';

