// Generated by tsbindgen - Architecture
// Namespace: Microsoft.AspNetCore.Identity.UI.Services
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.AspNetCore.Identity.UI.Services/internal/index.js';

// Cross-namespace type imports for constraints
import type { Object as ClrObject, String as ClrString } from '@tsonic/dotnet/System.js';
import type { Task } from '@tsonic/dotnet/System.Threading.Tasks.js';

// Public API exports (curated - no internal $instance/$views leakage)
export type IEmailSender = Internal.IEmailSender;
export { NoOpEmailSender as NoOpEmailSender } from './Microsoft.AspNetCore.Identity.UI.Services/internal/index.js';
