// Generated by dotnet-bindgen - Architecture
// Namespace: Microsoft.AspNetCore.RequestDecompression
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.AspNetCore.RequestDecompression/internal/index.js';

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Cross-namespace type imports for constraints
import type { HttpContext } from './Microsoft.AspNetCore.Http/internal/index.js';
import type { IDictionary } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { Stream } from '@tsonic/dotnet/System.IO.js';
import type { Object as ClrObject, String as ClrString } from '@tsonic/dotnet/System.js';

// Public API exports (curated - no internal $instance/$views leakage)
export type IDecompressionProvider = Internal.IDecompressionProvider;
export type IRequestDecompressionProvider = Internal.IRequestDecompressionProvider;
export { RequestDecompressionOptions as RequestDecompressionOptions } from './Microsoft.AspNetCore.RequestDecompression/internal/index.js';
