// Generated by tsbindgen - Architecture
// Namespace: Microsoft.AspNetCore.Connections.Features
// Assembly: Microsoft.AspNetCore.Connections.Abstractions

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { ConnectionAbortedException, TransferFormat } from "../../Microsoft.AspNetCore.Connections/internal/index.js";
import type { MemoryPool } from "@tsonic/dotnet/System.Buffers.js";
import type { ICollection, IDictionary, KeyValuePair } from "@tsonic/dotnet/System.Collections.Generic.js";
import type { IDuplexPipe } from "@tsonic/dotnet/System.IO.Pipelines.js";
import type { NamedPipeServerStream } from "@tsonic/dotnet/System.IO.Pipes.js";
import type { Action, Boolean as ClrBoolean, Byte, Func, Int32, Int64, Nullable, Object as ClrObject, String as ClrString, Void } from "@tsonic/dotnet/System.js";
import type { EndPoint } from "@tsonic/dotnet/System.Net.js";
import type { TlsCipherSuite } from "@tsonic/dotnet/System.Net.Security.js";
import type { Socket } from "@tsonic/dotnet/System.Net.Sockets.js";
import type { CipherAlgorithmType, ExchangeAlgorithmType, HashAlgorithmType, SslProtocols } from "@tsonic/dotnet/System.Security.Authentication.js";
import type { ClaimsPrincipal } from "@tsonic/dotnet/System.Security.Claims.js";
import type { CancellationToken } from "@tsonic/dotnet/System.Threading.js";
import type { Task } from "@tsonic/dotnet/System.Threading.Tasks.js";

export interface IConnectionCompleteFeature$instance {
    OnCompleted(callback: Func<unknown, Task>, state: unknown): void;
}


export type IConnectionCompleteFeature = IConnectionCompleteFeature$instance;

export interface IConnectionEndPointFeature$instance {
    get LocalEndPoint(): EndPoint | undefined;
    set LocalEndPoint(value: EndPoint | undefined);
    get RemoteEndPoint(): EndPoint | undefined;
    set RemoteEndPoint(value: EndPoint | undefined);
}


export type IConnectionEndPointFeature = IConnectionEndPointFeature$instance;

export interface IConnectionHeartbeatFeature$instance {
    OnHeartbeat(action: Action<unknown>, state: unknown): void;
}


export type IConnectionHeartbeatFeature = IConnectionHeartbeatFeature$instance;

export interface IConnectionIdFeature$instance {
    ConnectionId: string;
}


export type IConnectionIdFeature = IConnectionIdFeature$instance;

export interface IConnectionInherentKeepAliveFeature$instance {
    readonly HasInherentKeepAlive: boolean;
}


export type IConnectionInherentKeepAliveFeature = IConnectionInherentKeepAliveFeature$instance;

export interface IConnectionItemsFeature$instance {
    Items: IDictionary<unknown, unknown | undefined>;
}


export type IConnectionItemsFeature = IConnectionItemsFeature$instance;

export interface IConnectionLifetimeFeature$instance {
    ConnectionClosed: CancellationToken;
    Abort(): void;
}


export type IConnectionLifetimeFeature = IConnectionLifetimeFeature$instance;

export interface IConnectionLifetimeNotificationFeature$instance {
    ConnectionClosedRequested: CancellationToken;
    RequestClose(): void;
}


export type IConnectionLifetimeNotificationFeature = IConnectionLifetimeNotificationFeature$instance;

export interface IConnectionMetricsTagsFeature$instance {
    readonly Tags: ICollection<KeyValuePair<System_Internal.String, unknown>>;
}


export type IConnectionMetricsTagsFeature = IConnectionMetricsTagsFeature$instance;

export interface IConnectionNamedPipeFeature$instance {
    readonly NamedPipe: NamedPipeServerStream;
}


export type IConnectionNamedPipeFeature = IConnectionNamedPipeFeature$instance;

export interface IConnectionSocketFeature$instance {
    readonly Socket: Socket;
}


export type IConnectionSocketFeature = IConnectionSocketFeature$instance;

export interface IConnectionTransportFeature$instance {
    Transport: IDuplexPipe;
}


export type IConnectionTransportFeature = IConnectionTransportFeature$instance;

export interface IConnectionUserFeature$instance {
    get User(): ClaimsPrincipal | undefined;
    set User(value: ClaimsPrincipal | undefined);
}


export type IConnectionUserFeature = IConnectionUserFeature$instance;

export interface IMemoryPoolFeature$instance {
    readonly MemoryPool: MemoryPool<System_Internal.Byte>;
}


export type IMemoryPoolFeature = IMemoryPoolFeature$instance;

export interface IPersistentStateFeature$instance {
    readonly State: IDictionary<unknown, unknown | undefined>;
}


export type IPersistentStateFeature = IPersistentStateFeature$instance;

export interface IProtocolErrorCodeFeature$instance {
    Error: long;
}


export type IProtocolErrorCodeFeature = IProtocolErrorCodeFeature$instance;

export interface IStreamAbortFeature$instance {
    AbortRead(errorCode: long, abortReason: ConnectionAbortedException): void;
}


export type IStreamAbortFeature = IStreamAbortFeature$instance;

export interface IStreamClosedFeature$instance {
    OnClosed(callback: Action<unknown>, state: unknown): void;
}


export type IStreamClosedFeature = IStreamClosedFeature$instance;

export interface IStreamDirectionFeature$instance {
    readonly CanRead: boolean;
    readonly CanWrite: boolean;
}


export type IStreamDirectionFeature = IStreamDirectionFeature$instance;

export interface IStreamIdFeature$instance {
    readonly StreamId: long;
}


export type IStreamIdFeature = IStreamIdFeature$instance;

export interface ITlsHandshakeFeature$instance {
    readonly Protocol: SslProtocols;
    readonly NegotiatedCipherSuite: Nullable<TlsCipherSuite>;
    readonly HostName: string;
    readonly CipherAlgorithm: CipherAlgorithmType;
    readonly CipherStrength: int;
    readonly HashAlgorithm: HashAlgorithmType;
    readonly HashStrength: int;
    readonly KeyExchangeAlgorithm: ExchangeAlgorithmType;
    readonly KeyExchangeStrength: int;
}


export type ITlsHandshakeFeature = ITlsHandshakeFeature$instance;

export interface ITransferFormatFeature$instance {
    readonly SupportedFormats: TransferFormat;
    ActiveFormat: TransferFormat;
}


export type ITransferFormatFeature = ITransferFormatFeature$instance;

