// Generated by dotnet-bindgen - Architecture
// Namespace: Microsoft.AspNetCore.SignalR
// Assembly: Microsoft.AspNetCore.SignalR, Microsoft.AspNetCore.SignalR.Common, Microsoft.AspNetCore.SignalR.Core, Microsoft.AspNetCore.SignalR.Protocols.Json

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Import types from other namespaces
import * as Microsoft_AspNetCore_Connections_Internal from "../../Microsoft.AspNetCore.Connections/internal/index.js";
import type { ConnectionContext, ConnectionHandler, IConnectionBuilder } from "../../Microsoft.AspNetCore.Connections/internal/index.js";
import type { IFeatureCollection } from "../../Microsoft.AspNetCore.Http.Features/internal/index.js";
import type { HttpContext } from "../../Microsoft.AspNetCore.Http/internal/index.js";
import type { CompletionMessage, HubMessage, IHubProtocol } from "../../Microsoft.AspNetCore.SignalR.Protocol/internal/index.js";
import * as System_Collections_Generic_Internal from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import type { IDictionary_2, IEnumerable_1, IEnumerator_1, IList_1, IReadOnlyList_1 } from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import * as System_Collections_Internal from "@tsonic/dotnet/System.Collections/internal/index.js";
import type { IEnumerator } from "@tsonic/dotnet/System.Collections/internal/index.js";
import type { MethodInfo } from "@tsonic/dotnet/System.Reflection/internal/index.js";
import * as System_Runtime_Serialization_Internal from "@tsonic/dotnet/System.Runtime.Serialization/internal/index.js";
import type { ISerializable, SerializationInfo, StreamingContext } from "@tsonic/dotnet/System.Runtime.Serialization/internal/index.js";
import type { ClaimsPrincipal } from "@tsonic/dotnet/System.Security.Claims/internal/index.js";
import type { JsonSerializerOptions } from "@tsonic/dotnet/System.Text.Json/internal/index.js";
import type { Task, Task_1, ValueTask, ValueTask_1 } from "@tsonic/dotnet/System.Threading.Tasks/internal/index.js";
import type { CancellationToken } from "@tsonic/dotnet/System.Threading/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Attribute, Boolean as ClrBoolean, Byte, Exception, Func_2, Func_3, IDisposable, Int32, Int64, IServiceProvider, Nullable_1, Object as ClrObject, ReadOnlyMemory_1, ReadOnlySpan_1, String as ClrString, TimeSpan, Type, ValueType, Void } from "@tsonic/dotnet/System/internal/index.js";
import type { IServiceCollection, IServiceScopeFactory } from "@tsonic/microsoft-extensions/Microsoft.Extensions.DependencyInjection/internal/index.js";
import type { ILogger_1, ILoggerFactory } from "@tsonic/microsoft-extensions/Microsoft.Extensions.Logging/internal/index.js";
import * as Microsoft_Extensions_Options_Internal from "@tsonic/microsoft-extensions/Microsoft.Extensions.Options/internal/index.js";
import type { IConfigureOptions_1, IOptions_1 } from "@tsonic/microsoft-extensions/Microsoft.Extensions.Options/internal/index.js";

export interface IClientProxy$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_SignalR_IClientProxy: never;

    SendCoreAsync(method: string, args: (unknown | null)[], cancellationToken?: CancellationToken): Task;
}


export type IClientProxy = IClientProxy$instance;

export interface IGroupManager$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_SignalR_IGroupManager: never;

    AddToGroupAsync(connectionId: string, groupName: string, cancellationToken?: CancellationToken): Task;
}


export type IGroupManager = IGroupManager$instance;

export interface IHubActivator_1$instance<THub extends unknown & Hub> {
    readonly __tsonic_iface_Microsoft_AspNetCore_SignalR_IHubActivator_1: never;

    Create(): THub;
    Release(hub: THub): void;
}


export type IHubActivator_1<THub extends unknown & Hub> = IHubActivator_1$instance<THub>;

export interface IHubCallerClients$instance extends IHubCallerClients_1<IClientProxy>, IHubClients_1<IClientProxy> {
    readonly __tsonic_iface_Microsoft_AspNetCore_SignalR_IHubCallerClients: never;

    readonly Caller: ISingleClientProxy;
    readonly Others: IClientProxy;
    readonly All: IClientProxy;
    AllExcept(excludedConnectionIds: IReadOnlyList_1<System_Internal.String>): IClientProxy;
    Client(connectionId: string): ISingleClientProxy;
    Client(connectionId: string): IClientProxy;
    GroupExcept(groupName: string, excludedConnectionIds: IReadOnlyList_1<System_Internal.String>): IClientProxy;
    OthersInGroup(groupName: string): IClientProxy;
}


export type IHubCallerClients = IHubCallerClients$instance;

export interface IHubCallerClients_1$instance<T extends unknown> extends IHubClients_1<T> {
    readonly __tsonic_iface_Microsoft_AspNetCore_SignalR_IHubCallerClients_1: never;

    readonly Caller: T;
    readonly Others: T;
    readonly All: T;
    AllExcept(excludedConnectionIds: IReadOnlyList_1<System_Internal.String>): T;
    Client(connectionId: string): T;
    GroupExcept(groupName: string, excludedConnectionIds: IReadOnlyList_1<System_Internal.String>): T;
    OthersInGroup(groupName: string): T;
}


export interface IHubCallerClients_1$instance<T extends unknown> extends IHubClients_1$instance<T> {}

export type IHubCallerClients_1<T extends unknown> = IHubCallerClients_1$instance<T>;

export interface IHubClients$instance extends IHubClients_1<IClientProxy> {
    readonly __tsonic_iface_Microsoft_AspNetCore_SignalR_IHubClients: never;

    readonly All: IClientProxy;
    AllExcept(excludedConnectionIds: IReadOnlyList_1<System_Internal.String>): IClientProxy;
    Client(connectionId: string): ISingleClientProxy;
    Client(connectionId: string): IClientProxy;
    GroupExcept(groupName: string, excludedConnectionIds: IReadOnlyList_1<System_Internal.String>): IClientProxy;
}


export type IHubClients = IHubClients$instance;

export interface IHubClients_1$instance<T extends unknown> {
    readonly __tsonic_iface_Microsoft_AspNetCore_SignalR_IHubClients_1: never;

    readonly All: T;
    AllExcept(excludedConnectionIds: IReadOnlyList_1<System_Internal.String>): T;
    Client(connectionId: string): T;
    GroupExcept(groupName: string, excludedConnectionIds: IReadOnlyList_1<System_Internal.String>): T;
}


export type IHubClients_1<T extends unknown> = IHubClients_1$instance<T>;

export interface IHubContext$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_SignalR_IHubContext: never;

    readonly Clients: IHubClients;
    readonly Groups: IGroupManager;
}


export type IHubContext = IHubContext$instance;

export interface IHubContext_1$instance<THub extends unknown & Hub> {
    readonly __tsonic_iface_Microsoft_AspNetCore_SignalR_IHubContext_1: never;

    readonly Clients: IHubClients;
    readonly Groups: IGroupManager;
}


export type IHubContext_1<THub extends unknown & Hub> = IHubContext_1$instance<THub>;

export interface IHubContext_2$instance<THub extends unknown & Hub_1<T>, T extends (object | null)> {
    readonly __tsonic_iface_Microsoft_AspNetCore_SignalR_IHubContext_2: never;

    readonly Clients: IHubClients_1<T>;
    readonly Groups: IGroupManager;
}


export type IHubContext_2<THub extends unknown & Hub_1<T>, T extends (object | null)> = IHubContext_2$instance<THub, T>;

export interface IHubFilter$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_SignalR_IHubFilter: never;

    InvokeMethodAsync(invocationContext: HubInvocationContext, next: Func_2<HubInvocationContext, ValueTask_1<unknown>>): ValueTask_1<unknown>;
    OnConnectedAsync(context: HubLifetimeContext, next: Func_2<HubLifetimeContext, Task>): Task;
    OnDisconnectedAsync(context: HubLifetimeContext, exception: Exception | null, next: Func_3<HubLifetimeContext, Exception | null, Task>): Task;
}


export type IHubFilter = IHubFilter$instance;

export interface IHubProtocolResolver$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_SignalR_IHubProtocolResolver: never;

    readonly AllProtocols: IReadOnlyList_1<IHubProtocol>;
    GetProtocol(protocolName: string, supportedProtocols: IReadOnlyList_1<System_Internal.String> | null): IHubProtocol | null;
}


export type IHubProtocolResolver = IHubProtocolResolver$instance;

export interface IInvocationBinder$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_SignalR_IInvocationBinder: never;

    GetParameterTypes(methodName: string): IReadOnlyList_1<Type>;
    GetReturnType(invocationId: string): Type;
    GetTarget(utf8Bytes: ReadOnlySpan_1<System_Internal.Byte>): string | null;
}


export type IInvocationBinder = IInvocationBinder$instance;

export interface ISignalRBuilder$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_SignalR_ISignalRBuilder: never;

    readonly Services: IServiceCollection;
}


export type ISignalRBuilder = ISignalRBuilder$instance;

export interface ISignalRServerBuilder$instance extends ISignalRBuilder {
    readonly __tsonic_iface_Microsoft_AspNetCore_SignalR_ISignalRServerBuilder: never;

    readonly Services: IServiceCollection;
}


export interface ISignalRServerBuilder$instance extends ISignalRBuilder$instance {}

export type ISignalRServerBuilder = ISignalRServerBuilder$instance;

export interface ISingleClientProxy$instance extends IClientProxy {
    readonly __tsonic_iface_Microsoft_AspNetCore_SignalR_ISingleClientProxy: never;

    InvokeCoreAsync<T extends unknown>(method: string, args: (unknown | null)[], cancellationToken: CancellationToken): Task_1<T>;
    SendCoreAsync(method: string, args: (unknown | null)[], cancellationToken?: CancellationToken): Task;
}


export interface ISingleClientProxy$instance extends IClientProxy$instance {}

export type ISingleClientProxy = ISingleClientProxy$instance;

export interface IUserIdProvider$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_SignalR_IUserIdProvider: never;

    GetUserId(connection: HubConnectionContext): string | null;
}


export type IUserIdProvider = IUserIdProvider$instance;

export interface SerializedMessage$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_SignalR_SerializedMessage: never;

    readonly ProtocolName: string;
    readonly Serialized: ReadOnlyMemory_1<System_Internal.Byte>;
}


export const SerializedMessage: {
    new(protocolName: string, serialized: ReadOnlyMemory_1<System_Internal.Byte>): SerializedMessage;
};


export type SerializedMessage = SerializedMessage$instance;

export interface DefaultHubLifetimeManager_1$instance<THub extends unknown & Hub> extends HubLifetimeManager_1<THub> {
    readonly __tsonic_type_Microsoft_AspNetCore_SignalR_DefaultHubLifetimeManager_1: never;

    AddToGroupAsync(connectionId: string, groupName: string, cancellationToken?: CancellationToken): Task;
    InvokeConnectionAsync<T extends unknown>(connectionId: string, methodName: string, args: (unknown | null)[], cancellationToken: CancellationToken): Task_1<T>;
    InvokeConnectionAsync<T extends unknown>(connectionId: string, methodName: string, args: (unknown | null)[], cancellationToken: CancellationToken): Task_1<T>;
    OnConnectedAsync(connection: HubConnectionContext): Task;
    OnDisconnectedAsync(connection: HubConnectionContext): Task;
    RemoveFromGroupAsync(connectionId: string, groupName: string, cancellationToken?: CancellationToken): Task;
    SendAllAsync(methodName: string, args: (unknown | null)[], cancellationToken?: CancellationToken): Task;
    SendAllExceptAsync(methodName: string, args: (unknown | null)[], excludedConnectionIds: IReadOnlyList_1<System_Internal.String>, cancellationToken?: CancellationToken): Task;
    SendConnectionAsync(connectionId: string, methodName: string, args: (unknown | null)[], cancellationToken?: CancellationToken): Task;
    SendConnectionsAsync(connectionIds: IReadOnlyList_1<System_Internal.String>, methodName: string, args: (unknown | null)[], cancellationToken?: CancellationToken): Task;
    SendGroupAsync(groupName: string, methodName: string, args: (unknown | null)[], cancellationToken?: CancellationToken): Task;
    SendGroupExceptAsync(groupName: string, methodName: string, args: (unknown | null)[], excludedConnectionIds: IReadOnlyList_1<System_Internal.String>, cancellationToken?: CancellationToken): Task;
    SendGroupsAsync(groupNames: IReadOnlyList_1<System_Internal.String>, methodName: string, args: (unknown | null)[], cancellationToken?: CancellationToken): Task;
    SendUserAsync(userId: string, methodName: string, args: (unknown | null)[], cancellationToken?: CancellationToken): Task;
    SendUsersAsync(userIds: IReadOnlyList_1<System_Internal.String>, methodName: string, args: (unknown | null)[], cancellationToken?: CancellationToken): Task;
    SetConnectionResultAsync(connectionId: string, result: CompletionMessage): Task;
    TryGetReturnType(invocationId: string, type: Type | null): boolean;
}


export const DefaultHubLifetimeManager_1: {
    new<THub extends unknown & Hub>(logger: ILogger_1<DefaultHubLifetimeManager_1<THub>>): DefaultHubLifetimeManager_1<THub>;
};


export type DefaultHubLifetimeManager_1<THub extends unknown & Hub> = DefaultHubLifetimeManager_1$instance<THub>;

export interface DefaultUserIdProvider$instance extends IUserIdProvider$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_SignalR_DefaultUserIdProvider: never;

    readonly __tsonic_iface_Microsoft_AspNetCore_SignalR_IUserIdProvider: never;

    GetUserId(connection: HubConnectionContext): string | null;
}


export const DefaultUserIdProvider: {
    new(): DefaultUserIdProvider;
};


export interface __DefaultUserIdProvider$views {
    As_IUserIdProvider(): IUserIdProvider$instance;
}

export type DefaultUserIdProvider = DefaultUserIdProvider$instance & __DefaultUserIdProvider$views;


export interface DynamicHub$instance extends Hub {
    readonly __tsonic_type_Microsoft_AspNetCore_SignalR_DynamicHub: never;

    readonly __tsonic_iface_System_IDisposable: never;

    Clients: DynamicHubClients | IHubCallerClients;
}


export const DynamicHub: (abstract new() => DynamicHub) & {
};


export type DynamicHub = DynamicHub$instance;

export interface DynamicHubClients$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_SignalR_DynamicHubClients: never;

    readonly All: unknown;
    readonly Caller: unknown;
    readonly Others: unknown;
    AllExcept(excludedConnectionIds: IReadOnlyList_1<System_Internal.String>): unknown;
    Client(connectionId: string): unknown;
    Clients(connectionIds: IReadOnlyList_1<System_Internal.String>): unknown;
    Group(groupName: string): unknown;
    GroupExcept(groupName: string, excludedConnectionIds: IReadOnlyList_1<System_Internal.String>): unknown;
    Groups(groupNames: IReadOnlyList_1<System_Internal.String>): unknown;
    OthersInGroup(groupName: string): unknown;
    User(userId: string): unknown;
    Users(userIds: IReadOnlyList_1<System_Internal.String>): unknown;
}


export const DynamicHubClients: {
    new(clients: IHubCallerClients): DynamicHubClients;
};


export type DynamicHubClients = DynamicHubClients$instance;

export interface Hub$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_SignalR_Hub: never;

    readonly __tsonic_iface_System_IDisposable: never;

    Clients: DynamicHubClients | IHubCallerClients;
    Context: HubCallerContext;
    Groups: IGroupManager;
    Dispose(disposing: boolean): void;
    Dispose(): void;
    OnConnectedAsync(): Task;
    OnDisconnectedAsync(exception: Exception | null): Task;
}


export const Hub: (abstract new() => Hub) & {
};


export type Hub = Hub$instance;

export interface Hub_1$instance<T extends (object | null)> extends Hub {
    readonly __tsonic_type_Microsoft_AspNetCore_SignalR_Hub_1: never;

    readonly __tsonic_iface_System_IDisposable: never;

    Clients: IHubCallerClients_1<T>;
}


export const Hub_1: (abstract new<T extends (object | null)>() => Hub_1<T>) & {
};


export type Hub_1<T extends (object | null)> = Hub_1$instance<T>;

export interface HubCallerContext$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_SignalR_HubCallerContext: never;

    readonly ConnectionAborted: CancellationToken;
    readonly ConnectionId: string;
    readonly Features: IFeatureCollection;
    readonly Items: IDictionary_2<unknown, unknown | null>;
    readonly User: ClaimsPrincipal | null;
    readonly UserIdentifier: string | null;
    Abort(): void;
}


export const HubCallerContext: (abstract new() => HubCallerContext) & {
};


export type HubCallerContext = HubCallerContext$instance;

export interface HubConnectionContext$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_SignalR_HubConnectionContext: never;

    readonly ConnectionAborted: CancellationToken;
    readonly ConnectionId: string;
    readonly Features: IFeatureCollection;
    readonly Items: IDictionary_2<unknown, unknown | null>;
    Protocol: IHubProtocol;
    readonly User: ClaimsPrincipal;
    get UserIdentifier(): string | null;
    set UserIdentifier(value: string | null);
    Abort(): void;
    WriteAsync(message: HubMessage, cancellationToken?: CancellationToken): ValueTask;
    WriteAsync(message: SerializedHubMessage, cancellationToken?: CancellationToken): ValueTask;
}


export const HubConnectionContext: {
    new(connectionContext: ConnectionContext, contextOptions: HubConnectionContextOptions, loggerFactory: ILoggerFactory): HubConnectionContext;
};


export type HubConnectionContext = HubConnectionContext$instance;

export interface HubConnectionContextOptions$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_SignalR_HubConnectionContextOptions: never;

    ClientTimeoutInterval: TimeSpan;
    KeepAliveInterval: TimeSpan;
    MaximumParallelInvocations: int;
    get MaximumReceiveMessageSize(): Nullable_1<System_Internal.Int64>;
    set MaximumReceiveMessageSize(value: Nullable_1<System_Internal.Int64> | long);
    StreamBufferCapacity: int;
}


export const HubConnectionContextOptions: {
    new(): HubConnectionContextOptions;
};


export type HubConnectionContextOptions = HubConnectionContextOptions$instance;

export interface HubConnectionHandler_1$instance<THub extends unknown & Hub> extends ConnectionHandler {
    readonly __tsonic_type_Microsoft_AspNetCore_SignalR_HubConnectionHandler_1: never;

    OnConnectedAsync(connection: ConnectionContext): Task;
}


export const HubConnectionHandler_1: {
    new<THub extends unknown & Hub>(lifetimeManager: HubLifetimeManager_1<THub>, protocolResolver: IHubProtocolResolver, globalHubOptions: IOptions_1<HubOptions>, hubOptions: IOptions_1<HubOptions_1<THub>>, loggerFactory: ILoggerFactory, userIdProvider: IUserIdProvider, serviceScopeFactory: IServiceScopeFactory): HubConnectionHandler_1<THub>;
};


export type HubConnectionHandler_1<THub extends unknown & Hub> = HubConnectionHandler_1$instance<THub>;

export interface HubConnectionStore$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_SignalR_HubConnectionStore: never;

    readonly Count: int;
    Add(connection: HubConnectionContext): void;
    GetEnumerator(): HubConnectionStore_Enumerator;
    Remove(connection: HubConnectionContext): void;
}


export const HubConnectionStore: {
    new(): HubConnectionStore;
};


export type HubConnectionStore = HubConnectionStore$instance & { readonly [connectionId: string]: HubConnectionContext | null; };

export interface HubConnectionStore_Enumerator$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_SignalR_HubConnectionStore_Enumerator: never;

    readonly __tsonic_iface_System_Collections_Generic_IEnumerator_1: never;
    readonly __tsonic_iface_System_Collections_IEnumerator: never;
    readonly __tsonic_iface_System_IDisposable: never;

    readonly Current: HubConnectionContext;
    Dispose(): void;
    MoveNext(): boolean;
    Reset(): void;
}


export const HubConnectionStore_Enumerator: {
    new(hubConnectionList: HubConnectionStore): HubConnectionStore_Enumerator;
};


export type HubConnectionStore_Enumerator = HubConnectionStore_Enumerator$instance;

export interface HubException$instance extends Exception {
    readonly __tsonic_type_Microsoft_AspNetCore_SignalR_HubException: never;

    readonly __tsonic_iface_System_Runtime_Serialization_ISerializable: never;

}


export const HubException: {
    new(): HubException;
    new(message: string | null): HubException;
    new(message: string | null, innerException: Exception | null): HubException;
    new(info: SerializationInfo, context: StreamingContext): HubException;
};


export type HubException = HubException$instance;

export interface HubInvocationContext$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_SignalR_HubInvocationContext: never;

    readonly Context: HubCallerContext;
    readonly Hub: Hub;
    readonly HubMethod: MethodInfo;
    readonly HubMethodArguments: IReadOnlyList_1<unknown | null>;
    readonly HubMethodName: string;
    readonly ServiceProvider: IServiceProvider;
}


export const HubInvocationContext: {
    new(context: HubCallerContext, serviceProvider: IServiceProvider, hub: Hub, hubMethod: MethodInfo, hubMethodArguments: IReadOnlyList_1<unknown | null>): HubInvocationContext;
};


export type HubInvocationContext = HubInvocationContext$instance;

export interface HubLifetimeContext$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_SignalR_HubLifetimeContext: never;

    readonly Context: HubCallerContext;
    readonly Hub: Hub;
    readonly ServiceProvider: IServiceProvider;
}


export const HubLifetimeContext: {
    new(context: HubCallerContext, serviceProvider: IServiceProvider, hub: Hub): HubLifetimeContext;
};


export type HubLifetimeContext = HubLifetimeContext$instance;

export interface HubLifetimeManager_1$instance<THub extends unknown & Hub> {
    readonly __tsonic_type_Microsoft_AspNetCore_SignalR_HubLifetimeManager_1: never;

    AddToGroupAsync(connectionId: string, groupName: string, cancellationToken?: CancellationToken): Task;
    InvokeConnectionAsync<T extends unknown>(connectionId: string, methodName: string, args: (unknown | null)[], cancellationToken: CancellationToken): Task_1<T>;
    OnConnectedAsync(connection: HubConnectionContext): Task;
    OnDisconnectedAsync(connection: HubConnectionContext): Task;
    RemoveFromGroupAsync(connectionId: string, groupName: string, cancellationToken?: CancellationToken): Task;
    SendAllAsync(methodName: string, args: (unknown | null)[], cancellationToken?: CancellationToken): Task;
    SendAllExceptAsync(methodName: string, args: (unknown | null)[], excludedConnectionIds: IReadOnlyList_1<System_Internal.String>, cancellationToken?: CancellationToken): Task;
    SendConnectionAsync(connectionId: string, methodName: string, args: (unknown | null)[], cancellationToken?: CancellationToken): Task;
    SendConnectionsAsync(connectionIds: IReadOnlyList_1<System_Internal.String>, methodName: string, args: (unknown | null)[], cancellationToken?: CancellationToken): Task;
    SendGroupAsync(groupName: string, methodName: string, args: (unknown | null)[], cancellationToken?: CancellationToken): Task;
    SendGroupExceptAsync(groupName: string, methodName: string, args: (unknown | null)[], excludedConnectionIds: IReadOnlyList_1<System_Internal.String>, cancellationToken?: CancellationToken): Task;
    SendGroupsAsync(groupNames: IReadOnlyList_1<System_Internal.String>, methodName: string, args: (unknown | null)[], cancellationToken?: CancellationToken): Task;
    SendUserAsync(userId: string, methodName: string, args: (unknown | null)[], cancellationToken?: CancellationToken): Task;
    SendUsersAsync(userIds: IReadOnlyList_1<System_Internal.String>, methodName: string, args: (unknown | null)[], cancellationToken?: CancellationToken): Task;
    SetConnectionResultAsync(connectionId: string, result: CompletionMessage): Task;
    TryGetReturnType(invocationId: string, type: Type | null): boolean;
}


export const HubLifetimeManager_1: (abstract new<THub extends unknown & Hub>() => HubLifetimeManager_1<THub>) & {
};


export type HubLifetimeManager_1<THub extends unknown & Hub> = HubLifetimeManager_1$instance<THub>;

export interface HubMetadata$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_SignalR_HubMetadata: never;

    readonly HubType: Type;
}


export const HubMetadata: {
    new(hubType: Type): HubMetadata;
};


export type HubMetadata = HubMetadata$instance;

export interface HubMethodNameAttribute$instance extends Attribute {
    readonly __tsonic_type_Microsoft_AspNetCore_SignalR_HubMethodNameAttribute: never;

    readonly Name: string;
}


export const HubMethodNameAttribute: {
    new(name: string): HubMethodNameAttribute;
};


export type HubMethodNameAttribute = HubMethodNameAttribute$instance;

export interface HubOptions$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_SignalR_HubOptions: never;

    get ClientTimeoutInterval(): Nullable_1<TimeSpan>;
    set ClientTimeoutInterval(value: Nullable_1<TimeSpan> | TimeSpan);
    DisableImplicitFromServicesParameters: boolean;
    get EnableDetailedErrors(): Nullable_1<System_Internal.Boolean>;
    set EnableDetailedErrors(value: Nullable_1<System_Internal.Boolean> | boolean);
    get HandshakeTimeout(): Nullable_1<TimeSpan>;
    set HandshakeTimeout(value: Nullable_1<TimeSpan> | TimeSpan);
    get KeepAliveInterval(): Nullable_1<TimeSpan>;
    set KeepAliveInterval(value: Nullable_1<TimeSpan> | TimeSpan);
    MaximumParallelInvocationsPerClient: int;
    get MaximumReceiveMessageSize(): Nullable_1<System_Internal.Int64>;
    set MaximumReceiveMessageSize(value: Nullable_1<System_Internal.Int64> | long);
    StatefulReconnectBufferSize: long;
    get StreamBufferCapacity(): Nullable_1<System_Internal.Int32>;
    set StreamBufferCapacity(value: Nullable_1<System_Internal.Int32> | int);
    get SupportedProtocols(): IList_1<System_Internal.String> | null;
    set SupportedProtocols(value: IList_1<System_Internal.String> | null);
}


export const HubOptions: {
    new(): HubOptions;
};


export type HubOptions = HubOptions$instance;

export interface HubOptions_1$instance<THub extends unknown & Hub> extends HubOptions {
    readonly __tsonic_type_Microsoft_AspNetCore_SignalR_HubOptions_1: never;

}


export const HubOptions_1: {
    new<THub extends unknown & Hub>(): HubOptions_1<THub>;
};


export type HubOptions_1<THub extends unknown & Hub> = HubOptions_1$instance<THub>;

export interface HubOptionsSetup$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_SignalR_HubOptionsSetup: never;

    readonly __tsonic_iface_Microsoft_Extensions_Options_IConfigureOptions_1: never;

    Configure(options: HubOptions): void;
}


export const HubOptionsSetup: {
    new(protocols: IEnumerable_1<IHubProtocol>): HubOptionsSetup;
};


export type HubOptionsSetup = HubOptionsSetup$instance;

export interface HubOptionsSetup_1$instance<THub extends unknown & Hub> {
    readonly __tsonic_type_Microsoft_AspNetCore_SignalR_HubOptionsSetup_1: never;

    readonly __tsonic_iface_Microsoft_Extensions_Options_IConfigureOptions_1: never;

    Configure(options: HubOptions_1<THub>): void;
}


export const HubOptionsSetup_1: {
    new<THub extends unknown & Hub>(options: IOptions_1<HubOptions>): HubOptionsSetup_1<THub>;
};


export type HubOptionsSetup_1<THub extends unknown & Hub> = HubOptionsSetup_1$instance<THub>;

export interface JsonHubProtocolOptions$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_SignalR_JsonHubProtocolOptions: never;

    PayloadSerializerOptions: JsonSerializerOptions;
}


export const JsonHubProtocolOptions: {
    new(): JsonHubProtocolOptions;
};


export type JsonHubProtocolOptions = JsonHubProtocolOptions$instance;

export interface SerializedHubMessage$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_SignalR_SerializedHubMessage: never;

    readonly Message: HubMessage | null;
    GetSerializedMessage(protocol: IHubProtocol): ReadOnlyMemory_1<System_Internal.Byte>;
}


export const SerializedHubMessage: {
    new(messages: IReadOnlyList_1<SerializedMessage>): SerializedHubMessage;
    new(message: HubMessage): SerializedHubMessage;
};


export type SerializedHubMessage = SerializedHubMessage$instance;

export abstract class ClientProxyExtensions$instance {
    static InvokeAsync<T extends unknown>(clientProxy: ISingleClientProxy, method: string, arg1: unknown | null, arg2: unknown | null, arg3: unknown | null, arg4: unknown | null, arg5: unknown | null, arg6: unknown | null, arg7: unknown | null, arg8: unknown | null, arg9: unknown | null, arg10: unknown | null, cancellationToken: CancellationToken): Task_1<T>;
    static InvokeAsync<T extends unknown>(clientProxy: ISingleClientProxy, method: string, arg1: unknown | null, arg2: unknown | null, arg3: unknown | null, arg4: unknown | null, arg5: unknown | null, arg6: unknown | null, arg7: unknown | null, arg8: unknown | null, arg9: unknown | null, cancellationToken: CancellationToken): Task_1<T>;
    static InvokeAsync<T extends unknown>(clientProxy: ISingleClientProxy, method: string, arg1: unknown | null, arg2: unknown | null, arg3: unknown | null, arg4: unknown | null, arg5: unknown | null, arg6: unknown | null, arg7: unknown | null, arg8: unknown | null, cancellationToken: CancellationToken): Task_1<T>;
    static InvokeAsync<T extends unknown>(clientProxy: ISingleClientProxy, method: string, arg1: unknown | null, arg2: unknown | null, arg3: unknown | null, arg4: unknown | null, arg5: unknown | null, arg6: unknown | null, arg7: unknown | null, cancellationToken: CancellationToken): Task_1<T>;
    static InvokeAsync<T extends unknown>(clientProxy: ISingleClientProxy, method: string, arg1: unknown | null, arg2: unknown | null, arg3: unknown | null, arg4: unknown | null, arg5: unknown | null, arg6: unknown | null, cancellationToken: CancellationToken): Task_1<T>;
    static InvokeAsync<T extends unknown>(clientProxy: ISingleClientProxy, method: string, arg1: unknown | null, arg2: unknown | null, arg3: unknown | null, arg4: unknown | null, arg5: unknown | null, cancellationToken: CancellationToken): Task_1<T>;
    static InvokeAsync<T extends unknown>(clientProxy: ISingleClientProxy, method: string, arg1: unknown | null, arg2: unknown | null, arg3: unknown | null, arg4: unknown | null, cancellationToken: CancellationToken): Task_1<T>;
    static InvokeAsync<T extends unknown>(clientProxy: ISingleClientProxy, method: string, arg1: unknown | null, arg2: unknown | null, arg3: unknown | null, cancellationToken: CancellationToken): Task_1<T>;
    static InvokeAsync<T extends unknown>(clientProxy: ISingleClientProxy, method: string, arg1: unknown | null, arg2: unknown | null, cancellationToken: CancellationToken): Task_1<T>;
    static InvokeAsync<T extends unknown>(clientProxy: ISingleClientProxy, method: string, arg1: unknown | null, cancellationToken: CancellationToken): Task_1<T>;
    static InvokeAsync<T extends unknown>(clientProxy: ISingleClientProxy, method: string, cancellationToken: CancellationToken): Task_1<T>;
    static SendAsync(clientProxy: IClientProxy, method: string, arg1: unknown | null, arg2: unknown | null, arg3: unknown | null, arg4: unknown | null, arg5: unknown | null, arg6: unknown | null, arg7: unknown | null, arg8: unknown | null, arg9: unknown | null, arg10: unknown | null, cancellationToken?: CancellationToken): Task;
    static SendAsync(clientProxy: IClientProxy, method: string, arg1: unknown | null, arg2: unknown | null, arg3: unknown | null, arg4: unknown | null, arg5: unknown | null, arg6: unknown | null, arg7: unknown | null, arg8: unknown | null, arg9: unknown | null, cancellationToken?: CancellationToken): Task;
    static SendAsync(clientProxy: IClientProxy, method: string, arg1: unknown | null, arg2: unknown | null, arg3: unknown | null, arg4: unknown | null, arg5: unknown | null, arg6: unknown | null, arg7: unknown | null, arg8: unknown | null, cancellationToken?: CancellationToken): Task;
    static SendAsync(clientProxy: IClientProxy, method: string, arg1: unknown | null, arg2: unknown | null, arg3: unknown | null, arg4: unknown | null, arg5: unknown | null, arg6: unknown | null, arg7: unknown | null, cancellationToken?: CancellationToken): Task;
    static SendAsync(clientProxy: IClientProxy, method: string, arg1: unknown | null, arg2: unknown | null, arg3: unknown | null, arg4: unknown | null, arg5: unknown | null, arg6: unknown | null, cancellationToken?: CancellationToken): Task;
    static SendAsync(clientProxy: IClientProxy, method: string, arg1: unknown | null, arg2: unknown | null, arg3: unknown | null, arg4: unknown | null, arg5: unknown | null, cancellationToken?: CancellationToken): Task;
    static SendAsync(clientProxy: IClientProxy, method: string, arg1: unknown | null, arg2: unknown | null, arg3: unknown | null, arg4: unknown | null, cancellationToken?: CancellationToken): Task;
    static SendAsync(clientProxy: IClientProxy, method: string, arg1: unknown | null, arg2: unknown | null, arg3: unknown | null, cancellationToken?: CancellationToken): Task;
    static SendAsync(clientProxy: IClientProxy, method: string, arg1: unknown | null, arg2: unknown | null, cancellationToken?: CancellationToken): Task;
    static SendAsync(clientProxy: IClientProxy, method: string, arg1: unknown | null, cancellationToken?: CancellationToken): Task;
    static SendAsync(clientProxy: IClientProxy, method: string, cancellationToken?: CancellationToken): Task;
}


export type ClientProxyExtensions = ClientProxyExtensions$instance;

export abstract class GetHttpContextExtensions$instance {
    static GetHttpContext(connection: HubCallerContext): HttpContext | null;
    static GetHttpContext(connection: HubConnectionContext): HttpContext | null;
}


export type GetHttpContextExtensions = GetHttpContextExtensions$instance;

export abstract class HubClientsExtensions$instance {
    static AllExcept<T extends unknown>(hubClients: IHubClients_1<T>, excludedConnectionIds: IEnumerable_1<System_Internal.String>): T;
    static AllExcept<T extends unknown>(hubClients: IHubClients_1<T>, excludedConnectionId1: string, excludedConnectionId2: string, excludedConnectionId3: string, excludedConnectionId4: string, excludedConnectionId5: string, excludedConnectionId6: string, excludedConnectionId7: string, excludedConnectionId8: string): T;
    static AllExcept<T extends unknown>(hubClients: IHubClients_1<T>, excludedConnectionId1: string, excludedConnectionId2: string, excludedConnectionId3: string, excludedConnectionId4: string, excludedConnectionId5: string, excludedConnectionId6: string, excludedConnectionId7: string): T;
    static AllExcept<T extends unknown>(hubClients: IHubClients_1<T>, excludedConnectionId1: string, excludedConnectionId2: string, excludedConnectionId3: string, excludedConnectionId4: string, excludedConnectionId5: string, excludedConnectionId6: string): T;
    static AllExcept<T extends unknown>(hubClients: IHubClients_1<T>, excludedConnectionId1: string, excludedConnectionId2: string, excludedConnectionId3: string, excludedConnectionId4: string, excludedConnectionId5: string): T;
    static AllExcept<T extends unknown>(hubClients: IHubClients_1<T>, excludedConnectionId1: string, excludedConnectionId2: string, excludedConnectionId3: string, excludedConnectionId4: string): T;
    static AllExcept<T extends unknown>(hubClients: IHubClients_1<T>, excludedConnectionId1: string, excludedConnectionId2: string, excludedConnectionId3: string): T;
    static AllExcept<T extends unknown>(hubClients: IHubClients_1<T>, excludedConnectionId1: string, excludedConnectionId2: string): T;
    static AllExcept<T extends unknown>(hubClients: IHubClients_1<T>, excludedConnectionId1: string): T;
    static Clients<T extends unknown>(hubClients: IHubClients_1<T>, connectionIds: IEnumerable_1<System_Internal.String>): T;
    static Clients<T extends unknown>(hubClients: IHubClients_1<T>, connection1: string, connection2: string, connection3: string, connection4: string, connection5: string, connection6: string, connection7: string, connection8: string): T;
    static Clients<T extends unknown>(hubClients: IHubClients_1<T>, connection1: string, connection2: string, connection3: string, connection4: string, connection5: string, connection6: string, connection7: string): T;
    static Clients<T extends unknown>(hubClients: IHubClients_1<T>, connection1: string, connection2: string, connection3: string, connection4: string, connection5: string, connection6: string): T;
    static Clients<T extends unknown>(hubClients: IHubClients_1<T>, connection1: string, connection2: string, connection3: string, connection4: string, connection5: string): T;
    static Clients<T extends unknown>(hubClients: IHubClients_1<T>, connection1: string, connection2: string, connection3: string, connection4: string): T;
    static Clients<T extends unknown>(hubClients: IHubClients_1<T>, connection1: string, connection2: string, connection3: string): T;
    static Clients<T extends unknown>(hubClients: IHubClients_1<T>, connection1: string, connection2: string): T;
    static Clients<T extends unknown>(hubClients: IHubClients_1<T>, connection1: string): T;
    static GroupExcept<T extends unknown>(hubClients: IHubClients_1<T>, groupName: string, excludedConnectionIds: IEnumerable_1<System_Internal.String>): T;
    static GroupExcept<T extends unknown>(hubClients: IHubClients_1<T>, groupName: string, excludedConnectionId1: string, excludedConnectionId2: string, excludedConnectionId3: string, excludedConnectionId4: string, excludedConnectionId5: string, excludedConnectionId6: string, excludedConnectionId7: string, excludedConnectionId8: string): T;
    static GroupExcept<T extends unknown>(hubClients: IHubClients_1<T>, groupName: string, excludedConnectionId1: string, excludedConnectionId2: string, excludedConnectionId3: string, excludedConnectionId4: string, excludedConnectionId5: string, excludedConnectionId6: string, excludedConnectionId7: string): T;
    static GroupExcept<T extends unknown>(hubClients: IHubClients_1<T>, groupName: string, excludedConnectionId1: string, excludedConnectionId2: string, excludedConnectionId3: string, excludedConnectionId4: string, excludedConnectionId5: string, excludedConnectionId6: string): T;
    static GroupExcept<T extends unknown>(hubClients: IHubClients_1<T>, groupName: string, excludedConnectionId1: string, excludedConnectionId2: string, excludedConnectionId3: string, excludedConnectionId4: string, excludedConnectionId5: string): T;
    static GroupExcept<T extends unknown>(hubClients: IHubClients_1<T>, groupName: string, excludedConnectionId1: string, excludedConnectionId2: string, excludedConnectionId3: string, excludedConnectionId4: string): T;
    static GroupExcept<T extends unknown>(hubClients: IHubClients_1<T>, groupName: string, excludedConnectionId1: string, excludedConnectionId2: string, excludedConnectionId3: string): T;
    static GroupExcept<T extends unknown>(hubClients: IHubClients_1<T>, groupName: string, excludedConnectionId1: string, excludedConnectionId2: string): T;
    static GroupExcept<T extends unknown>(hubClients: IHubClients_1<T>, groupName: string, excludedConnectionId1: string): T;
    static Groups<T extends unknown>(hubClients: IHubClients_1<T>, groupNames: IEnumerable_1<System_Internal.String>): T;
    static Groups<T extends unknown>(hubClients: IHubClients_1<T>, group1: string, group2: string, group3: string, group4: string, group5: string, group6: string, group7: string, group8: string): T;
    static Groups<T extends unknown>(hubClients: IHubClients_1<T>, group1: string, group2: string, group3: string, group4: string, group5: string, group6: string, group7: string): T;
    static Groups<T extends unknown>(hubClients: IHubClients_1<T>, group1: string, group2: string, group3: string, group4: string, group5: string, group6: string): T;
    static Groups<T extends unknown>(hubClients: IHubClients_1<T>, group1: string, group2: string, group3: string, group4: string, group5: string): T;
    static Groups<T extends unknown>(hubClients: IHubClients_1<T>, group1: string, group2: string, group3: string, group4: string): T;
    static Groups<T extends unknown>(hubClients: IHubClients_1<T>, group1: string, group2: string, group3: string): T;
    static Groups<T extends unknown>(hubClients: IHubClients_1<T>, group1: string, group2: string): T;
    static Groups<T extends unknown>(hubClients: IHubClients_1<T>, group1: string): T;
    static Users<T extends unknown>(hubClients: IHubClients_1<T>, userIds: IEnumerable_1<System_Internal.String>): T;
    static Users<T extends unknown>(hubClients: IHubClients_1<T>, user1: string, user2: string, user3: string, user4: string, user5: string, user6: string, user7: string, user8: string): T;
    static Users<T extends unknown>(hubClients: IHubClients_1<T>, user1: string, user2: string, user3: string, user4: string, user5: string, user6: string, user7: string): T;
    static Users<T extends unknown>(hubClients: IHubClients_1<T>, user1: string, user2: string, user3: string, user4: string, user5: string, user6: string): T;
    static Users<T extends unknown>(hubClients: IHubClients_1<T>, user1: string, user2: string, user3: string, user4: string, user5: string): T;
    static Users<T extends unknown>(hubClients: IHubClients_1<T>, user1: string, user2: string, user3: string, user4: string): T;
    static Users<T extends unknown>(hubClients: IHubClients_1<T>, user1: string, user2: string, user3: string): T;
    static Users<T extends unknown>(hubClients: IHubClients_1<T>, user1: string, user2: string): T;
    static Users<T extends unknown>(hubClients: IHubClients_1<T>, user1: string): T;
}


export type HubClientsExtensions = HubClientsExtensions$instance;

export abstract class HubOptionsExtensions$instance {
    static AddFilter(options: HubOptions, hubFilter: IHubFilter): void;
    static AddFilter(options: HubOptions, filterType: Type): void;
    static AddFilter<TFilter extends unknown & IHubFilter>(options: HubOptions): void;
}


export type HubOptionsExtensions = HubOptionsExtensions$instance;

export abstract class SignalRConnectionBuilderExtensions$instance {
    static UseHub<THub extends unknown & Hub>(connectionBuilder: IConnectionBuilder): IConnectionBuilder;
}


export type SignalRConnectionBuilderExtensions = SignalRConnectionBuilderExtensions$instance;
