// Generated by tsbindgen - Architecture
// Namespace: Microsoft.AspNetCore.Server.Kestrel
// Assembly: Microsoft.AspNetCore.Server.Kestrel.Core

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { KestrelServerOptions, ListenOptions } from "../../Microsoft.AspNetCore.Server.Kestrel.Core/internal/index.js";
import type { HttpsConnectionAdapterOptions } from "../../Microsoft.AspNetCore.Server.Kestrel.Https/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Action, Boolean as ClrBoolean, Int32, Object as ClrObject, String as ClrString, UInt64, Void } from "@tsonic/dotnet/System.js";
import type { IPAddress, IPEndPoint } from "@tsonic/dotnet/System.Net.js";
import type { IConfiguration, IConfigurationSection } from "@tsonic/microsoft-extensions/Microsoft.Extensions.Configuration.js";

export interface EndpointConfiguration$instance {
    readonly ConfigSection: IConfigurationSection;
    readonly HttpsOptions: HttpsConnectionAdapterOptions;
    readonly IsHttps: boolean;
    readonly ListenOptions: ListenOptions;
}


export const EndpointConfiguration: {
};


export type EndpointConfiguration = EndpointConfiguration$instance;

export interface KestrelConfigurationLoader$instance {
    Configuration: IConfiguration;
    readonly Options: KestrelServerOptions;
    AnyIPEndpoint(port: int): KestrelConfigurationLoader;
    AnyIPEndpoint(port: int, configure: Action<ListenOptions>): KestrelConfigurationLoader;
    Endpoint(name: string, configureOptions: Action<EndpointConfiguration>): KestrelConfigurationLoader;
    Endpoint(address: IPAddress, port: int): KestrelConfigurationLoader;
    Endpoint(address: IPAddress, port: int, configure: Action<ListenOptions>): KestrelConfigurationLoader;
    Endpoint(endPoint: IPEndPoint): KestrelConfigurationLoader;
    Endpoint(endPoint: IPEndPoint, configure: Action<ListenOptions>): KestrelConfigurationLoader;
    HandleEndpoint(handle: ulong): KestrelConfigurationLoader;
    HandleEndpoint(handle: ulong, configure: Action<ListenOptions>): KestrelConfigurationLoader;
    Load(): void;
    LocalhostEndpoint(port: int): KestrelConfigurationLoader;
    LocalhostEndpoint(port: int, configure: Action<ListenOptions>): KestrelConfigurationLoader;
    NamedPipeEndpoint(pipeName: string): KestrelConfigurationLoader;
    NamedPipeEndpoint(pipeName: string, configure: Action<ListenOptions>): KestrelConfigurationLoader;
    UnixSocketEndpoint(socketPath: string): KestrelConfigurationLoader;
    UnixSocketEndpoint(socketPath: string, configure: Action<ListenOptions>): KestrelConfigurationLoader;
}


export const KestrelConfigurationLoader: {
};


export type KestrelConfigurationLoader = KestrelConfigurationLoader$instance;

