// Generated by dotnet-bindgen - Architecture
// Namespace: Microsoft.AspNetCore.Mvc.ModelBinding.Validation
// Assembly: Microsoft.AspNetCore.Mvc.Abstractions, Microsoft.AspNetCore.Mvc.Core

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Import types from other namespaces
import type { IModelMetadataProvider, ModelMetadata, ModelStateDictionary } from "../../Microsoft.AspNetCore.Mvc.ModelBinding/internal/index.js";
import type { ActionContext } from "../../Microsoft.AspNetCore.Mvc/internal/index.js";
import * as System_Collections_Generic_Internal from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import type { ICollection_1, IDictionary_2, IEnumerable_1, IEnumerator_1, IList_1, IReadOnlyCollection_1, IReadOnlyDictionary_2, IReadOnlyList_1, KeyValuePair_2 } from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import * as System_Collections_Internal from "@tsonic/dotnet/System.Collections/internal/index.js";
import type { IEnumerable } from "@tsonic/dotnet/System.Collections/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Attribute, Boolean as ClrBoolean, Func_1, IDisposable, Int32, Nullable_1, Object as ClrObject, String as ClrString, Type, ValueType, Void } from "@tsonic/dotnet/System/internal/index.js";

export interface IClientModelValidator$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Mvc_ModelBinding_Validation_IClientModelValidator: never;

    AddValidation(context: ClientModelValidationContext): void;
}


export type IClientModelValidator = IClientModelValidator$instance;

export interface IClientModelValidatorProvider$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Mvc_ModelBinding_Validation_IClientModelValidatorProvider: never;

    CreateValidators(context: ClientValidatorProviderContext): void;
}


export type IClientModelValidatorProvider = IClientModelValidatorProvider$instance;

export interface IMetadataBasedModelValidatorProvider$instance extends IModelValidatorProvider {
    readonly __tsonic_iface_Microsoft_AspNetCore_Mvc_ModelBinding_Validation_IMetadataBasedModelValidatorProvider: never;

    CreateValidators(context: ModelValidatorProviderContext): void;
    HasValidators(modelType: Type, validatorMetadata: IList_1<unknown>): boolean;
}


export interface IMetadataBasedModelValidatorProvider$instance extends IModelValidatorProvider$instance {}

export type IMetadataBasedModelValidatorProvider = IMetadataBasedModelValidatorProvider$instance;

export interface IModelValidator$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Mvc_ModelBinding_Validation_IModelValidator: never;

    Validate(context: ModelValidationContext): IEnumerable_1<ModelValidationResult>;
}


export type IModelValidator = IModelValidator$instance;

export interface IModelValidatorProvider$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Mvc_ModelBinding_Validation_IModelValidatorProvider: never;

    CreateValidators(context: ModelValidatorProviderContext): void;
}


export type IModelValidatorProvider = IModelValidatorProvider$instance;

export interface IObjectModelValidator$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Mvc_ModelBinding_Validation_IObjectModelValidator: never;

    Validate(actionContext: ActionContext, validationState: ValidationStateDictionary | null, prefix: string, model: unknown | null): void;
}


export type IObjectModelValidator = IObjectModelValidator$instance;

export interface IPropertyValidationFilter$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Mvc_ModelBinding_Validation_IPropertyValidationFilter: never;

    ShouldValidateEntry(entry: ValidationEntry, parentEntry: ValidationEntry): boolean;
}


export type IPropertyValidationFilter = IPropertyValidationFilter$instance;

export interface IValidationStrategy$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Mvc_ModelBinding_Validation_IValidationStrategy: never;

    GetChildren(metadata: ModelMetadata, key: string, model: unknown): IEnumerator_1<ValidationEntry>;
}


export type IValidationStrategy = IValidationStrategy$instance;

export interface ValidationEntry$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Mvc_ModelBinding_Validation_ValidationEntry: never;

    readonly Key: string;
    readonly Metadata: ModelMetadata;
    readonly Model: unknown | null;
}


export const ValidationEntry: {
    new(metadata: ModelMetadata, key: string, model: unknown | null): ValidationEntry;
    new(metadata: ModelMetadata, key: string, modelAccessor: Func_1<unknown | null>): ValidationEntry;
};


export type ValidationEntry = ValidationEntry$instance;

export interface ClientModelValidationContext$instance extends ModelValidationContextBase {
    readonly __tsonic_type_Microsoft_AspNetCore_Mvc_ModelBinding_Validation_ClientModelValidationContext: never;

    readonly Attributes: IDictionary_2<System_Internal.String, System_Internal.String>;
}


export const ClientModelValidationContext: {
    new(actionContext: ActionContext, metadata: ModelMetadata, metadataProvider: IModelMetadataProvider, attributes: IDictionary_2<System_Internal.String, System_Internal.String>): ClientModelValidationContext;
};


export type ClientModelValidationContext = ClientModelValidationContext$instance;

export interface ClientValidatorCache$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Mvc_ModelBinding_Validation_ClientValidatorCache: never;

    GetValidators(metadata: ModelMetadata, validatorProvider: IClientModelValidatorProvider): IReadOnlyList_1<IClientModelValidator>;
}


export const ClientValidatorCache: {
    new(): ClientValidatorCache;
};


export type ClientValidatorCache = ClientValidatorCache$instance;

export interface ClientValidatorItem$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Mvc_ModelBinding_Validation_ClientValidatorItem: never;

    IsReusable: boolean;
    get Validator(): IClientModelValidator | null;
    set Validator(value: IClientModelValidator | null);
    readonly ValidatorMetadata: unknown | null;
}


export const ClientValidatorItem: {
    new(): ClientValidatorItem;
    new(validatorMetadata: unknown | null): ClientValidatorItem;
};


export type ClientValidatorItem = ClientValidatorItem$instance;

export interface ClientValidatorProviderContext$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Mvc_ModelBinding_Validation_ClientValidatorProviderContext: never;

    readonly ModelMetadata: ModelMetadata;
    readonly Results: IList_1<ClientValidatorItem>;
    readonly ValidatorMetadata: IReadOnlyList_1<unknown>;
}


export const ClientValidatorProviderContext: {
    new(modelMetadata: ModelMetadata, items: IList_1<ClientValidatorItem>): ClientValidatorProviderContext;
};


export type ClientValidatorProviderContext = ClientValidatorProviderContext$instance;

export interface CompositeClientModelValidatorProvider$instance extends IClientModelValidatorProvider$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Mvc_ModelBinding_Validation_CompositeClientModelValidatorProvider: never;

    readonly __tsonic_iface_Microsoft_AspNetCore_Mvc_ModelBinding_Validation_IClientModelValidatorProvider: never;

    readonly ValidatorProviders: IReadOnlyList_1<IClientModelValidatorProvider>;
    CreateValidators(context: ClientValidatorProviderContext): void;
}


export const CompositeClientModelValidatorProvider: {
    new(providers: IEnumerable_1<IClientModelValidatorProvider>): CompositeClientModelValidatorProvider;
};


export interface __CompositeClientModelValidatorProvider$views {
    As_IClientModelValidatorProvider(): IClientModelValidatorProvider$instance;
}

export type CompositeClientModelValidatorProvider = CompositeClientModelValidatorProvider$instance & __CompositeClientModelValidatorProvider$views;


export interface CompositeModelValidatorProvider$instance extends IModelValidatorProvider$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Mvc_ModelBinding_Validation_CompositeModelValidatorProvider: never;

    readonly __tsonic_iface_Microsoft_AspNetCore_Mvc_ModelBinding_Validation_IModelValidatorProvider: never;

    readonly ValidatorProviders: IList_1<IModelValidatorProvider>;
    CreateValidators(context: ModelValidatorProviderContext): void;
}


export const CompositeModelValidatorProvider: {
    new(providers: IList_1<IModelValidatorProvider>): CompositeModelValidatorProvider;
};


export interface __CompositeModelValidatorProvider$views {
    As_IModelValidatorProvider(): IModelValidatorProvider$instance;
}

export type CompositeModelValidatorProvider = CompositeModelValidatorProvider$instance & __CompositeModelValidatorProvider$views;


export interface ModelValidationContext$instance extends ModelValidationContextBase {
    readonly __tsonic_type_Microsoft_AspNetCore_Mvc_ModelBinding_Validation_ModelValidationContext: never;

    readonly Container: unknown | null;
    readonly Model: unknown | null;
}


export const ModelValidationContext: {
    new(actionContext: ActionContext, modelMetadata: ModelMetadata, metadataProvider: IModelMetadataProvider, container: unknown | null, model: unknown | null): ModelValidationContext;
};


export type ModelValidationContext = ModelValidationContext$instance;

export interface ModelValidationContextBase$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Mvc_ModelBinding_Validation_ModelValidationContextBase: never;

    readonly ActionContext: ActionContext;
    readonly MetadataProvider: IModelMetadataProvider;
    readonly ModelMetadata: ModelMetadata;
}


export const ModelValidationContextBase: {
    new(actionContext: ActionContext, modelMetadata: ModelMetadata, metadataProvider: IModelMetadataProvider): ModelValidationContextBase;
};


export type ModelValidationContextBase = ModelValidationContextBase$instance;

export interface ModelValidationResult$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Mvc_ModelBinding_Validation_ModelValidationResult: never;

    readonly MemberName: string;
    readonly Message: string;
}


export const ModelValidationResult: {
    new(memberName: string | null, message: string | null): ModelValidationResult;
};


export type ModelValidationResult = ModelValidationResult$instance;

export interface ModelValidatorProviderContext$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Mvc_ModelBinding_Validation_ModelValidatorProviderContext: never;

    ModelMetadata: ModelMetadata;
    readonly Results: IList_1<ValidatorItem>;
    readonly ValidatorMetadata: IReadOnlyList_1<unknown>;
}


export const ModelValidatorProviderContext: {
    new(modelMetadata: ModelMetadata, items: IList_1<ValidatorItem>): ModelValidatorProviderContext;
};


export type ModelValidatorProviderContext = ModelValidatorProviderContext$instance;

export interface ValidateNeverAttribute$instance extends Attribute, IPropertyValidationFilter$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Mvc_ModelBinding_Validation_ValidateNeverAttribute: never;

    readonly __tsonic_iface_Microsoft_AspNetCore_Mvc_ModelBinding_Validation_IPropertyValidationFilter: never;

    ShouldValidateEntry(entry: ValidationEntry, parentEntry: ValidationEntry): boolean;
}


export const ValidateNeverAttribute: {
    new(): ValidateNeverAttribute;
};


export interface __ValidateNeverAttribute$views {
    As_IPropertyValidationFilter(): IPropertyValidationFilter$instance;
}

export type ValidateNeverAttribute = ValidateNeverAttribute$instance & __ValidateNeverAttribute$views;


export interface ValidationStateDictionary$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Mvc_ModelBinding_Validation_ValidationStateDictionary: never;

    readonly __tsonic_iface_System_Collections_Generic_ICollection_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IDictionary_2: never;
    readonly __tsonic_iface_System_Collections_Generic_IEnumerable_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyCollection_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyDictionary_2: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;

    readonly Count: int;
    readonly IsReadOnly: boolean;
    get Item(): ValidationStateEntry | null;
    set Item(value: ValidationStateEntry | null);
    readonly Keys: ICollection_1<unknown>;
    readonly Values: ICollection_1<ValidationStateEntry>;
    Add(item: KeyValuePair_2<unknown, ValidationStateEntry>): void;
    Add(key: unknown, value: ValidationStateEntry): void;
    Clear(): void;
    Contains(item: KeyValuePair_2<unknown, ValidationStateEntry>): boolean;
    ContainsKey(key: unknown): boolean;
    CopyTo(array: KeyValuePair_2<unknown, ValidationStateEntry>[], arrayIndex: int): void;
    GetEnumerator(): IEnumerator_1<KeyValuePair_2<unknown, ValidationStateEntry>>;
    Remove(item: KeyValuePair_2<unknown, ValidationStateEntry>): boolean;
    Remove(key: unknown): boolean;
    TryGetValue(key: unknown, value: ValidationStateEntry): boolean;
}


export const ValidationStateDictionary: {
    new(): ValidationStateDictionary;
};


export type ValidationStateDictionary = ValidationStateDictionary$instance;

export interface ValidationStateEntry$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Mvc_ModelBinding_Validation_ValidationStateEntry: never;

    Key: string;
    Metadata: ModelMetadata;
    Strategy: IValidationStrategy;
    SuppressValidation: boolean;
}


export const ValidationStateEntry: {
    new(): ValidationStateEntry;
};


export type ValidationStateEntry = ValidationStateEntry$instance;

export interface ValidationVisitor$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Mvc_ModelBinding_Validation_ValidationVisitor: never;

    get MaxValidationDepth(): Nullable_1<System_Internal.Int32>;
    set MaxValidationDepth(value: Nullable_1<System_Internal.Int32> | int);
    ValidateComplexTypesIfChildValidationFails: boolean;
    GetValidationEntry(model: unknown | null): ValidationStateEntry | null;
    SuppressValidation(key: string): void;
    Validate(metadata: ModelMetadata, key: string, model: unknown): boolean;
    Validate(metadata: ModelMetadata | null, key: string | null, model: unknown | null, alwaysValidateAtTopLevel: boolean): boolean;
    Validate(metadata: ModelMetadata | null, key: string | null, model: unknown | null, alwaysValidateAtTopLevel: boolean, container: unknown | null): boolean;
    ValidateNode(): boolean;
    Visit(metadata: ModelMetadata, key: string | null, model: unknown | null): boolean;
    VisitChildren(strategy: IValidationStrategy): boolean;
    VisitComplexType(defaultStrategy: IValidationStrategy): boolean;
    VisitSimpleType(): boolean;
}


export const ValidationVisitor: {
    new(actionContext: ActionContext, validatorProvider: IModelValidatorProvider, validatorCache: ValidatorCache, metadataProvider: IModelMetadataProvider, validationState: ValidationStateDictionary | null): ValidationVisitor;
};


export type ValidationVisitor = ValidationVisitor$instance;

export interface ValidationVisitor_StateManager$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Mvc_ModelBinding_Validation_ValidationVisitor_StateManager: never;

    readonly __tsonic_iface_System_IDisposable: never;

    Dispose(): void;
}


export const ValidationVisitor_StateManager: {
    new(visitor: ValidationVisitor, newModel: unknown | null): ValidationVisitor_StateManager;
    Recurse(visitor: ValidationVisitor, key: string, metadata: ModelMetadata, model: unknown | null, strategy: IValidationStrategy): ValidationVisitor_StateManager;
};


export type ValidationVisitor_StateManager = ValidationVisitor_StateManager$instance;

export interface ValidatorCache$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Mvc_ModelBinding_Validation_ValidatorCache: never;

    GetValidators(metadata: ModelMetadata, validatorProvider: IModelValidatorProvider): IReadOnlyList_1<IModelValidator>;
}


export const ValidatorCache: {
    new(): ValidatorCache;
};


export type ValidatorCache = ValidatorCache$instance;

export interface ValidatorItem$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Mvc_ModelBinding_Validation_ValidatorItem: never;

    IsReusable: boolean;
    get Validator(): IModelValidator | null;
    set Validator(value: IModelValidator | null);
    readonly ValidatorMetadata: unknown;
}


export const ValidatorItem: {
    new(): ValidatorItem;
    new(validatorMetadata: unknown): ValidatorItem;
};


export type ValidatorItem = ValidatorItem$instance;

export abstract class ModelValidatorProviderExtensions$instance {
    static RemoveType(list: IList_1<IModelValidatorProvider>, type: Type): void;
    static RemoveType<TModelValidatorProvider extends unknown & IModelValidatorProvider>(list: IList_1<IModelValidatorProvider>): void;
}


export type ModelValidatorProviderExtensions = ModelValidatorProviderExtensions$instance;

