// Generated by tsbindgen - Architecture
// Namespace: Microsoft.AspNetCore.StaticFiles.Infrastructure
// Assembly: Microsoft.AspNetCore.StaticFiles

// Core type aliases from @tsonic/core
import type { JsValue, fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Import types from other namespaces
import type { PathString } from "../../Microsoft.AspNetCore.Http/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Boolean as ClrBoolean, Object as ClrObject } from "@tsonic/dotnet/System/internal/index.js";
import type { IFileProvider } from "@tsonic/microsoft-extensions/Microsoft.Extensions.FileProviders/internal/index.js";

export interface SharedOptions$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_StaticFiles_Infrastructure_SharedOptions: never;

    get FileProvider(): IFileProvider | null;
    set FileProvider(value: IFileProvider | null);
    RedirectToAppendTrailingSlash: boolean;
    RequestPath: PathString;
}


export const SharedOptions: {
    new(): SharedOptions;
};


export type SharedOptions = SharedOptions$instance;

export interface SharedOptionsBase$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_StaticFiles_Infrastructure_SharedOptionsBase: never;

    get FileProvider(): IFileProvider | null;
    set FileProvider(value: IFileProvider | null);
    RedirectToAppendTrailingSlash: boolean;
    RequestPath: PathString;
}


export const SharedOptionsBase: (abstract new(sharedOptions: SharedOptions) => SharedOptionsBase) & {
};


export type SharedOptionsBase = SharedOptionsBase$instance;

