// Generated by tsbindgen - Architecture
// Namespace: Microsoft.AspNetCore.Mvc.ViewFeatures.Buffers
// Assembly: Microsoft.AspNetCore.Mvc.ViewFeatures

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { IHtmlContent } from "../../Microsoft.AspNetCore.Html/internal/index.js";
import type { TextWriter } from "@tsonic/dotnet/System.IO.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Int32, Object as ClrObject, String as ClrString, ValueType, Void } from "@tsonic/dotnet/System.js";

export interface IViewBufferScope$instance {
    CreateWriter(writer: TextWriter): TextWriter;
    GetPage(pageSize: int): ViewBufferValue[];
    ReturnSegment(segment: ViewBufferValue[]): void;
}


export type IViewBufferScope = IViewBufferScope$instance;

export interface ViewBufferValue$instance {
    readonly Value: unknown;
}


export const ViewBufferValue: {
    new(value: string): ViewBufferValue;
    new(content: IHtmlContent): ViewBufferValue;
};


export type ViewBufferValue = ViewBufferValue$instance;

