// Generated by dotnet-bindgen - Architecture
// Namespace: Microsoft.AspNetCore.Components.Web
// Assembly: Microsoft.AspNetCore.Components.Web

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Import types from other namespaces
import type { RenderTreeBuilder } from "../../Microsoft.AspNetCore.Components.Rendering/internal/index.js";
import type { HtmlRootComponent } from "../../Microsoft.AspNetCore.Components.Web.HtmlRendering/internal/index.js";
import * as Microsoft_AspNetCore_Components_Internal from "../../Microsoft.AspNetCore.Components/internal/index.js";
import type { ComponentBase, Dispatcher, ErrorBoundaryBase, EventCallback_1, EventCallbackFactory, EventCallbackWorkItem, IComponent, IComponentRenderMode, IHandleAfterRender, IHandleEvent, ParameterView, RendererInfo, RenderFragment, RenderFragment_1, RenderHandle, ResourceAssetCollection } from "../../Microsoft.AspNetCore.Components/internal/index.js";
import type { Task, Task_1, ValueTask } from "@tsonic/dotnet/System.Threading.Tasks/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Action, Action_1, Boolean as ClrBoolean, Double, EventArgs, Exception, Func_1, Func_2, IAsyncDisposable, IDisposable, Int32, Int64, IServiceProvider, Object as ClrObject, Single, String as ClrString, Type, Void } from "@tsonic/dotnet/System/internal/index.js";
import type { ILoggerFactory } from "@tsonic/microsoft-extensions/Microsoft.Extensions.Logging/internal/index.js";

export interface IErrorBoundaryLogger$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Components_Web_IErrorBoundaryLogger: never;

    LogErrorAsync(exception: Exception): ValueTask;
}


export type IErrorBoundaryLogger = IErrorBoundaryLogger$instance;

export interface IJSComponentConfiguration$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Components_Web_IJSComponentConfiguration: never;

    readonly JSComponents: JSComponentConfigurationStore;
}


export type IJSComponentConfiguration = IJSComponentConfiguration$instance;

export interface ClipboardEventArgs$instance extends EventArgs {
    readonly __tsonic_type_Microsoft_AspNetCore_Components_Web_ClipboardEventArgs: never;

    Type: string;
}


export const ClipboardEventArgs: {
    new(): ClipboardEventArgs;
};


export type ClipboardEventArgs = ClipboardEventArgs$instance;

export interface DataTransfer$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Components_Web_DataTransfer: never;

    DropEffect: string;
    get EffectAllowed(): string | null;
    set EffectAllowed(value: string | null);
    Files: string[];
    Items: DataTransferItem[];
    Types: string[];
}


export const DataTransfer: {
    new(): DataTransfer;
};


export type DataTransfer = DataTransfer$instance;

export interface DataTransferItem$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Components_Web_DataTransferItem: never;

    Kind: string;
    Type: string;
}


export const DataTransferItem: {
    new(): DataTransferItem;
};


export type DataTransferItem = DataTransferItem$instance;

export interface DragEventArgs$instance extends MouseEventArgs {
    readonly __tsonic_type_Microsoft_AspNetCore_Components_Web_DragEventArgs: never;

    DataTransfer: DataTransfer;
}


export const DragEventArgs: {
    new(): DragEventArgs;
};


export type DragEventArgs = DragEventArgs$instance;

export interface ErrorBoundary$instance extends ErrorBoundaryBase, Microsoft_AspNetCore_Components_Internal.IComponent$instance, Microsoft_AspNetCore_Components_Internal.IHandleEvent$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Components_Web_ErrorBoundary: never;

    readonly __tsonic_iface_Microsoft_AspNetCore_Components_IComponent: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Components_IErrorBoundary: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Components_IHandleAfterRender: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Components_IHandleEvent: never;

    BuildRenderTree(builder: RenderTreeBuilder): void;
    OnErrorAsync(exception: Exception): Task;
}


export const ErrorBoundary: {
    new(): ErrorBoundary;
};


export interface __ErrorBoundary$views {
    As_IComponent(): Microsoft_AspNetCore_Components_Internal.IComponent$instance;
    As_IHandleAfterRender(): Microsoft_AspNetCore_Components_Internal.IHandleAfterRender$instance;
    As_IHandleEvent(): Microsoft_AspNetCore_Components_Internal.IHandleEvent$instance;
}

export type ErrorBoundary = ErrorBoundary$instance & __ErrorBoundary$views;


export interface ErrorEventArgs$instance extends EventArgs {
    readonly __tsonic_type_Microsoft_AspNetCore_Components_Web_ErrorEventArgs: never;

    Colno: int;
    get Filename(): string | null;
    set Filename(value: string | null);
    Lineno: int;
    get Message(): string | null;
    set Message(value: string | null);
    get Type(): string | null;
    set Type(value: string | null);
}


export const ErrorEventArgs: {
    new(): ErrorEventArgs;
};


export type ErrorEventArgs = ErrorEventArgs$instance;

export interface FocusEventArgs$instance extends EventArgs {
    readonly __tsonic_type_Microsoft_AspNetCore_Components_Web_FocusEventArgs: never;

    get Type(): string | null;
    set Type(value: string | null);
}


export const FocusEventArgs: {
    new(): FocusEventArgs;
};


export type FocusEventArgs = FocusEventArgs$instance;

export interface HeadContent$instance extends ComponentBase, Microsoft_AspNetCore_Components_Internal.IComponent$instance, Microsoft_AspNetCore_Components_Internal.IHandleEvent$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Components_Web_HeadContent: never;

    readonly __tsonic_iface_Microsoft_AspNetCore_Components_IComponent: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Components_IHandleAfterRender: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Components_IHandleEvent: never;

    get ChildContent(): RenderFragment | null;
    set ChildContent(value: RenderFragment | null);
    BuildRenderTree(builder: RenderTreeBuilder): void;
}


export const HeadContent: {
    new(): HeadContent;
};


export interface __HeadContent$views {
    As_IComponent(): Microsoft_AspNetCore_Components_Internal.IComponent$instance;
    As_IHandleAfterRender(): Microsoft_AspNetCore_Components_Internal.IHandleAfterRender$instance;
    As_IHandleEvent(): Microsoft_AspNetCore_Components_Internal.IHandleEvent$instance;
}

export type HeadContent = HeadContent$instance & __HeadContent$views;


export interface HeadOutlet$instance extends ComponentBase, Microsoft_AspNetCore_Components_Internal.IComponent$instance, Microsoft_AspNetCore_Components_Internal.IHandleEvent$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Components_Web_HeadOutlet: never;

    readonly __tsonic_iface_Microsoft_AspNetCore_Components_IComponent: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Components_IHandleAfterRender: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Components_IHandleEvent: never;

    BuildRenderTree(builder: RenderTreeBuilder): void;
    OnAfterRenderAsync(firstRender: boolean): Task;
}


export const HeadOutlet: {
    new(): HeadOutlet;
};


export interface __HeadOutlet$views {
    As_IComponent(): Microsoft_AspNetCore_Components_Internal.IComponent$instance;
    As_IHandleAfterRender(): Microsoft_AspNetCore_Components_Internal.IHandleAfterRender$instance;
    As_IHandleEvent(): Microsoft_AspNetCore_Components_Internal.IHandleEvent$instance;
}

export type HeadOutlet = HeadOutlet$instance & __HeadOutlet$views;


export interface HtmlRenderer$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Components_Web_HtmlRenderer: never;

    readonly __tsonic_iface_System_IAsyncDisposable: never;
    readonly __tsonic_iface_System_IDisposable: never;

    readonly Dispatcher: Dispatcher;
    BeginRenderingComponent<TComponent extends unknown & IComponent>(): HtmlRootComponent;
    BeginRenderingComponent<TComponent extends unknown & IComponent>(parameters: ParameterView): HtmlRootComponent;
    BeginRenderingComponent(componentType: Type): HtmlRootComponent;
    BeginRenderingComponent(componentType: Type, parameters: ParameterView): HtmlRootComponent;
    Dispose(): void;
    DisposeAsync(): ValueTask;
    RenderComponentAsync<TComponent extends unknown & IComponent>(): Task_1<HtmlRootComponent>;
    RenderComponentAsync(componentType: Type): Task_1<HtmlRootComponent>;
    RenderComponentAsync<TComponent extends unknown & IComponent>(parameters: ParameterView): Task_1<HtmlRootComponent>;
    RenderComponentAsync(componentType: Type, parameters: ParameterView): Task_1<HtmlRootComponent>;
}


export const HtmlRenderer: {
    new(services: IServiceProvider, loggerFactory: ILoggerFactory): HtmlRenderer;
};


export type HtmlRenderer = HtmlRenderer$instance;

export interface InteractiveAutoRenderMode$instance extends IComponentRenderMode {
    readonly __tsonic_type_Microsoft_AspNetCore_Components_Web_InteractiveAutoRenderMode: never;

    readonly __tsonic_iface_Microsoft_AspNetCore_Components_IComponentRenderMode: never;

    readonly Prerender: boolean;
}


export const InteractiveAutoRenderMode: {
    new(): InteractiveAutoRenderMode;
    new(prerender: boolean): InteractiveAutoRenderMode;
};


export type InteractiveAutoRenderMode = InteractiveAutoRenderMode$instance;

export interface InteractiveServerRenderMode$instance extends IComponentRenderMode {
    readonly __tsonic_type_Microsoft_AspNetCore_Components_Web_InteractiveServerRenderMode: never;

    readonly __tsonic_iface_Microsoft_AspNetCore_Components_IComponentRenderMode: never;

    readonly Prerender: boolean;
}


export const InteractiveServerRenderMode: {
    new(): InteractiveServerRenderMode;
    new(prerender: boolean): InteractiveServerRenderMode;
};


export type InteractiveServerRenderMode = InteractiveServerRenderMode$instance;

export interface InteractiveWebAssemblyRenderMode$instance extends IComponentRenderMode {
    readonly __tsonic_type_Microsoft_AspNetCore_Components_Web_InteractiveWebAssemblyRenderMode: never;

    readonly __tsonic_iface_Microsoft_AspNetCore_Components_IComponentRenderMode: never;

    readonly Prerender: boolean;
}


export const InteractiveWebAssemblyRenderMode: {
    new(): InteractiveWebAssemblyRenderMode;
    new(prerender: boolean): InteractiveWebAssemblyRenderMode;
};


export type InteractiveWebAssemblyRenderMode = InteractiveWebAssemblyRenderMode$instance;

export interface JSComponentConfigurationStore$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Components_Web_JSComponentConfigurationStore: never;

}


export const JSComponentConfigurationStore: {
    new(): JSComponentConfigurationStore;
};


export type JSComponentConfigurationStore = JSComponentConfigurationStore$instance;

export interface KeyboardEventArgs$instance extends EventArgs {
    readonly __tsonic_type_Microsoft_AspNetCore_Components_Web_KeyboardEventArgs: never;

    AltKey: boolean;
    Code: string;
    CtrlKey: boolean;
    IsComposing: boolean;
    Key: string;
    Location: float;
    MetaKey: boolean;
    Repeat: boolean;
    ShiftKey: boolean;
    Type: string;
}


export const KeyboardEventArgs: {
    new(): KeyboardEventArgs;
};


export type KeyboardEventArgs = KeyboardEventArgs$instance;

export interface MouseEventArgs$instance extends EventArgs {
    readonly __tsonic_type_Microsoft_AspNetCore_Components_Web_MouseEventArgs: never;

    AltKey: boolean;
    Button: long;
    Buttons: long;
    ClientX: double;
    ClientY: double;
    CtrlKey: boolean;
    Detail: long;
    MetaKey: boolean;
    MovementX: double;
    MovementY: double;
    OffsetX: double;
    OffsetY: double;
    PageX: double;
    PageY: double;
    ScreenX: double;
    ScreenY: double;
    ShiftKey: boolean;
    Type: string;
}


export const MouseEventArgs: {
    new(): MouseEventArgs;
};


export type MouseEventArgs = MouseEventArgs$instance;

export interface PageTitle$instance extends ComponentBase, Microsoft_AspNetCore_Components_Internal.IComponent$instance, Microsoft_AspNetCore_Components_Internal.IHandleEvent$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Components_Web_PageTitle: never;

    readonly __tsonic_iface_Microsoft_AspNetCore_Components_IComponent: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Components_IHandleAfterRender: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Components_IHandleEvent: never;

    get ChildContent(): RenderFragment | null;
    set ChildContent(value: RenderFragment | null);
    BuildRenderTree(builder: RenderTreeBuilder): void;
}


export const PageTitle: {
    new(): PageTitle;
};


export interface __PageTitle$views {
    As_IComponent(): Microsoft_AspNetCore_Components_Internal.IComponent$instance;
    As_IHandleAfterRender(): Microsoft_AspNetCore_Components_Internal.IHandleAfterRender$instance;
    As_IHandleEvent(): Microsoft_AspNetCore_Components_Internal.IHandleEvent$instance;
}

export type PageTitle = PageTitle$instance & __PageTitle$views;


export interface PointerEventArgs$instance extends MouseEventArgs {
    readonly __tsonic_type_Microsoft_AspNetCore_Components_Web_PointerEventArgs: never;

    Height: float;
    IsPrimary: boolean;
    PointerId: long;
    PointerType: string;
    Pressure: float;
    TiltX: float;
    TiltY: float;
    Width: float;
}


export const PointerEventArgs: {
    new(): PointerEventArgs;
};


export type PointerEventArgs = PointerEventArgs$instance;

export interface ProgressEventArgs$instance extends EventArgs {
    readonly __tsonic_type_Microsoft_AspNetCore_Components_Web_ProgressEventArgs: never;

    LengthComputable: boolean;
    Loaded: long;
    Total: long;
    Type: string;
}


export const ProgressEventArgs: {
    new(): ProgressEventArgs;
};


export type ProgressEventArgs = ProgressEventArgs$instance;

export interface TouchEventArgs$instance extends EventArgs {
    readonly __tsonic_type_Microsoft_AspNetCore_Components_Web_TouchEventArgs: never;

    AltKey: boolean;
    ChangedTouches: TouchPoint[];
    CtrlKey: boolean;
    Detail: long;
    MetaKey: boolean;
    ShiftKey: boolean;
    TargetTouches: TouchPoint[];
    Touches: TouchPoint[];
    Type: string;
}


export const TouchEventArgs: {
    new(): TouchEventArgs;
};


export type TouchEventArgs = TouchEventArgs$instance;

export interface TouchPoint$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Components_Web_TouchPoint: never;

    ClientX: double;
    ClientY: double;
    Identifier: long;
    PageX: double;
    PageY: double;
    ScreenX: double;
    ScreenY: double;
}


export const TouchPoint: {
    new(): TouchPoint;
};


export type TouchPoint = TouchPoint$instance;

export interface WheelEventArgs$instance extends MouseEventArgs {
    readonly __tsonic_type_Microsoft_AspNetCore_Components_Web_WheelEventArgs: never;

    DeltaMode: long;
    DeltaX: double;
    DeltaY: double;
    DeltaZ: double;
}


export const WheelEventArgs: {
    new(): WheelEventArgs;
};


export type WheelEventArgs = WheelEventArgs$instance;

export abstract class BindAttributes$instance {
}


export type BindAttributes = BindAttributes$instance;

export abstract class EventHandlers$instance {
}


export type EventHandlers = EventHandlers$instance;

export abstract class JSComponentConfigurationExtensions$instance {
    static RegisterForJavaScript<TComponent extends unknown & IComponent>(configuration: IJSComponentConfiguration, identifier: string, javaScriptInitializer: string): void;
    static RegisterForJavaScript<TComponent extends unknown & IComponent>(configuration: IJSComponentConfiguration, identifier: string): void;
    static RegisterForJavaScript(configuration: IJSComponentConfiguration, componentType: Type, identifier: string, javaScriptInitializer: string): void;
    static RegisterForJavaScript(configuration: IJSComponentConfiguration, componentType: Type, identifier: string): void;
}


export type JSComponentConfigurationExtensions = JSComponentConfigurationExtensions$instance;

export abstract class RenderMode$instance {
    static readonly InteractiveServer: InteractiveServerRenderMode;
    static readonly InteractiveWebAssembly: InteractiveWebAssemblyRenderMode;
    static readonly InteractiveAuto: InteractiveAutoRenderMode;
}


export type RenderMode = RenderMode$instance;

export abstract class WebEventCallbackFactoryEventArgsExtensions$instance {
    static Create(factory: EventCallbackFactory, receiver: unknown, callback: Action_1<ClipboardEventArgs>): EventCallback_1<ClipboardEventArgs>;
    static Create(factory: EventCallbackFactory, receiver: unknown, callback: Action_1<DragEventArgs>): EventCallback_1<DragEventArgs>;
    static Create(factory: EventCallbackFactory, receiver: unknown, callback: Action_1<ErrorEventArgs>): EventCallback_1<ErrorEventArgs>;
    static Create(factory: EventCallbackFactory, receiver: unknown, callback: Action_1<FocusEventArgs>): EventCallback_1<FocusEventArgs>;
    static Create(factory: EventCallbackFactory, receiver: unknown, callback: Action_1<KeyboardEventArgs>): EventCallback_1<KeyboardEventArgs>;
    static Create(factory: EventCallbackFactory, receiver: unknown, callback: Action_1<MouseEventArgs>): EventCallback_1<MouseEventArgs>;
    static Create(factory: EventCallbackFactory, receiver: unknown, callback: Action_1<PointerEventArgs>): EventCallback_1<PointerEventArgs>;
    static Create(factory: EventCallbackFactory, receiver: unknown, callback: Action_1<ProgressEventArgs>): EventCallback_1<ProgressEventArgs>;
    static Create(factory: EventCallbackFactory, receiver: unknown, callback: Action_1<TouchEventArgs>): EventCallback_1<TouchEventArgs>;
    static Create(factory: EventCallbackFactory, receiver: unknown, callback: Action_1<WheelEventArgs>): EventCallback_1<WheelEventArgs>;
    static Create(factory: EventCallbackFactory, receiver: unknown, callback: Func_2<ClipboardEventArgs, Task>): EventCallback_1<ClipboardEventArgs>;
    static Create(factory: EventCallbackFactory, receiver: unknown, callback: Func_2<DragEventArgs, Task>): EventCallback_1<DragEventArgs>;
    static Create(factory: EventCallbackFactory, receiver: unknown, callback: Func_2<ErrorEventArgs, Task>): EventCallback_1<ErrorEventArgs>;
    static Create(factory: EventCallbackFactory, receiver: unknown, callback: Func_2<FocusEventArgs, Task>): EventCallback_1<FocusEventArgs>;
    static Create(factory: EventCallbackFactory, receiver: unknown, callback: Func_2<KeyboardEventArgs, Task>): EventCallback_1<KeyboardEventArgs>;
    static Create(factory: EventCallbackFactory, receiver: unknown, callback: Func_2<MouseEventArgs, Task>): EventCallback_1<MouseEventArgs>;
    static Create(factory: EventCallbackFactory, receiver: unknown, callback: Func_2<PointerEventArgs, Task>): EventCallback_1<PointerEventArgs>;
    static Create(factory: EventCallbackFactory, receiver: unknown, callback: Func_2<ProgressEventArgs, Task>): EventCallback_1<ProgressEventArgs>;
    static Create(factory: EventCallbackFactory, receiver: unknown, callback: Func_2<TouchEventArgs, Task>): EventCallback_1<TouchEventArgs>;
    static Create(factory: EventCallbackFactory, receiver: unknown, callback: Func_2<WheelEventArgs, Task>): EventCallback_1<WheelEventArgs>;
}


export type WebEventCallbackFactoryEventArgsExtensions = WebEventCallbackFactoryEventArgsExtensions$instance;

export abstract class WebRenderTreeBuilderExtensions$instance {
    static AddEventPreventDefaultAttribute(builder: RenderTreeBuilder, sequence: int, eventName: string, value: boolean): void;
    static AddEventStopPropagationAttribute(builder: RenderTreeBuilder, sequence: int, eventName: string, value: boolean): void;
}


export type WebRenderTreeBuilderExtensions = WebRenderTreeBuilderExtensions$instance;
