// Generated by tsbindgen - Architecture
// Namespace: Microsoft.AspNetCore.Mvc.Razor.Internal
// Assembly: Microsoft.AspNetCore.Mvc.Razor

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Attribute, Object as ClrObject } from "@tsonic/dotnet/System/internal/index.js";

export interface RazorInjectAttribute$instance extends Attribute {
    readonly __tsonic_type_Microsoft_AspNetCore_Mvc_Razor_Internal_RazorInjectAttribute: never;

    get Key(): unknown | undefined;
    set Key(value: unknown | undefined);
}


export const RazorInjectAttribute: {
    new(): RazorInjectAttribute;
};


export type RazorInjectAttribute = RazorInjectAttribute$instance;

