// Generated by tsbindgen - Architecture
// Namespace: Microsoft.AspNetCore.Server.Kestrel.Core.Features
// Assembly: Microsoft.AspNetCore.Server.Kestrel.Core

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { MinDataRate } from "../../Microsoft.AspNetCore.Server.Kestrel.Core/internal/index.js";
import type { Byte, Int32, ReadOnlyMemory, TimeSpan, Void } from "@tsonic/dotnet/System.js";
import type { SslStream } from "@tsonic/dotnet/System.Net.Security.js";

export interface IConnectionTimeoutFeature$instance {
    cancelTimeout(): void;
    setTimeout(timeSpan: TimeSpan): void;
}


export type IConnectionTimeoutFeature = IConnectionTimeoutFeature$instance;

export interface IDecrementConcurrentConnectionCountFeature$instance {
    releaseConnection(): void;
}


export type IDecrementConcurrentConnectionCountFeature = IDecrementConcurrentConnectionCountFeature$instance;

export interface IHttp2StreamIdFeature$instance {
    readonly streamId: int;
}


export type IHttp2StreamIdFeature = IHttp2StreamIdFeature$instance;

export interface IHttpMinRequestBodyDataRateFeature$instance {
    get minDataRate(): MinDataRate | undefined;
    set minDataRate(value: MinDataRate);
}


export type IHttpMinRequestBodyDataRateFeature = IHttpMinRequestBodyDataRateFeature$instance;

export interface IHttpMinResponseDataRateFeature$instance {
    get minDataRate(): MinDataRate | undefined;
    set minDataRate(value: MinDataRate);
}


export type IHttpMinResponseDataRateFeature = IHttpMinResponseDataRateFeature$instance;

export interface ISslStreamFeature$instance {
    readonly sslStream: SslStream;
}


export type ISslStreamFeature = ISslStreamFeature$instance;

export interface ITlsApplicationProtocolFeature$instance {
    readonly applicationProtocol: ReadOnlyMemory<System_Internal.Byte>;
}


export type ITlsApplicationProtocolFeature = ITlsApplicationProtocolFeature$instance;

