// Generated by tsbindgen - Architecture
// Namespace: Microsoft.AspNetCore.Routing.Tree
// Assembly: Microsoft.AspNetCore.Routing

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { RouteTemplate, TemplateBinder, TemplateMatcher } from "../../Microsoft.AspNetCore.Routing.Template/internal/index.js";
import * as Microsoft_AspNetCore_Routing_Internal from "../../Microsoft.AspNetCore.Routing/internal/index.js";
import type { IRouteConstraint, IRouter, RouteContext, RouteValueDictionary, VirtualPathContext, VirtualPathData } from "../../Microsoft.AspNetCore.Routing/internal/index.js";
import type { Dictionary, IDictionary, IList, List } from "@tsonic/dotnet/System.Collections.Generic.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Boolean as ClrBoolean, Decimal, Int32, Object as ClrObject, String as ClrString, Void } from "@tsonic/dotnet/System.js";
import type { Task } from "@tsonic/dotnet/System.Threading.Tasks.js";

export interface InboundMatch$instance {
    entry: InboundRouteEntry;
    templateMatcher: TemplateMatcher;
}


export const InboundMatch: {
    new(): InboundMatch;
};


export type InboundMatch = InboundMatch$instance;

export interface InboundRouteEntry$instance {
    constraints: IDictionary<System_Internal.String, IRouteConstraint>;
    defaults: RouteValueDictionary;
    handler: IRouter;
    order: int;
    precedence: decimal;
    get routeName(): string | undefined;
    set routeName(value: string);
    get routeTemplate(): RouteTemplate | undefined;
    set routeTemplate(value: RouteTemplate);
}


export const InboundRouteEntry: {
    new(): InboundRouteEntry;
};


export type InboundRouteEntry = InboundRouteEntry$instance;

export interface OutboundMatch$instance {
    entry: OutboundRouteEntry;
    templateBinder: TemplateBinder;
}


export const OutboundMatch: {
    new(): OutboundMatch;
};


export type OutboundMatch = OutboundMatch$instance;

export interface OutboundRouteEntry$instance {
    constraints: IDictionary<System_Internal.String, IRouteConstraint>;
    data: unknown;
    defaults: RouteValueDictionary;
    handler: IRouter;
    order: int;
    precedence: decimal;
    requiredLinkValues: RouteValueDictionary;
    get routeName(): string | undefined;
    set routeName(value: string);
    get routeTemplate(): RouteTemplate | undefined;
    set routeTemplate(value: RouteTemplate);
}


export const OutboundRouteEntry: {
    new(): OutboundRouteEntry;
};


export type OutboundRouteEntry = OutboundRouteEntry$instance;

export interface TreeRouteBuilder$instance {
    readonly inboundEntries: IList<InboundRouteEntry>;
    readonly outboundEntries: IList<OutboundRouteEntry>;
    build(): TreeRouter;
    build(version: int): TreeRouter;
    clear(): void;
    mapInbound(handler: IRouter, routeTemplate: RouteTemplate, routeName: string, order: int): InboundRouteEntry;
    mapOutbound(handler: IRouter, routeTemplate: RouteTemplate, requiredLinkValues: RouteValueDictionary, routeName: string, order: int): OutboundRouteEntry;
}


export const TreeRouteBuilder: {
    new(): TreeRouteBuilder;
};


export type TreeRouteBuilder = TreeRouteBuilder$instance;

export interface TreeRouter$instance {
    readonly version: int;
    getVirtualPath(context: VirtualPathContext): VirtualPathData | undefined;
    routeAsync(context: RouteContext): Task;
}


export const TreeRouter: {
    new(): TreeRouter;
    readonly routeGroupKey: string;
};


export interface __TreeRouter$views {
    As_IRouter(): Microsoft_AspNetCore_Routing_Internal.IRouter$instance;
}

export interface TreeRouter$instance extends Microsoft_AspNetCore_Routing_Internal.IRouter$instance {}

export type TreeRouter = TreeRouter$instance & __TreeRouter$views;


export interface UrlMatchingNode$instance {
    catchAlls: UrlMatchingNode;
    constrainedCatchAlls: UrlMatchingNode;
    constrainedParameters: UrlMatchingNode;
    readonly depth: int;
    isCatchAll: boolean;
    readonly literals: Dictionary<System_Internal.String, UrlMatchingNode>;
    readonly matches: List<InboundMatch>;
    parameters: UrlMatchingNode;
}


export const UrlMatchingNode: {
    new(length: int): UrlMatchingNode;
};


export type UrlMatchingNode = UrlMatchingNode$instance;

export interface UrlMatchingTree$instance {
    readonly order: int;
    readonly root: UrlMatchingNode;
}


export const UrlMatchingTree: {
    new(order: int): UrlMatchingTree;
};


export type UrlMatchingTree = UrlMatchingTree$instance;

