// Generated by tsbindgen - Architecture
// Namespace: Microsoft.AspNetCore.Routing
// Assembly: Microsoft.AspNetCore.Http.Abstractions, Microsoft.AspNetCore.Identity, Microsoft.AspNetCore.Mvc.Core, Microsoft.AspNetCore.Routing, Microsoft.AspNetCore.Routing.Abstractions

// Core type aliases from @tsonic/core
import type { JsValue, fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Import types from other namespaces
import * as Microsoft_AspNetCore_Builder_Internal from "../../Microsoft.AspNetCore.Builder/internal/index.js";
import type { EndpointBuilder, IApplicationBuilder, IEndpointConventionBuilder, RouteHandlerBuilder } from "../../Microsoft.AspNetCore.Builder/internal/index.js";
import * as Microsoft_AspNetCore_Http_Internal from "../../Microsoft.AspNetCore.Http/internal/index.js";
import type { Endpoint, EndpointFilterDelegate, EndpointFilterFactoryContext, EndpointMetadataCollection, FragmentString, HostString, HttpContext, HttpRequest, HttpResponse, PathString, RequestDelegate, RequestDelegateFactoryOptions, RequestDelegateMetadataResult, RequestDelegateResult } from "../../Microsoft.AspNetCore.Http/internal/index.js";
import type { RoutePattern, RoutePatternParameterPart, RoutePatternParameterPolicyReference } from "../../Microsoft.AspNetCore.Routing.Patterns/internal/index.js";
import type { RouteTemplate, TemplatePart } from "../../Microsoft.AspNetCore.Routing.Template/internal/index.js";
import * as System_Collections_Generic_Internal from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import type { ICollection_1, IDictionary_2, IEnumerable_1, IEnumerator_1, IEqualityComparer_1, IList_1, IReadOnlyCollection_1, IReadOnlyDictionary_2, IReadOnlyList_1, KeyValuePair_2 } from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import * as System_Collections_Internal from "@tsonic/dotnet/System.Collections/internal/index.js";
import type { IEnumerable, IEnumerator } from "@tsonic/dotnet/System.Collections/internal/index.js";
import type { MethodInfo } from "@tsonic/dotnet/System.Reflection/internal/index.js";
import * as System_Runtime_Serialization_Internal from "@tsonic/dotnet/System.Runtime.Serialization/internal/index.js";
import type { ISerializable } from "@tsonic/dotnet/System.Runtime.Serialization/internal/index.js";
import type { Task } from "@tsonic/dotnet/System.Threading.Tasks/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Action_1, Attribute, Boolean as ClrBoolean, Delegate, Double, Enum, Exception, Func_3, Func_4, IComparable, IConvertible, IDisposable, IFormattable, Int32, IServiceProvider, ISpanFormattable, Nullable_1, Object as ClrObject, String as ClrString, Type, ValueType, Void } from "@tsonic/dotnet/System/internal/index.js";
import type { ILogger } from "@tsonic/microsoft-extensions/Microsoft.Extensions.Logging/internal/index.js";
import type { IOptions_1 } from "@tsonic/microsoft-extensions/Microsoft.Extensions.Options/internal/index.js";
import type { IChangeToken } from "@tsonic/microsoft-extensions/Microsoft.Extensions.Primitives/internal/index.js";

export enum RouteDirection {
    IncomingRequest = 0,
    UrlGeneration = 1
}


export interface IDataTokensMetadata$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IDataTokensMetadata: never;

    readonly DataTokens: IReadOnlyDictionary_2<System_Internal.String, JsValue | null>;
}


export type IDataTokensMetadata = IDataTokensMetadata$instance;

export interface IDynamicEndpointMetadata$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IDynamicEndpointMetadata: never;

    readonly IsDynamic: boolean;
}


export type IDynamicEndpointMetadata = IDynamicEndpointMetadata$instance;

export interface IEndpointAddressScheme_1$instance<TAddress> {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IEndpointAddressScheme_1: never;

    FindEndpoints(address: TAddress): IEnumerable_1<Endpoint>;
}


export type IEndpointAddressScheme_1<TAddress> = IEndpointAddressScheme_1$instance<TAddress>;

export interface IEndpointGroupNameMetadata$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IEndpointGroupNameMetadata: never;

    readonly EndpointGroupName: string;
}


export type IEndpointGroupNameMetadata = IEndpointGroupNameMetadata$instance;

export interface IEndpointNameMetadata$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IEndpointNameMetadata: never;

    readonly EndpointName: string;
}


export type IEndpointNameMetadata = IEndpointNameMetadata$instance;

export interface IEndpointRouteBuilder$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IEndpointRouteBuilder: never;

    readonly ServiceProvider: IServiceProvider;
    readonly DataSources: ICollection_1<EndpointDataSource>;
    CreateApplicationBuilder(): IApplicationBuilder;
}


export type IEndpointRouteBuilder = IEndpointRouteBuilder$instance;

export interface IExcludeFromDescriptionMetadata$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IExcludeFromDescriptionMetadata: never;

    readonly ExcludeFromDescription: boolean;
}


export type IExcludeFromDescriptionMetadata = IExcludeFromDescriptionMetadata$instance;

export interface IHostMetadata$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IHostMetadata: never;

    readonly Hosts: IReadOnlyList_1<System_Internal.String>;
}


export type IHostMetadata = IHostMetadata$instance;

export interface IHttpMethodMetadata$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IHttpMethodMetadata: never;

    AcceptCorsPreflight: boolean;
    readonly HttpMethods: IReadOnlyList_1<System_Internal.String>;
}


export type IHttpMethodMetadata = IHttpMethodMetadata$instance;

export interface IInlineConstraintResolver$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IInlineConstraintResolver: never;

    ResolveConstraint(inlineConstraint: string): IRouteConstraint | null;
}


export type IInlineConstraintResolver = IInlineConstraintResolver$instance;

export interface INamedRouter$instance extends IRouter {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_INamedRouter: never;

    readonly Name: string | null;
    GetVirtualPath(context: VirtualPathContext): VirtualPathData | null;
    RouteAsync(context: RouteContext): Task;
}


export interface INamedRouter$instance extends IRouter$instance {}

export type INamedRouter = INamedRouter$instance;

export interface IOutboundParameterTransformer$instance extends IParameterPolicy {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IOutboundParameterTransformer: never;

    TransformOutbound(value: JsValue | null): string | null;
}


export interface IOutboundParameterTransformer$instance extends IParameterPolicy$instance {}

export type IOutboundParameterTransformer = IOutboundParameterTransformer$instance;

export interface IParameterPolicy$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IParameterPolicy: never;

}


export type IParameterPolicy = IParameterPolicy$instance;

export interface IRouteBuilder$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IRouteBuilder: never;

    readonly ApplicationBuilder: IApplicationBuilder;
    get DefaultHandler(): IRouter | null;
    set DefaultHandler(value: IRouter | null);
    readonly ServiceProvider: IServiceProvider;
    readonly Routes: IList_1<IRouter>;
    Build(): IRouter;
}


export type IRouteBuilder = IRouteBuilder$instance;

export interface IRouteCollection$instance extends IRouter {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IRouteCollection: never;

    Add(router: IRouter): void;
    GetVirtualPath(context: VirtualPathContext): VirtualPathData | null;
    RouteAsync(context: RouteContext): Task;
}


export interface IRouteCollection$instance extends IRouter$instance {}

export type IRouteCollection = IRouteCollection$instance;

export interface IRouteConstraint$instance extends IParameterPolicy {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IRouteConstraint: never;

    Match(httpContext: HttpContext | null, route: IRouter | null, routeKey: string, values: RouteValueDictionary, routeDirection: RouteDirection): boolean;
}


export interface IRouteConstraint$instance extends IParameterPolicy$instance {}

export type IRouteConstraint = IRouteConstraint$instance;

export interface IRouteHandler$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IRouteHandler: never;

    GetRequestHandler(httpContext: HttpContext, routeData: RouteData): RequestDelegate;
}


export type IRouteHandler = IRouteHandler$instance;

export interface IRouteNameMetadata$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IRouteNameMetadata: never;

    readonly RouteName: string | null;
}


export type IRouteNameMetadata = IRouteNameMetadata$instance;

export interface IRouter$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IRouter: never;

    GetVirtualPath(context: VirtualPathContext): VirtualPathData | null;
    RouteAsync(context: RouteContext): Task;
}


export type IRouter = IRouter$instance;

export interface IRoutingFeature$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IRoutingFeature: never;

    get RouteData(): RouteData | null;
    set RouteData(value: RouteData | null);
}


export type IRoutingFeature = IRoutingFeature$instance;

export interface ISuppressLinkGenerationMetadata$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_ISuppressLinkGenerationMetadata: never;

    readonly SuppressLinkGeneration: boolean;
}


export type ISuppressLinkGenerationMetadata = ISuppressLinkGenerationMetadata$instance;

export interface ISuppressMatchingMetadata$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_ISuppressMatchingMetadata: never;

    readonly SuppressMatching: boolean;
}


export type ISuppressMatchingMetadata = ISuppressMatchingMetadata$instance;

export interface CompositeEndpointDataSource$instance extends EndpointDataSource {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_CompositeEndpointDataSource: never;

    readonly __tsonic_iface_System_IDisposable: never;

    readonly DataSources: IEnumerable_1<EndpointDataSource>;
    readonly Endpoints: IReadOnlyList_1<Endpoint>;
    Dispose(): void;
    GetChangeToken(): IChangeToken;
    GetGroupedEndpoints(context: RouteGroupContext): IReadOnlyList_1<Endpoint>;
}


export const CompositeEndpointDataSource: {
    new(endpointDataSources: IEnumerable_1<EndpointDataSource>): CompositeEndpointDataSource;
};


export type CompositeEndpointDataSource = CompositeEndpointDataSource$instance;

export interface ContentEncodingMetadata$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_ContentEncodingMetadata: never;

    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_Matching_INegotiateMetadata: never;

    readonly Quality: double;
    readonly Value: string;
}


export const ContentEncodingMetadata: {
    new(value: string, quality: double): ContentEncodingMetadata;
};


export type ContentEncodingMetadata = ContentEncodingMetadata$instance;

export interface DataTokensMetadata$instance extends IDataTokensMetadata$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_DataTokensMetadata: never;

    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IDataTokensMetadata: never;

    readonly DataTokens: IReadOnlyDictionary_2<System_Internal.String, JsValue | null>;
    ToString(): string;
}


export const DataTokensMetadata: {
    new(dataTokens: IReadOnlyDictionary_2<System_Internal.String, JsValue | null>): DataTokensMetadata;
};


export interface __DataTokensMetadata$views {
    As_IDataTokensMetadata(): IDataTokensMetadata$instance;
}

export type DataTokensMetadata = DataTokensMetadata$instance & __DataTokensMetadata$views;


export interface DefaultEndpointDataSource$instance extends EndpointDataSource {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_DefaultEndpointDataSource: never;

    readonly Endpoints: IReadOnlyList_1<Endpoint>;
    GetChangeToken(): IChangeToken;
}


export const DefaultEndpointDataSource: {
    new(endpoints: Endpoint[]): DefaultEndpointDataSource;
    new(endpoints: IEnumerable_1<Endpoint>): DefaultEndpointDataSource;
};


export type DefaultEndpointDataSource = DefaultEndpointDataSource$instance;

export interface DefaultInlineConstraintResolver$instance extends IInlineConstraintResolver$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_DefaultInlineConstraintResolver: never;

    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IInlineConstraintResolver: never;

    ResolveConstraint(inlineConstraint: string): IRouteConstraint | null;
}


export const DefaultInlineConstraintResolver: {
    new(routeOptions: IOptions_1<RouteOptions>, serviceProvider: IServiceProvider): DefaultInlineConstraintResolver;
};


export interface __DefaultInlineConstraintResolver$views {
    As_IInlineConstraintResolver(): IInlineConstraintResolver$instance;
}

export type DefaultInlineConstraintResolver = DefaultInlineConstraintResolver$instance & __DefaultInlineConstraintResolver$views;


export interface EndpointDataSource$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_EndpointDataSource: never;

    readonly Endpoints: IReadOnlyList_1<Endpoint>;
    GetChangeToken(): IChangeToken;
    GetGroupedEndpoints(context: RouteGroupContext): IReadOnlyList_1<Endpoint>;
}


export const EndpointDataSource: (abstract new() => EndpointDataSource) & {
};


export type EndpointDataSource = EndpointDataSource$instance;

export interface EndpointGroupNameAttribute$instance extends Attribute, IEndpointGroupNameMetadata$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_EndpointGroupNameAttribute: never;

    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IEndpointGroupNameMetadata: never;

    readonly EndpointGroupName: string;
}


export const EndpointGroupNameAttribute: {
    new(endpointGroupName: string): EndpointGroupNameAttribute;
};


export interface __EndpointGroupNameAttribute$views {
    As_IEndpointGroupNameMetadata(): IEndpointGroupNameMetadata$instance;
}

export type EndpointGroupNameAttribute = EndpointGroupNameAttribute$instance & __EndpointGroupNameAttribute$views;


export interface EndpointNameAttribute$instance extends Attribute, IEndpointNameMetadata$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_EndpointNameAttribute: never;

    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IEndpointNameMetadata: never;

    readonly EndpointName: string;
}


export const EndpointNameAttribute: {
    new(endpointName: string): EndpointNameAttribute;
};


export interface __EndpointNameAttribute$views {
    As_IEndpointNameMetadata(): IEndpointNameMetadata$instance;
}

export type EndpointNameAttribute = EndpointNameAttribute$instance & __EndpointNameAttribute$views;


export interface EndpointNameMetadata$instance extends IEndpointNameMetadata$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_EndpointNameMetadata: never;

    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IEndpointNameMetadata: never;

    readonly EndpointName: string;
    ToString(): string;
}


export const EndpointNameMetadata: {
    new(endpointName: string): EndpointNameMetadata;
};


export interface __EndpointNameMetadata$views {
    As_IEndpointNameMetadata(): IEndpointNameMetadata$instance;
}

export type EndpointNameMetadata = EndpointNameMetadata$instance & __EndpointNameMetadata$views;


export interface ExcludeFromDescriptionAttribute$instance extends Attribute, IExcludeFromDescriptionMetadata$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_ExcludeFromDescriptionAttribute: never;

    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IExcludeFromDescriptionMetadata: never;

    readonly ExcludeFromDescription: boolean;
    ToString(): string;
}


export const ExcludeFromDescriptionAttribute: {
    new(): ExcludeFromDescriptionAttribute;
};


export interface __ExcludeFromDescriptionAttribute$views {
    As_IExcludeFromDescriptionMetadata(): IExcludeFromDescriptionMetadata$instance;
}

export type ExcludeFromDescriptionAttribute = ExcludeFromDescriptionAttribute$instance & __ExcludeFromDescriptionAttribute$views;


export interface HostAttribute$instance extends Attribute, IHostMetadata$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_HostAttribute: never;

    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IHostMetadata: never;

    readonly Hosts: IReadOnlyList_1<System_Internal.String>;
    ToString(): string;
}


export const HostAttribute: {
    new(host: string): HostAttribute;
    new(hosts: string[]): HostAttribute;
};


export interface __HostAttribute$views {
    As_IHostMetadata(): IHostMetadata$instance;
}

export type HostAttribute = HostAttribute$instance & __HostAttribute$views;


export interface HttpMethodMetadata$instance extends IHttpMethodMetadata$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_HttpMethodMetadata: never;

    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IHttpMethodMetadata: never;

    AcceptCorsPreflight: boolean;
    readonly HttpMethods: IReadOnlyList_1<System_Internal.String>;
    ToString(): string;
}


export const HttpMethodMetadata: {
    new(httpMethods: IEnumerable_1<System_Internal.String>): HttpMethodMetadata;
    new(httpMethods: IEnumerable_1<System_Internal.String>, acceptCorsPreflight: boolean): HttpMethodMetadata;
};


export interface __HttpMethodMetadata$views {
    As_IHttpMethodMetadata(): IHttpMethodMetadata$instance;
}

export type HttpMethodMetadata = HttpMethodMetadata$instance & __HttpMethodMetadata$views;


export interface LinkGenerator$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_LinkGenerator: never;

    GetPathByAddress<TAddress>(httpContext: HttpContext, address: TAddress, values: RouteValueDictionary, ambientValues?: RouteValueDictionary | null, pathBase?: Nullable_1<PathString>, fragment?: FragmentString, options?: LinkOptions | null): string | null;
    GetPathByAddress<TAddress>(address: TAddress, values: RouteValueDictionary, pathBase?: PathString, fragment?: FragmentString, options?: LinkOptions | null): string | null;
    GetUriByAddress<TAddress>(httpContext: HttpContext, address: TAddress, values: RouteValueDictionary, ambientValues?: RouteValueDictionary | null, scheme?: string | null, host?: Nullable_1<HostString>, pathBase?: Nullable_1<PathString>, fragment?: FragmentString, options?: LinkOptions | null): string | null;
    GetUriByAddress<TAddress>(address: TAddress, values: RouteValueDictionary, scheme: string, host: HostString, pathBase?: PathString, fragment?: FragmentString, options?: LinkOptions | null): string | null;
}


export const LinkGenerator: (abstract new() => LinkGenerator) & {
};


export type LinkGenerator = LinkGenerator$instance;

export interface LinkOptions$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_LinkOptions: never;

    get AppendTrailingSlash(): Nullable_1<System_Internal.Boolean>;
    set AppendTrailingSlash(value: Nullable_1<System_Internal.Boolean> | boolean);
    get LowercaseQueryStrings(): Nullable_1<System_Internal.Boolean>;
    set LowercaseQueryStrings(value: Nullable_1<System_Internal.Boolean> | boolean);
    get LowercaseUrls(): Nullable_1<System_Internal.Boolean>;
    set LowercaseUrls(value: Nullable_1<System_Internal.Boolean> | boolean);
}


export const LinkOptions: {
    new(): LinkOptions;
};


export type LinkOptions = LinkOptions$instance;

export interface LinkParser$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_LinkParser: never;

    ParsePathByAddress<TAddress>(address: TAddress, path: PathString): RouteValueDictionary | null;
}


export const LinkParser: (abstract new() => LinkParser) & {
};


export type LinkParser = LinkParser$instance;

export interface MatcherPolicy$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_MatcherPolicy: never;

    readonly Order: int;
}


export const MatcherPolicy: (abstract new() => MatcherPolicy) & {
    ContainsDynamicEndpoints(endpoints: IReadOnlyList_1<Endpoint>): boolean;
};


export type MatcherPolicy = MatcherPolicy$instance;

export interface ParameterPolicyFactory$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_ParameterPolicyFactory: never;

    Create(parameter: RoutePatternParameterPart | null, inlineText: string): IParameterPolicy;
    Create(parameter: RoutePatternParameterPart | null, parameterPolicy: IParameterPolicy): IParameterPolicy;
    Create(parameter: RoutePatternParameterPart | null, reference: RoutePatternParameterPolicyReference): IParameterPolicy;
}


export const ParameterPolicyFactory: (abstract new() => ParameterPolicyFactory) & {
};


export type ParameterPolicyFactory = ParameterPolicyFactory$instance;

export interface Route$instance extends RouteBase$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_Route: never;

    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_INamedRouter: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IRouter: never;

    readonly RouteTemplate: string | null;
    OnRouteMatched(context: RouteContext): Task;
    OnVirtualPathGenerated(context: VirtualPathContext): VirtualPathData | null;
}


export const Route: {
    new(target: IRouter, routeTemplate: string, inlineConstraintResolver: IInlineConstraintResolver): Route;
    new(target: IRouter, routeTemplate: string, defaults: RouteValueDictionary | null, constraints: IDictionary_2<System_Internal.String, JsValue> | null, dataTokens: RouteValueDictionary | null, inlineConstraintResolver: IInlineConstraintResolver): Route;
    new(target: IRouter, routeName: string | null, routeTemplate: string | null, defaults: RouteValueDictionary | null, constraints: IDictionary_2<System_Internal.String, JsValue> | null, dataTokens: RouteValueDictionary | null, inlineConstraintResolver: IInlineConstraintResolver): Route;
};


export interface __Route$views {
    As_INamedRouter(): INamedRouter$instance;
    As_IRouter(): IRouter$instance;
}

export type Route = Route$instance & __Route$views;


export interface RouteBase$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_RouteBase: never;

    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_INamedRouter: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IRouter: never;

    ConstraintResolver: IInlineConstraintResolver;
    Constraints: IDictionary_2<System_Internal.String, IRouteConstraint>;
    DataTokens: RouteValueDictionary;
    Defaults: RouteValueDictionary;
    get Name(): string | null;
    set Name(value: string | null);
    ParsedTemplate: RouteTemplate;
    GetVirtualPath(context: VirtualPathContext): VirtualPathData | null;
    OnRouteMatched(context: RouteContext): Task;
    OnVirtualPathGenerated(context: VirtualPathContext): VirtualPathData | null;
    RouteAsync(context: RouteContext): Task;
    ToString(): string;
}


export const RouteBase: (abstract new(template: string | null, name: string | null, constraintResolver: IInlineConstraintResolver, defaults: RouteValueDictionary | null, constraints: IDictionary_2<System_Internal.String, JsValue> | null, dataTokens: RouteValueDictionary | null) => RouteBase) & {
    GetConstraints(inlineConstraintResolver: IInlineConstraintResolver, parsedTemplate: RouteTemplate, constraints: IDictionary_2<System_Internal.String, JsValue> | null): IDictionary_2<System_Internal.String, IRouteConstraint>;
    GetDefaults(parsedTemplate: RouteTemplate, defaults: RouteValueDictionary | null): RouteValueDictionary;
};


export interface __RouteBase$views {
    As_INamedRouter(): INamedRouter$instance;
    As_IRouter(): IRouter$instance;
}

export type RouteBase = RouteBase$instance & __RouteBase$views;


export interface RouteBuilder$instance extends IRouteBuilder$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_RouteBuilder: never;

    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IRouteBuilder: never;

    readonly ApplicationBuilder: IApplicationBuilder;
    get DefaultHandler(): IRouter | null;
    set DefaultHandler(value: IRouter | null);
    readonly Routes: IList_1<IRouter>;
    readonly ServiceProvider: IServiceProvider;
    Build(): IRouter;
}


export const RouteBuilder: {
    new(applicationBuilder: IApplicationBuilder): RouteBuilder;
    new(applicationBuilder: IApplicationBuilder, defaultHandler: IRouter | null): RouteBuilder;
};


export interface __RouteBuilder$views {
    As_IRouteBuilder(): IRouteBuilder$instance;
}

export type RouteBuilder = RouteBuilder$instance & __RouteBuilder$views;


export interface RouteCollection$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_RouteCollection: never;

    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IRouteCollection: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IRouter: never;

    readonly Count: int;
    Add(router: IRouter): void;
    GetVirtualPath(context: VirtualPathContext): VirtualPathData | null;
    RouteAsync(context: RouteContext): Task;
}


export const RouteCollection: {
    new(): RouteCollection;
};


export interface __RouteCollection$views {
    As_IRouteCollection(): IRouteCollection$instance;
    As_IRouter(): IRouter$instance;
}

export type RouteCollection = RouteCollection$instance & __RouteCollection$views & { readonly [index: number]: IRouter; };


export interface RouteConstraintBuilder$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_RouteConstraintBuilder: never;

    AddConstraint(key: string, value: JsValue): void;
    AddResolvedConstraint(key: string, constraintText: string): void;
    Build(): IDictionary_2<System_Internal.String, IRouteConstraint>;
    SetOptional(key: string): void;
}


export const RouteConstraintBuilder: {
    new(inlineConstraintResolver: IInlineConstraintResolver, displayName: string): RouteConstraintBuilder;
};


export type RouteConstraintBuilder = RouteConstraintBuilder$instance;

export interface RouteContext$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_RouteContext: never;

    get Handler(): RequestDelegate | null;
    set Handler(value: RequestDelegate | null);
    readonly HttpContext: HttpContext;
    RouteData: RouteData;
}


export const RouteContext: {
    new(httpContext: HttpContext): RouteContext;
};


export type RouteContext = RouteContext$instance;

export interface RouteCreationException$instance extends Exception {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_RouteCreationException: never;

    readonly __tsonic_iface_System_Runtime_Serialization_ISerializable: never;

}


export const RouteCreationException: {
    new(message: string): RouteCreationException;
    new(message: string, innerException: Exception): RouteCreationException;
};


export type RouteCreationException = RouteCreationException$instance;

export interface RouteData$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_RouteData: never;

    readonly DataTokens: RouteValueDictionary;
    readonly Routers: IList_1<IRouter>;
    readonly Values: RouteValueDictionary;
    PushState(router: IRouter | null, values: RouteValueDictionary | null, dataTokens: RouteValueDictionary | null): RouteData_RouteDataSnapshot;
}


export const RouteData: {
    new(): RouteData;
    new(other: RouteData): RouteData;
    new(values: RouteValueDictionary): RouteData;
};


export type RouteData = RouteData$instance;

export interface RouteData_RouteDataSnapshot$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_RouteData_RouteDataSnapshot: never;

    Restore(): void;
}


export const RouteData_RouteDataSnapshot: {
    new(routeData: RouteData, dataTokens: RouteValueDictionary | null, routers: IList_1<IRouter> | null, values: RouteValueDictionary | null): RouteData_RouteDataSnapshot;
};


export type RouteData_RouteDataSnapshot = RouteData_RouteDataSnapshot$instance;

export interface RouteEndpoint$instance extends Endpoint {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_RouteEndpoint: never;

    readonly Order: int;
    readonly RoutePattern: RoutePattern;
}


export const RouteEndpoint: {
    new(requestDelegate: RequestDelegate, routePattern: RoutePattern, order: int, metadata: EndpointMetadataCollection | null, displayName: string | null): RouteEndpoint;
};


export type RouteEndpoint = RouteEndpoint$instance;

export interface RouteEndpointBuilder$instance extends EndpointBuilder {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_RouteEndpointBuilder: never;

    Order: int;
    RoutePattern: RoutePattern;
    Build(): Endpoint;
}


export const RouteEndpointBuilder: {
    new(requestDelegate: RequestDelegate | null, routePattern: RoutePattern, order: int): RouteEndpointBuilder;
};


export type RouteEndpointBuilder = RouteEndpointBuilder$instance;

export interface RouteGroupBuilder$instance extends Microsoft_AspNetCore_Builder_Internal.IEndpointConventionBuilder$instance, IEndpointRouteBuilder$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_RouteGroupBuilder: never;

    readonly __tsonic_iface_Microsoft_AspNetCore_Builder_IEndpointConventionBuilder: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IEndpointRouteBuilder: never;

}


export const RouteGroupBuilder: {
};


export interface __RouteGroupBuilder$views {
    As_IEndpointConventionBuilder(): Microsoft_AspNetCore_Builder_Internal.IEndpointConventionBuilder$instance;
    As_IEndpointRouteBuilder(): IEndpointRouteBuilder$instance;
}

export type RouteGroupBuilder = RouteGroupBuilder$instance & __RouteGroupBuilder$views;


export interface RouteGroupContext$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_RouteGroupContext: never;

    ApplicationServices: IServiceProvider;
    Conventions: IReadOnlyList_1<Action_1<EndpointBuilder>>;
    FinallyConventions: IReadOnlyList_1<Action_1<EndpointBuilder>>;
    Prefix: RoutePattern;
}


export const RouteGroupContext: {
    new(): RouteGroupContext;
};


export type RouteGroupContext = RouteGroupContext$instance;

export interface RouteHandler$instance extends IRouteHandler$instance, IRouter$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_RouteHandler: never;

    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IRouteHandler: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IRouter: never;

    GetRequestHandler(httpContext: HttpContext, routeData: RouteData): RequestDelegate;
    GetVirtualPath(context: VirtualPathContext): VirtualPathData | null;
    RouteAsync(context: RouteContext): Task;
}


export const RouteHandler: {
    new(requestDelegate: RequestDelegate): RouteHandler;
};


export interface __RouteHandler$views {
    As_IRouteHandler(): IRouteHandler$instance;
    As_IRouter(): IRouter$instance;
}

export type RouteHandler = RouteHandler$instance & __RouteHandler$views;


export interface RouteHandlerOptions$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_RouteHandlerOptions: never;

    ThrowOnBadRequest: boolean;
}


export const RouteHandlerOptions: {
    new(): RouteHandlerOptions;
};


export type RouteHandlerOptions = RouteHandlerOptions$instance;

export interface RouteNameMetadata$instance extends IRouteNameMetadata$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_RouteNameMetadata: never;

    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IRouteNameMetadata: never;

    readonly RouteName: string | null;
    ToString(): string;
}


export const RouteNameMetadata: {
    new(routeName: string | null): RouteNameMetadata;
};


export interface __RouteNameMetadata$views {
    As_IRouteNameMetadata(): IRouteNameMetadata$instance;
}

export type RouteNameMetadata = RouteNameMetadata$instance & __RouteNameMetadata$views;


export interface RouteOptions$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_RouteOptions: never;

    AppendTrailingSlash: boolean;
    ConstraintMap: IDictionary_2<System_Internal.String, Type>;
    LowercaseQueryStrings: boolean;
    LowercaseUrls: boolean;
    SuppressCheckForUnhandledSecurityMetadata: boolean;
    SetParameterPolicy<T extends IParameterPolicy>(token: string): void;
    SetParameterPolicy(token: string, type: Type): void;
}


export const RouteOptions: {
    new(): RouteOptions;
};


export type RouteOptions = RouteOptions$instance;

export interface RouteValueDictionary$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_RouteValueDictionary: never;

    readonly __tsonic_iface_System_Collections_Generic_ICollection_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IDictionary_2: never;
    readonly __tsonic_iface_System_Collections_Generic_IEnumerable_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyCollection_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyDictionary_2: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;

    readonly Comparer: IEqualityComparer_1<System_Internal.String>;
    readonly Count: int;
    readonly Keys: ICollection_1<System_Internal.String>;
    readonly Values: ICollection_1<JsValue | null>;
    Add(key: string, value: JsValue | null): void;
    Clear(): void;
    ContainsKey(key: string): boolean;
    GetEnumerator(): RouteValueDictionary_Enumerator;
    Remove(key: string): boolean;
    Remove(key: string, value: JsValue | null): boolean;
    TryAdd(key: string, value: JsValue | null): boolean;
    TryGetValue(key: string, value: JsValue | null): boolean;
}


export const RouteValueDictionary: {
    new(): RouteValueDictionary;
    new(values: JsValue | null): RouteValueDictionary;
    new(values: IEnumerable_1<KeyValuePair_2<System_Internal.String, JsValue>> | null): RouteValueDictionary;
    new(values: IEnumerable_1<KeyValuePair_2<System_Internal.String, System_Internal.String>> | null): RouteValueDictionary;
    new(dictionary: RouteValueDictionary | null): RouteValueDictionary;
    FromArray(items: KeyValuePair_2<System_Internal.String, JsValue>[]): RouteValueDictionary;
};


export type RouteValueDictionary = RouteValueDictionary$instance & { [key: string]: JsValue | null; };

export interface RouteValueDictionary_Enumerator$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_RouteValueDictionary_Enumerator: never;

    readonly __tsonic_iface_System_Collections_Generic_IEnumerator_1: never;
    readonly __tsonic_iface_System_Collections_IEnumerator: never;
    readonly __tsonic_iface_System_IDisposable: never;

    Current: KeyValuePair_2<System_Internal.String, JsValue>;
    Dispose(): void;
    MoveNext(): boolean;
    Reset(): void;
}


export const RouteValueDictionary_Enumerator: {
    new(dictionary: RouteValueDictionary): RouteValueDictionary_Enumerator;
};


export type RouteValueDictionary_Enumerator = RouteValueDictionary_Enumerator$instance;

export interface RouteValueEqualityComparer$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_RouteValueEqualityComparer: never;

    readonly __tsonic_iface_System_Collections_Generic_IEqualityComparer_1: never;

    Equals(x: JsValue | null, y: JsValue | null): boolean;
    GetHashCode(obj: JsValue): int;
}


export const RouteValueEqualityComparer: {
    new(): RouteValueEqualityComparer;
    readonly Default: RouteValueEqualityComparer;
};


export type RouteValueEqualityComparer = RouteValueEqualityComparer$instance;

export interface RouteValuesAddress$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_RouteValuesAddress: never;

    get AmbientValues(): RouteValueDictionary | null;
    set AmbientValues(value: RouteValueDictionary | null);
    ExplicitValues: RouteValueDictionary;
    get RouteName(): string | null;
    set RouteName(value: string | null);
    ToString(): string | null;
}


export const RouteValuesAddress: {
    new(): RouteValuesAddress;
};


export type RouteValuesAddress = RouteValuesAddress$instance;

export interface RoutingFeature$instance extends IRoutingFeature$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_RoutingFeature: never;

    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_IRoutingFeature: never;

    get RouteData(): RouteData | null;
    set RouteData(value: RouteData | null);
}


export const RoutingFeature: {
    new(): RoutingFeature;
};


export interface __RoutingFeature$views {
    As_IRoutingFeature(): IRoutingFeature$instance;
}

export type RoutingFeature = RoutingFeature$instance & __RoutingFeature$views;


export interface SuppressLinkGenerationMetadata$instance extends ISuppressLinkGenerationMetadata$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_SuppressLinkGenerationMetadata: never;

    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_ISuppressLinkGenerationMetadata: never;

    readonly SuppressLinkGeneration: boolean;
    ToString(): string;
}


export const SuppressLinkGenerationMetadata: {
    new(): SuppressLinkGenerationMetadata;
};


export interface __SuppressLinkGenerationMetadata$views {
    As_ISuppressLinkGenerationMetadata(): ISuppressLinkGenerationMetadata$instance;
}

export type SuppressLinkGenerationMetadata = SuppressLinkGenerationMetadata$instance & __SuppressLinkGenerationMetadata$views;


export interface SuppressMatchingMetadata$instance extends ISuppressMatchingMetadata$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_SuppressMatchingMetadata: never;

    readonly __tsonic_iface_Microsoft_AspNetCore_Routing_ISuppressMatchingMetadata: never;

    readonly SuppressMatching: boolean;
    ToString(): string;
}


export const SuppressMatchingMetadata: {
    new(): SuppressMatchingMetadata;
};


export interface __SuppressMatchingMetadata$views {
    As_ISuppressMatchingMetadata(): ISuppressMatchingMetadata$instance;
}

export type SuppressMatchingMetadata = SuppressMatchingMetadata$instance & __SuppressMatchingMetadata$views;


export interface VirtualPathContext$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_VirtualPathContext: never;

    readonly AmbientValues: RouteValueDictionary;
    readonly HttpContext: HttpContext;
    readonly RouteName: string | null;
    Values: RouteValueDictionary;
}


export const VirtualPathContext: {
    new(httpContext: HttpContext, ambientValues: RouteValueDictionary, values: RouteValueDictionary): VirtualPathContext;
    new(httpContext: HttpContext, ambientValues: RouteValueDictionary, values: RouteValueDictionary, routeName: string | null): VirtualPathContext;
};


export type VirtualPathContext = VirtualPathContext$instance;

export interface VirtualPathData$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Routing_VirtualPathData: never;

    readonly DataTokens: RouteValueDictionary;
    Router: IRouter;
    VirtualPath: string;
}


export const VirtualPathData: {
    new(router: IRouter, virtualPath: string): VirtualPathData;
    new(router: IRouter, virtualPath: string, dataTokens: RouteValueDictionary): VirtualPathData;
};


export type VirtualPathData = VirtualPathData$instance;

export abstract class ControllerLinkGeneratorExtensions$instance {
    static GetPathByAction(generator: LinkGenerator, httpContext: HttpContext, action?: string | null, controller?: string | null, values?: JsValue | null, pathBase?: Nullable_1<PathString>, fragment?: FragmentString, options?: LinkOptions | null): string | null;
    static GetPathByAction(generator: LinkGenerator, action: string, controller: string, values?: JsValue | null, pathBase?: PathString, fragment?: FragmentString, options?: LinkOptions | null): string | null;
    static GetUriByAction(generator: LinkGenerator, httpContext: HttpContext, action?: string | null, controller?: string | null, values?: JsValue | null, scheme?: string | null, host?: Nullable_1<HostString>, pathBase?: Nullable_1<PathString>, fragment?: FragmentString, options?: LinkOptions | null): string | null;
    static GetUriByAction(generator: LinkGenerator, action: string, controller: string, values: JsValue | null, scheme: string, host: HostString, pathBase?: PathString, fragment?: FragmentString, options?: LinkOptions | null): string | null;
}


export type ControllerLinkGeneratorExtensions = ControllerLinkGeneratorExtensions$instance;

export abstract class IdentityApiEndpointRouteBuilderExtensions$instance {
    static MapIdentityApi<TUser>(endpoints: IEndpointRouteBuilder): IEndpointConventionBuilder;
}


export type IdentityApiEndpointRouteBuilderExtensions = IdentityApiEndpointRouteBuilderExtensions$instance;

export abstract class InlineRouteParameterParser$instance {
    static ParseRouteParameter(routeParameter: string): TemplatePart;
}


export type InlineRouteParameterParser = InlineRouteParameterParser$instance;

export abstract class LinkGeneratorEndpointNameAddressExtensions$instance {
    static GetPathByName(generator: LinkGenerator, httpContext: HttpContext, endpointName: string, values?: RouteValueDictionary | null, pathBase?: Nullable_1<PathString>, fragment?: FragmentString, options?: LinkOptions | null): string | null;
    static GetPathByName(generator: LinkGenerator, httpContext: HttpContext, endpointName: string, values: JsValue | null, pathBase?: Nullable_1<PathString>, fragment?: FragmentString, options?: LinkOptions | null): string | null;
    static GetPathByName(generator: LinkGenerator, endpointName: string, values?: RouteValueDictionary | null, pathBase?: PathString, fragment?: FragmentString, options?: LinkOptions | null): string | null;
    static GetPathByName(generator: LinkGenerator, endpointName: string, values: JsValue | null, pathBase?: PathString, fragment?: FragmentString, options?: LinkOptions | null): string | null;
    static GetUriByName(generator: LinkGenerator, httpContext: HttpContext, endpointName: string, values?: RouteValueDictionary | null, scheme?: string | null, host?: Nullable_1<HostString>, pathBase?: Nullable_1<PathString>, fragment?: FragmentString, options?: LinkOptions | null): string | null;
    static GetUriByName(generator: LinkGenerator, httpContext: HttpContext, endpointName: string, values: JsValue | null, scheme?: string | null, host?: Nullable_1<HostString>, pathBase?: Nullable_1<PathString>, fragment?: FragmentString, options?: LinkOptions | null): string | null;
    static GetUriByName(generator: LinkGenerator, endpointName: string, values: RouteValueDictionary, scheme: string, host: HostString, pathBase?: PathString, fragment?: FragmentString, options?: LinkOptions | null): string | null;
    static GetUriByName(generator: LinkGenerator, endpointName: string, values: JsValue | null, scheme: string, host: HostString, pathBase?: PathString, fragment?: FragmentString, options?: LinkOptions | null): string | null;
}


export type LinkGeneratorEndpointNameAddressExtensions = LinkGeneratorEndpointNameAddressExtensions$instance;

export abstract class LinkGeneratorRouteValuesAddressExtensions$instance {
    static GetPathByRouteValues(generator: LinkGenerator, httpContext: HttpContext, routeName: string | null, values?: RouteValueDictionary | null, pathBase?: Nullable_1<PathString>, fragment?: FragmentString, options?: LinkOptions | null): string | null;
    static GetPathByRouteValues(generator: LinkGenerator, httpContext: HttpContext, routeName: string | null, values: JsValue | null, pathBase?: Nullable_1<PathString>, fragment?: FragmentString, options?: LinkOptions | null): string | null;
    static GetPathByRouteValues(generator: LinkGenerator, routeName: string | null, values?: RouteValueDictionary | null, pathBase?: PathString, fragment?: FragmentString, options?: LinkOptions | null): string | null;
    static GetPathByRouteValues(generator: LinkGenerator, routeName: string | null, values: JsValue | null, pathBase?: PathString, fragment?: FragmentString, options?: LinkOptions | null): string | null;
    static GetUriByRouteValues(generator: LinkGenerator, httpContext: HttpContext, routeName: string | null, values?: RouteValueDictionary | null, scheme?: string | null, host?: Nullable_1<HostString>, pathBase?: Nullable_1<PathString>, fragment?: FragmentString, options?: LinkOptions | null): string | null;
    static GetUriByRouteValues(generator: LinkGenerator, httpContext: HttpContext, routeName: string | null, values: JsValue | null, scheme?: string | null, host?: Nullable_1<HostString>, pathBase?: Nullable_1<PathString>, fragment?: FragmentString, options?: LinkOptions | null): string | null;
    static GetUriByRouteValues(generator: LinkGenerator, routeName: string | null, values: RouteValueDictionary, scheme: string, host: HostString, pathBase?: PathString, fragment?: FragmentString, options?: LinkOptions | null): string | null;
    static GetUriByRouteValues(generator: LinkGenerator, routeName: string | null, values: JsValue | null, scheme: string, host: HostString, pathBase?: PathString, fragment?: FragmentString, options?: LinkOptions | null): string | null;
}


export type LinkGeneratorRouteValuesAddressExtensions = LinkGeneratorRouteValuesAddressExtensions$instance;

export abstract class LinkParserEndpointNameAddressExtensions$instance {
    static ParsePathByEndpointName(parser: LinkParser, endpointName: string, path: PathString): RouteValueDictionary | null;
}


export type LinkParserEndpointNameAddressExtensions = LinkParserEndpointNameAddressExtensions$instance;

export abstract class PageLinkGeneratorExtensions$instance {
    static GetPathByPage(generator: LinkGenerator, httpContext: HttpContext, page?: string | null, handler?: string | null, values?: JsValue | null, pathBase?: Nullable_1<PathString>, fragment?: FragmentString, options?: LinkOptions | null): string | null;
    static GetPathByPage(generator: LinkGenerator, page: string, handler?: string | null, values?: JsValue | null, pathBase?: PathString, fragment?: FragmentString, options?: LinkOptions | null): string | null;
    static GetUriByPage(generator: LinkGenerator, httpContext: HttpContext, page?: string | null, handler?: string | null, values?: JsValue | null, scheme?: string | null, host?: Nullable_1<HostString>, pathBase?: Nullable_1<PathString>, fragment?: FragmentString, options?: LinkOptions | null): string | null;
    static GetUriByPage(generator: LinkGenerator, page: string, handler: string | null, values: JsValue | null, scheme: string, host: HostString, pathBase?: PathString, fragment?: FragmentString, options?: LinkOptions | null): string | null;
}


export type PageLinkGeneratorExtensions = PageLinkGeneratorExtensions$instance;

export abstract class RequestDelegateRouteBuilderExtensions$instance {
    static MapDelete(builder: IRouteBuilder, template: string, handler: RequestDelegate): IRouteBuilder;
    static MapDelete(builder: IRouteBuilder, template: string, handler: Func_4<HttpRequest, HttpResponse, RouteData, Task>): IRouteBuilder;
    static MapGet(builder: IRouteBuilder, template: string, handler: RequestDelegate): IRouteBuilder;
    static MapGet(builder: IRouteBuilder, template: string, handler: Func_4<HttpRequest, HttpResponse, RouteData, Task>): IRouteBuilder;
    static MapMiddlewareDelete(builder: IRouteBuilder, template: string, action: Action_1<IApplicationBuilder>): IRouteBuilder;
    static MapMiddlewareGet(builder: IRouteBuilder, template: string, action: Action_1<IApplicationBuilder>): IRouteBuilder;
    static MapMiddlewarePost(builder: IRouteBuilder, template: string, action: Action_1<IApplicationBuilder>): IRouteBuilder;
    static MapMiddlewarePut(builder: IRouteBuilder, template: string, action: Action_1<IApplicationBuilder>): IRouteBuilder;
    static MapMiddlewareRoute(builder: IRouteBuilder, template: string, action: Action_1<IApplicationBuilder>): IRouteBuilder;
    static MapMiddlewareVerb(builder: IRouteBuilder, verb: string, template: string, action: Action_1<IApplicationBuilder>): IRouteBuilder;
    static MapPost(builder: IRouteBuilder, template: string, handler: RequestDelegate): IRouteBuilder;
    static MapPost(builder: IRouteBuilder, template: string, handler: Func_4<HttpRequest, HttpResponse, RouteData, Task>): IRouteBuilder;
    static MapPut(builder: IRouteBuilder, template: string, handler: RequestDelegate): IRouteBuilder;
    static MapPut(builder: IRouteBuilder, template: string, handler: Func_4<HttpRequest, HttpResponse, RouteData, Task>): IRouteBuilder;
    static MapRoute(builder: IRouteBuilder, template: string, handler: RequestDelegate): IRouteBuilder;
    static MapVerb(builder: IRouteBuilder, verb: string, template: string, handler: RequestDelegate): IRouteBuilder;
    static MapVerb(builder: IRouteBuilder, verb: string, template: string, handler: Func_4<HttpRequest, HttpResponse, RouteData, Task>): IRouteBuilder;
}


export type RequestDelegateRouteBuilderExtensions = RequestDelegateRouteBuilderExtensions$instance;

export abstract class RouteConstraintMatcher$instance {
    static Match(constraints: IDictionary_2<System_Internal.String, IRouteConstraint>, routeValues: RouteValueDictionary, httpContext: HttpContext, route: IRouter, routeDirection: RouteDirection, logger: ILogger): boolean;
}


export type RouteConstraintMatcher = RouteConstraintMatcher$instance;

export abstract class RouteHandlerServices$instance {
    static Map(endpoints: IEndpointRouteBuilder, pattern: string, handler: Function, httpMethods: IEnumerable_1<System_Internal.String> | null, populateMetadata: Func_3<MethodInfo, RequestDelegateFactoryOptions | null, RequestDelegateMetadataResult>, createRequestDelegate: Func_4<Function, RequestDelegateFactoryOptions, RequestDelegateMetadataResult | null, RequestDelegateResult>, methodInfo: MethodInfo): RouteHandlerBuilder;
    static Map(endpoints: IEndpointRouteBuilder, pattern: string, handler: Function, httpMethods: IEnumerable_1<System_Internal.String> | null, populateMetadata: Func_3<MethodInfo, RequestDelegateFactoryOptions | null, RequestDelegateMetadataResult>, createRequestDelegate: Func_4<Function, RequestDelegateFactoryOptions, RequestDelegateMetadataResult | null, RequestDelegateResult>): RouteHandlerBuilder;
}


export type RouteHandlerServices = RouteHandlerServices$instance;

export abstract class RouteShortCircuitEndpointRouteBuilderExtensions$instance {
    static MapShortCircuit(builder: IEndpointRouteBuilder, statusCode: int, ...routePrefixes: string[]): IEndpointConventionBuilder;
}


export type RouteShortCircuitEndpointRouteBuilderExtensions = RouteShortCircuitEndpointRouteBuilderExtensions$instance;

export abstract class RoutingHttpContextExtensions$instance {
    static GetRouteData(httpContext: HttpContext): RouteData;
    static GetRouteValue(httpContext: HttpContext, key: string): JsValue | null;
}


export type RoutingHttpContextExtensions = RoutingHttpContextExtensions$instance;

