// Generated by tsbindgen - Architecture
// Namespace: Microsoft.AspNetCore.Server.HttpSys
// Assembly: Microsoft.AspNetCore.Server.HttpSys

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import support types from @tsonic/core
import type { ptr } from "@tsonic/core/types.js";

// Import types from other namespaces
import * as System_Collections_Generic_Internal from "@tsonic/dotnet/System.Collections.Generic.js";
import type { ICollection, IEnumerable as IEnumerable__System_Collections_Generic, IEnumerator, IReadOnlyDictionary } from "@tsonic/dotnet/System.Collections.Generic.js";
import * as System_Collections_Internal from "@tsonic/dotnet/System.Collections.js";
import type { IEnumerable } from "@tsonic/dotnet/System.Collections.js";
import * as System_ComponentModel_Internal from "@tsonic/dotnet/System.ComponentModel.js";
import type { Win32Exception } from "@tsonic/dotnet/System.ComponentModel.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Boolean as ClrBoolean, Byte, Enum, IComparable, IConvertible, IDisposable, IFormattable, Int32, Int64, ISpanFormattable, Nullable, Object as ClrObject, ReadOnlyMemory, ReadOnlySpan, Span, String as ClrString, TimeSpan, Void } from "@tsonic/dotnet/System.js";
import * as System_Runtime_Serialization_Internal from "@tsonic/dotnet/System.Runtime.Serialization.js";
import type { ISerializable } from "@tsonic/dotnet/System.Runtime.Serialization.js";
import type { GenericSecurityDescriptor } from "@tsonic/dotnet/System.Security.AccessControl.js";

export enum AuthenticationSchemes {
    none = 0,
    basic = 1,
    NTLM = 4,
    negotiate = 8,
    kerberos = 16
}


export enum ClientCertificateMethod {
    noCertificate = 0,
    allowCertificate = 1,
    allowRenegotation = 2
}


export enum Http503VerbosityLevel {
    basic = 0,
    limited = 1,
    full = 2
}


export enum HttpSysRequestTimingType {
    connectionStart = 0,
    dataStart = 1,
    tlsCertificateLoadStart = 2,
    tlsCertificateLoadEnd = 3,
    tlsHandshakeLeg1Start = 4,
    tlsHandshakeLeg1End = 5,
    tlsHandshakeLeg2Start = 6,
    tlsHandshakeLeg2End = 7,
    tlsAttributesQueryStart = 8,
    tlsAttributesQueryEnd = 9,
    tlsClientCertQueryStart = 10,
    tlsClientCertQueryEnd = 11,
    http2StreamStart = 12,
    http2HeaderDecodeStart = 13,
    http2HeaderDecodeEnd = 14,
    requestHeaderParseStart = 15,
    requestHeaderParseEnd = 16,
    requestRoutingStart = 17,
    requestRoutingEnd = 18,
    requestQueuedForInspection = 19,
    requestDeliveredForInspection = 20,
    requestReturnedAfterInspection = 21,
    requestQueuedForDelegation = 22,
    requestDeliveredForDelegation = 23,
    requestReturnedAfterDelegation = 24,
    requestQueuedForIO = 25,
    requestDeliveredForIO = 26,
    http3StreamStart = 27,
    http3HeaderDecodeStart = 28,
    http3HeaderDecodeEnd = 29
}


export enum RequestQueueMode {
    create = 0,
    attach = 1,
    createOrAttach = 2
}


export interface IHttpSysRequestDelegationFeature$instance {
    readonly canDelegate: boolean;
    delegateRequest(destination: DelegationRule): void;
}


export type IHttpSysRequestDelegationFeature = IHttpSysRequestDelegationFeature$instance;

export interface IHttpSysRequestInfoFeature$instance {
    readonly requestInfo: IReadOnlyDictionary<System_Internal.Int32, ReadOnlyMemory<System_Internal.Byte>>;
}


export type IHttpSysRequestInfoFeature = IHttpSysRequestInfoFeature$instance;

export interface IHttpSysRequestPropertyFeature$instance {
    tryGetTlsClientHello(tlsClientHelloBytesDestination: Span<System_Internal.Byte>, bytesReturned: int): boolean;
}


export type IHttpSysRequestPropertyFeature = IHttpSysRequestPropertyFeature$instance;

export interface IHttpSysRequestTimingFeature$instance {
    readonly timestamps: ReadOnlySpan<System_Internal.Int64>;
    tryGetElapsedTime(startingTimestampType: HttpSysRequestTimingType, endingTimestampType: HttpSysRequestTimingType, elapsed: TimeSpan): boolean;
    tryGetTimestamp(timestampType: HttpSysRequestTimingType, timestamp: long): boolean;
}


export type IHttpSysRequestTimingFeature = IHttpSysRequestTimingFeature$instance;

export interface IServerDelegationFeature$instance {
    createDelegationRule(queueName: string, urlPrefix: string): DelegationRule;
}


export type IServerDelegationFeature = IServerDelegationFeature$instance;

export interface AuthenticationManager$instance {
    allowAnonymous: boolean;
    get authenticationDisplayName(): string | undefined;
    set authenticationDisplayName(value: string);
    automaticAuthentication: boolean;
    captureCredentials: boolean;
    enableKerberosCredentialCaching: boolean;
    schemes: AuthenticationSchemes;
}


export const AuthenticationManager: {
    new(): AuthenticationManager;
};


export type AuthenticationManager = AuthenticationManager$instance;

export interface DelegationRule$instance {
    readonly queueName: string;
    readonly urlPrefix: string;
    dispose(): void;
}


export const DelegationRule: {
    new(): DelegationRule;
};


export type DelegationRule = DelegationRule$instance;

export interface HttpSysException$instance extends Win32Exception {
    readonly errorCode: int;
}


export const HttpSysException: {
    new(): HttpSysException;
};


export type HttpSysException = HttpSysException$instance;

export interface HttpSysOptions$instance {
    allowSynchronousIO: boolean;
    readonly authentication: AuthenticationManager;
    clientCertificateMethod: ClientCertificateMethod;
    enableKernelResponseBuffering: boolean;
    enableResponseCaching: boolean;
    http503Verbosity: Http503VerbosityLevel;
    maxAccepts: int;
    maxConnections: Nullable<System_Internal.Int64>;
    maxRequestBodySize: Nullable<System_Internal.Int64>;
    requestQueueLimit: long;
    requestQueueMode: RequestQueueMode;
    get requestQueueName(): string | undefined;
    set requestQueueName(value: string);
    get requestQueueSecurityDescriptor(): GenericSecurityDescriptor | undefined;
    set requestQueueSecurityDescriptor(value: GenericSecurityDescriptor);
    throwWriteExceptions: boolean;
    readonly timeouts: TimeoutManager;
    unsafePreferInlineScheduling: boolean;
    readonly urlPrefixes: UrlPrefixCollection;
    useLatin1RequestHeaders: boolean;
}


export const HttpSysOptions: {
    new(): HttpSysOptions;
};


export type HttpSysOptions = HttpSysOptions$instance;

export interface TimeoutManager$instance {
    drainEntityBody: TimeSpan;
    entityBody: TimeSpan;
    headerWait: TimeSpan;
    idleConnection: TimeSpan;
    minSendBytesPerSecond: long;
    requestQueue: TimeSpan;
}


export const TimeoutManager: {
    new(): TimeoutManager;
};


export type TimeoutManager = TimeoutManager$instance;

export interface UrlPrefix$instance {
    readonly fullPrefix: string;
    readonly host: string;
    readonly isHttps: boolean;
    readonly path: string;
    readonly port: string;
    readonly portValue: int;
    readonly scheme: string;
    equals(obj: unknown): boolean;
    getHashCode(): int;
    toString(): string;
}


export const UrlPrefix: {
    new(): UrlPrefix;
    create(scheme: string, host: string, portValue: Nullable<System_Internal.Int32>, path: string): UrlPrefix;
    create(scheme: string, host: string, port: string, path: string): UrlPrefix;
    create(prefix: string): UrlPrefix;
};


export type UrlPrefix = UrlPrefix$instance;

export interface UrlPrefixCollection$instance {
    readonly count: int;
    readonly isReadOnly: boolean;
    add(prefix: string): void;
    add(item: UrlPrefix): void;
    clear(): void;
    contains(item: UrlPrefix): boolean;
    copyTo(array: UrlPrefix[], arrayIndex: int): void;
    getEnumerator(): IEnumerator<UrlPrefix>;
    remove(prefix: string): boolean;
    remove(item: UrlPrefix): boolean;
}


export const UrlPrefixCollection: {
    new(): UrlPrefixCollection;
};


export type UrlPrefixCollection = UrlPrefixCollection$instance;

export abstract class HttpSysDefaults$instance {
    static readonly authenticationScheme: string;
}


export type HttpSysDefaults = HttpSysDefaults$instance;

