// Generated by tsbindgen - Architecture
// Namespace: Microsoft.AspNetCore.DataProtection.KeyManagement
// Assembly: Microsoft.AspNetCore.DataProtection

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { AlgorithmConfiguration, IAuthenticatedEncryptorDescriptor } from "../../Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel/internal/index.js";
import type { IAuthenticatedEncryptor, IAuthenticatedEncryptorFactory } from "../../Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption/internal/index.js";
import type { IActivator } from "../../Microsoft.AspNetCore.DataProtection.Internal/internal/index.js";
import type { IXmlRepository } from "../../Microsoft.AspNetCore.DataProtection.Repositories/internal/index.js";
import type { IXmlEncryptor } from "../../Microsoft.AspNetCore.DataProtection.XmlEncryption/internal/index.js";
import type { IList, IReadOnlyCollection } from "@tsonic/dotnet/System.Collections.Generic.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Boolean as ClrBoolean, DateTimeOffset, Func, Guid, Object as ClrObject, String as ClrString, TimeSpan, Void } from "@tsonic/dotnet/System.js";
import type { CancellationToken } from "@tsonic/dotnet/System.Threading.js";
import type { XElement } from "@tsonic/dotnet/System.Xml.Linq.js";
import type { ILoggerFactory } from "@tsonic/microsoft-extensions/Microsoft.Extensions.Logging.js";
import type { IOptions } from "@tsonic/microsoft-extensions/Microsoft.Extensions.Options.js";

export interface IDeletableKeyManager$instance extends IKeyManager {
    readonly __tsonic_iface_Microsoft_AspNetCore_DataProtection_KeyManagement_IDeletableKeyManager: never;

    readonly CanDeleteKeys: boolean;
    CreateNewKey(activationDate: DateTimeOffset, expirationDate: DateTimeOffset): IKey;
    DeleteKeys(shouldDelete: Func<IKey, System_Internal.Boolean>): boolean;
    GetAllKeys(): IReadOnlyCollection<IKey>;
    GetCacheExpirationToken(): CancellationToken;
    RevokeAllKeys(revocationDate: DateTimeOffset, reason?: string): void;
    RevokeKey(keyId: Guid, reason?: string): void;
}


export interface IDeletableKeyManager$instance extends IKeyManager$instance {}

export type IDeletableKeyManager = IDeletableKeyManager$instance;

export interface IKey$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_DataProtection_KeyManagement_IKey: never;

    readonly ActivationDate: DateTimeOffset;
    readonly CreationDate: DateTimeOffset;
    readonly ExpirationDate: DateTimeOffset;
    readonly IsRevoked: boolean;
    readonly KeyId: Guid;
    readonly Descriptor: IAuthenticatedEncryptorDescriptor;
    CreateEncryptor(): IAuthenticatedEncryptor | undefined;
}


export type IKey = IKey$instance;

export interface IKeyEscrowSink$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_DataProtection_KeyManagement_IKeyEscrowSink: never;

    Store(keyId: Guid, element: XElement): void;
}


export type IKeyEscrowSink = IKeyEscrowSink$instance;

export interface IKeyManager$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_DataProtection_KeyManagement_IKeyManager: never;

    CreateNewKey(activationDate: DateTimeOffset, expirationDate: DateTimeOffset): IKey;
    GetAllKeys(): IReadOnlyCollection<IKey>;
    GetCacheExpirationToken(): CancellationToken;
    RevokeAllKeys(revocationDate: DateTimeOffset, reason?: string): void;
    RevokeKey(keyId: Guid, reason?: string): void;
}


export type IKeyManager = IKeyManager$instance;

export interface KeyManagementOptions$instance {
    get AuthenticatedEncryptorConfiguration(): AlgorithmConfiguration | undefined;
    set AuthenticatedEncryptorConfiguration(value: AlgorithmConfiguration | undefined);
    readonly AuthenticatedEncryptorFactories: IList<IAuthenticatedEncryptorFactory>;
    AutoGenerateKeys: boolean;
    readonly KeyEscrowSinks: IList<IKeyEscrowSink>;
    NewKeyLifetime: TimeSpan;
    get XmlEncryptor(): IXmlEncryptor | undefined;
    set XmlEncryptor(value: IXmlEncryptor | undefined);
    get XmlRepository(): IXmlRepository | undefined;
    set XmlRepository(value: IXmlRepository | undefined);
}


export const KeyManagementOptions: {
    new(): KeyManagementOptions;
};


export type KeyManagementOptions = KeyManagementOptions$instance;

export interface XmlKeyManager$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_DataProtection_KeyManagement_IKeyManager: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_DataProtection_KeyManagement_Internal_IInternalXmlKeyManager: never;

    readonly CanDeleteKeys: boolean;
    CreateNewKey(activationDate: DateTimeOffset, expirationDate: DateTimeOffset): IKey;
    DeleteKeys(shouldDelete: Func<IKey, System_Internal.Boolean>): boolean;
    GetAllKeys(): IReadOnlyCollection<IKey>;
    GetCacheExpirationToken(): CancellationToken;
    RevokeAllKeys(revocationDate: DateTimeOffset, reason?: string): void;
    RevokeKey(keyId: Guid, reason?: string): void;
}


export const XmlKeyManager: {
    new(keyManagementOptions: IOptions<KeyManagementOptions>, activator: IActivator): XmlKeyManager;
    new(keyManagementOptions: IOptions<KeyManagementOptions>, activator: IActivator, loggerFactory: ILoggerFactory): XmlKeyManager;
};


export interface __XmlKeyManager$views {
    As_IKeyManager(): IKeyManager$instance;
    As_IInternalXmlKeyManager(): Microsoft_AspNetCore_DataProtection_KeyManagement_Internal_Internal.IInternalXmlKeyManager$instance;
}

export interface XmlKeyManager$instance extends IKeyManager$instance {}

export type XmlKeyManager = XmlKeyManager$instance & __XmlKeyManager$views;


