// Generated by tsbindgen - Architecture
// Namespace: Microsoft.AspNetCore.Mvc.ActionConstraints
// Assembly: Microsoft.AspNetCore.Mvc.Abstractions, Microsoft.AspNetCore.Mvc.Core

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Import types from other namespaces
import type { HttpContext } from "../../Microsoft.AspNetCore.Http/internal/index.js";
import type { ActionDescriptor } from "../../Microsoft.AspNetCore.Mvc.Abstractions/internal/index.js";
import type { RouteContext } from "../../Microsoft.AspNetCore.Routing/internal/index.js";
import type { IEnumerable_1, IList_1, IReadOnlyList_1 } from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Attribute, Boolean as ClrBoolean, Int32, IServiceProvider, Object as ClrObject, String as ClrString, ValueType, Void } from "@tsonic/dotnet/System/internal/index.js";

export interface IActionConstraint$instance extends IActionConstraintMetadata {
    readonly __tsonic_iface_Microsoft_AspNetCore_Mvc_ActionConstraints_IActionConstraint: never;

    readonly Order: int;
    Accept(context: ActionConstraintContext): boolean;
}


export interface IActionConstraint$instance extends IActionConstraintMetadata$instance {}

export type IActionConstraint = IActionConstraint$instance;

export interface IActionConstraintFactory$instance extends IActionConstraintMetadata {
    readonly __tsonic_iface_Microsoft_AspNetCore_Mvc_ActionConstraints_IActionConstraintFactory: never;

    readonly IsReusable: boolean;
    CreateInstance(services: IServiceProvider): IActionConstraint;
}


export interface IActionConstraintFactory$instance extends IActionConstraintMetadata$instance {}

export type IActionConstraintFactory = IActionConstraintFactory$instance;

export interface IActionConstraintMetadata$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Mvc_ActionConstraints_IActionConstraintMetadata: never;

}


export type IActionConstraintMetadata = IActionConstraintMetadata$instance;

export interface IActionConstraintProvider$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Mvc_ActionConstraints_IActionConstraintProvider: never;

    readonly Order: int;
    OnProvidersExecuting(context: ActionConstraintProviderContext): void;
}


export type IActionConstraintProvider = IActionConstraintProvider$instance;

export interface ActionSelectorCandidate$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Mvc_ActionConstraints_ActionSelectorCandidate: never;

    readonly Action: ActionDescriptor;
    readonly Constraints: IReadOnlyList_1<IActionConstraint> | null;
}


export const ActionSelectorCandidate: {
    new(action: ActionDescriptor, constraints: IReadOnlyList_1<IActionConstraint> | null): ActionSelectorCandidate;
};


export type ActionSelectorCandidate = ActionSelectorCandidate$instance;

export interface ActionConstraintContext$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Mvc_ActionConstraints_ActionConstraintContext: never;

    Candidates: IReadOnlyList_1<ActionSelectorCandidate>;
    CurrentCandidate: ActionSelectorCandidate;
    RouteContext: RouteContext;
}


export const ActionConstraintContext: {
    new(): ActionConstraintContext;
};


export type ActionConstraintContext = ActionConstraintContext$instance;

export interface ActionConstraintItem$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Mvc_ActionConstraints_ActionConstraintItem: never;

    get Constraint(): IActionConstraint | null;
    set Constraint(value: IActionConstraint | null);
    IsReusable: boolean;
    readonly Metadata: IActionConstraintMetadata;
}


export const ActionConstraintItem: {
    new(metadata: IActionConstraintMetadata): ActionConstraintItem;
};


export type ActionConstraintItem = ActionConstraintItem$instance;

export interface ActionConstraintProviderContext$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Mvc_ActionConstraints_ActionConstraintProviderContext: never;

    readonly Action: ActionDescriptor;
    readonly HttpContext: HttpContext;
    readonly Results: IList_1<ActionConstraintItem>;
}


export const ActionConstraintProviderContext: {
    new(context: HttpContext, action: ActionDescriptor, items: IList_1<ActionConstraintItem>): ActionConstraintProviderContext;
};


export type ActionConstraintProviderContext = ActionConstraintProviderContext$instance;

export interface ActionMethodSelectorAttribute$instance extends Attribute {
    readonly __tsonic_type_Microsoft_AspNetCore_Mvc_ActionConstraints_ActionMethodSelectorAttribute: never;

    readonly __tsonic_iface_Microsoft_AspNetCore_Mvc_ActionConstraints_IActionConstraint: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Mvc_ActionConstraints_IActionConstraintMetadata: never;

    Order: int;
    Accept(context: ActionConstraintContext): boolean;
    IsValidForRequest(routeContext: RouteContext, action: ActionDescriptor): boolean;
}


export const ActionMethodSelectorAttribute: (abstract new() => ActionMethodSelectorAttribute) & {
};


export interface __ActionMethodSelectorAttribute$views {
    As_IActionConstraint(): IActionConstraint$instance;
}

export type ActionMethodSelectorAttribute = ActionMethodSelectorAttribute$instance & __ActionMethodSelectorAttribute$views;


export interface HttpMethodActionConstraint$instance extends IActionConstraint$instance {
    readonly __tsonic_type_Microsoft_AspNetCore_Mvc_ActionConstraints_HttpMethodActionConstraint: never;

    readonly __tsonic_iface_Microsoft_AspNetCore_Mvc_ActionConstraints_IActionConstraint: never;
    readonly __tsonic_iface_Microsoft_AspNetCore_Mvc_ActionConstraints_IActionConstraintMetadata: never;

    readonly HttpMethods: IEnumerable_1<System_Internal.String>;
    readonly Order: int;
    Accept(context: ActionConstraintContext): boolean;
}


export const HttpMethodActionConstraint: {
    new(httpMethods: IEnumerable_1<System_Internal.String>): HttpMethodActionConstraint;
    readonly HttpMethodConstraintOrder: int;
};


export interface __HttpMethodActionConstraint$views {
    As_IActionConstraint(): IActionConstraint$instance;
}

export type HttpMethodActionConstraint = HttpMethodActionConstraint$instance & __HttpMethodActionConstraint$views;


