// Generated by tsbindgen - Architecture
// Namespace: Microsoft.AspNetCore.Mvc.TagHelpers.Cache
// Assembly: Microsoft.AspNetCore.Mvc.TagHelpers

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { HtmlString, IHtmlContent } from "../../Microsoft.AspNetCore.Html/internal/index.js";
import type { CacheTagHelper, DistributedCacheTagHelper } from "../../Microsoft.AspNetCore.Mvc.TagHelpers/internal/index.js";
import type { TagHelperContext, TagHelperOutput } from "../../Microsoft.AspNetCore.Razor.TagHelpers/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Boolean as ClrBoolean, Byte, IEquatable, Int32, Object as ClrObject, String as ClrString } from "@tsonic/dotnet/System.js";
import type { HtmlEncoder } from "@tsonic/dotnet/System.Text.Encodings.Web.js";
import type { Task } from "@tsonic/dotnet/System.Threading.Tasks.js";
import type { DistributedCacheEntryOptions, IDistributedCache } from "@tsonic/microsoft-extensions/Microsoft.Extensions.Caching.Distributed.js";
import type { ILoggerFactory } from "@tsonic/microsoft-extensions/Microsoft.Extensions.Logging.js";

export interface IDistributedCacheTagHelperFormatter$instance {
    DeserializeAsync(value: byte[]): Task<HtmlString>;
    SerializeAsync(context: DistributedCacheTagHelperFormattingContext): Task<byte[]>;
}


export type IDistributedCacheTagHelperFormatter = IDistributedCacheTagHelperFormatter$instance;

export interface IDistributedCacheTagHelperService$instance {
    ProcessContentAsync(output: TagHelperOutput, key: CacheTagKey, options: DistributedCacheEntryOptions): Task<IHtmlContent>;
}


export type IDistributedCacheTagHelperService = IDistributedCacheTagHelperService$instance;

export interface IDistributedCacheTagHelperStorage$instance {
    GetAsync(key: string): Task<byte[]>;
    SetAsync(key: string, value: byte[], options: DistributedCacheEntryOptions): Task;
}


export type IDistributedCacheTagHelperStorage = IDistributedCacheTagHelperStorage$instance;

export interface CacheTagKey$instance {
    Equals(obj: unknown): boolean;
    Equals(other: CacheTagKey): boolean;
    GenerateHashedKey(): string;
    GenerateKey(): string;
    GetHashCode(): int;
}


export const CacheTagKey: {
    new(tagHelper: CacheTagHelper, context: TagHelperContext): CacheTagKey;
    new(tagHelper: DistributedCacheTagHelper): CacheTagKey;
};


export type CacheTagKey = CacheTagKey$instance;

export interface DistributedCacheTagHelperFormatter$instance {
    DeserializeAsync(value: byte[]): Task<HtmlString>;
    SerializeAsync(context: DistributedCacheTagHelperFormattingContext): Task<byte[]>;
}


export const DistributedCacheTagHelperFormatter: {
    new(): DistributedCacheTagHelperFormatter;
};


export interface __DistributedCacheTagHelperFormatter$views {
    As_IDistributedCacheTagHelperFormatter(): IDistributedCacheTagHelperFormatter$instance;
}

export interface DistributedCacheTagHelperFormatter$instance extends IDistributedCacheTagHelperFormatter$instance {}

export type DistributedCacheTagHelperFormatter = DistributedCacheTagHelperFormatter$instance & __DistributedCacheTagHelperFormatter$views;


export interface DistributedCacheTagHelperFormattingContext$instance {
    Html: HtmlString;
}


export const DistributedCacheTagHelperFormattingContext: {
    new(): DistributedCacheTagHelperFormattingContext;
};


export type DistributedCacheTagHelperFormattingContext = DistributedCacheTagHelperFormattingContext$instance;

export interface DistributedCacheTagHelperService$instance {
    ProcessContentAsync(output: TagHelperOutput, key: CacheTagKey, options: DistributedCacheEntryOptions): Task<IHtmlContent>;
}


export const DistributedCacheTagHelperService: {
    new(storage: IDistributedCacheTagHelperStorage, formatter: IDistributedCacheTagHelperFormatter, HtmlEncoder: HtmlEncoder, loggerFactory: ILoggerFactory): DistributedCacheTagHelperService;
};


export interface __DistributedCacheTagHelperService$views {
    As_IDistributedCacheTagHelperService(): IDistributedCacheTagHelperService$instance;
}

export interface DistributedCacheTagHelperService$instance extends IDistributedCacheTagHelperService$instance {}

export type DistributedCacheTagHelperService = DistributedCacheTagHelperService$instance & __DistributedCacheTagHelperService$views;


export interface DistributedCacheTagHelperStorage$instance {
    GetAsync(key: string): Task<byte[]>;
    SetAsync(key: string, value: byte[], options: DistributedCacheEntryOptions): Task;
}


export const DistributedCacheTagHelperStorage: {
    new(distributedCache: IDistributedCache): DistributedCacheTagHelperStorage;
};


export interface __DistributedCacheTagHelperStorage$views {
    As_IDistributedCacheTagHelperStorage(): IDistributedCacheTagHelperStorage$instance;
}

export interface DistributedCacheTagHelperStorage$instance extends IDistributedCacheTagHelperStorage$instance {}

export type DistributedCacheTagHelperStorage = DistributedCacheTagHelperStorage$instance & __DistributedCacheTagHelperStorage$views;


