// Generated by tsbindgen - Architecture
// Namespace: Microsoft.AspNetCore.DataProtection.Internal
// Assembly: Microsoft.AspNetCore.DataProtection

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Object as ClrObject, String as ClrString, Type } from "@tsonic/dotnet/System.js";

export interface IActivator$instance {
    CreateInstance(expectedBaseType: Type, implementationTypeName: string): unknown;
}


export type IActivator = IActivator$instance;

