// Generated by tsbindgen - Architecture
// Namespace: Microsoft.AspNetCore.Identity.Data
// Assembly: Microsoft.AspNetCore.Identity

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Boolean as ClrBoolean, Int32, Nullable, Object as ClrObject, String as ClrString } from "@tsonic/dotnet/System.js";

export interface ForgotPasswordRequest$instance {
    email: string;
}


export const ForgotPasswordRequest: {
    new(): ForgotPasswordRequest;
};


export type ForgotPasswordRequest = ForgotPasswordRequest$instance;

export interface InfoRequest$instance {
    get newEmail(): string | undefined;
    set newEmail(value: string);
    newPassword: string;
    get oldPassword(): string | undefined;
    set oldPassword(value: string);
}


export const InfoRequest: {
    new(): InfoRequest;
};


export type InfoRequest = InfoRequest$instance;

export interface InfoResponse$instance {
    email: string;
    isEmailConfirmed: boolean;
}


export const InfoResponse: {
    new(): InfoResponse;
};


export type InfoResponse = InfoResponse$instance;

export interface LoginRequest$instance {
    email: string;
    password: string;
    get twoFactorCode(): string | undefined;
    set twoFactorCode(value: string);
    get twoFactorRecoveryCode(): string | undefined;
    set twoFactorRecoveryCode(value: string);
}


export const LoginRequest: {
    new(): LoginRequest;
};


export type LoginRequest = LoginRequest$instance;

export interface RefreshRequest$instance {
    refreshToken: string;
}


export const RefreshRequest: {
    new(): RefreshRequest;
};


export type RefreshRequest = RefreshRequest$instance;

export interface RegisterRequest$instance {
    email: string;
    password: string;
}


export const RegisterRequest: {
    new(): RegisterRequest;
};


export type RegisterRequest = RegisterRequest$instance;

export interface ResendConfirmationEmailRequest$instance {
    email: string;
}


export const ResendConfirmationEmailRequest: {
    new(): ResendConfirmationEmailRequest;
};


export type ResendConfirmationEmailRequest = ResendConfirmationEmailRequest$instance;

export interface ResetPasswordRequest$instance {
    email: string;
    newPassword: string;
    resetCode: string;
}


export const ResetPasswordRequest: {
    new(): ResetPasswordRequest;
};


export type ResetPasswordRequest = ResetPasswordRequest$instance;

export interface TwoFactorRequest$instance {
    enable: Nullable<System_Internal.Boolean>;
    forgetMachine: boolean;
    resetRecoveryCodes: boolean;
    resetSharedKey: boolean;
    get twoFactorCode(): string | undefined;
    set twoFactorCode(value: string);
}


export const TwoFactorRequest: {
    new(): TwoFactorRequest;
};


export type TwoFactorRequest = TwoFactorRequest$instance;

export interface TwoFactorResponse$instance {
    isMachineRemembered: boolean;
    isTwoFactorEnabled: boolean;
    get recoveryCodes(): string[] | undefined;
    set recoveryCodes(value: string[]);
    recoveryCodesLeft: int;
    sharedKey: string;
}


export const TwoFactorResponse: {
    new(): TwoFactorResponse;
};


export type TwoFactorResponse = TwoFactorResponse$instance;

