// Generated by tsbindgen - Architecture
// Namespace: Microsoft.AspNetCore.Identity.Data
// Assembly: Microsoft.AspNetCore.Identity

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Boolean as ClrBoolean, Int32, Nullable, Object as ClrObject, String as ClrString } from "@tsonic/dotnet/System.js";

export interface ForgotPasswordRequest$instance {
    Email: string;
}


export const ForgotPasswordRequest: {
    new(): ForgotPasswordRequest;
};


export type ForgotPasswordRequest = ForgotPasswordRequest$instance;

export interface InfoRequest$instance {
    get NewEmail(): string | undefined;
    set NewEmail(value: string | undefined);
    get NewPassword(): string | undefined;
    set NewPassword(value: string | undefined);
    get OldPassword(): string | undefined;
    set OldPassword(value: string | undefined);
}


export const InfoRequest: {
    new(): InfoRequest;
};


export type InfoRequest = InfoRequest$instance;

export interface InfoResponse$instance {
    Email: string;
    IsEmailConfirmed: boolean;
}


export const InfoResponse: {
    new(): InfoResponse;
};


export type InfoResponse = InfoResponse$instance;

export interface LoginRequest$instance {
    Email: string;
    Password: string;
    get TwoFactorCode(): string | undefined;
    set TwoFactorCode(value: string | undefined);
    get TwoFactorRecoveryCode(): string | undefined;
    set TwoFactorRecoveryCode(value: string | undefined);
}


export const LoginRequest: {
    new(): LoginRequest;
};


export type LoginRequest = LoginRequest$instance;

export interface RefreshRequest$instance {
    RefreshToken: string;
}


export const RefreshRequest: {
    new(): RefreshRequest;
};


export type RefreshRequest = RefreshRequest$instance;

export interface RegisterRequest$instance {
    Email: string;
    Password: string;
}


export const RegisterRequest: {
    new(): RegisterRequest;
};


export type RegisterRequest = RegisterRequest$instance;

export interface ResendConfirmationEmailRequest$instance {
    Email: string;
}


export const ResendConfirmationEmailRequest: {
    new(): ResendConfirmationEmailRequest;
};


export type ResendConfirmationEmailRequest = ResendConfirmationEmailRequest$instance;

export interface ResetPasswordRequest$instance {
    Email: string;
    NewPassword: string;
    ResetCode: string;
}


export const ResetPasswordRequest: {
    new(): ResetPasswordRequest;
};


export type ResetPasswordRequest = ResetPasswordRequest$instance;

export interface TwoFactorRequest$instance {
    Enable: Nullable<System_Internal.Boolean>;
    ForgetMachine: boolean;
    ResetRecoveryCodes: boolean;
    ResetSharedKey: boolean;
    get TwoFactorCode(): string | undefined;
    set TwoFactorCode(value: string | undefined);
}


export const TwoFactorRequest: {
    new(): TwoFactorRequest;
};


export type TwoFactorRequest = TwoFactorRequest$instance;

export interface TwoFactorResponse$instance {
    IsMachineRemembered: boolean;
    IsTwoFactorEnabled: boolean;
    get RecoveryCodes(): string[] | undefined;
    set RecoveryCodes(value: string[] | undefined);
    RecoveryCodesLeft: int;
    SharedKey: string;
}


export const TwoFactorResponse: {
    new(): TwoFactorResponse;
};


export type TwoFactorResponse = TwoFactorResponse$instance;

