// Generated by dotnet-bindgen - Architecture
// Namespace: Microsoft.AspNetCore.Connections.Abstractions
// Assembly: Microsoft.AspNetCore.Connections.Abstractions

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Import types from other namespaces
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { PipeWriter } from "@tsonic/dotnet/System.IO.Pipelines/internal/index.js";
import type { Task } from "@tsonic/dotnet/System.Threading.Tasks/internal/index.js";
import type { Func_2, Void } from "@tsonic/dotnet/System/internal/index.js";

export interface IStatefulReconnectFeature$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Connections_Abstractions_IStatefulReconnectFeature: never;

    DisableReconnect(): void;
    OnReconnected(notifyOnReconnect: Func_2<PipeWriter, Task>): void;
}


export type IStatefulReconnectFeature = IStatefulReconnectFeature$instance;

