// Generated by tsbindgen - Architecture
// Namespace: Microsoft.AspNetCore.StaticAssets
// Assembly: Microsoft.AspNetCore.StaticAssets

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import * as Microsoft_AspNetCore_Builder_Internal from "../../Microsoft.AspNetCore.Builder/internal/index.js";
import type { EndpointBuilder, IEndpointConventionBuilder } from "../../Microsoft.AspNetCore.Builder/internal/index.js";
import type { IReadOnlyList } from "@tsonic/dotnet/System.Collections.Generic.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Action, Object as ClrObject, String as ClrString, Void } from "@tsonic/dotnet/System.js";

export interface StaticAssetDescriptor$instance {
    AssetPath: string;
    Properties: IReadOnlyList<StaticAssetProperty>;
    ResponseHeaders: IReadOnlyList<StaticAssetResponseHeader>;
    Route: string;
    Selectors: IReadOnlyList<StaticAssetSelector>;
}


export const StaticAssetDescriptor: {
    new(): StaticAssetDescriptor;
};


export type StaticAssetDescriptor = StaticAssetDescriptor$instance;

export interface StaticAssetProperty$instance {
    readonly Name: string;
    readonly Value: string;
}


export const StaticAssetProperty: {
    new(name: string, value: string): StaticAssetProperty;
};


export type StaticAssetProperty = StaticAssetProperty$instance;

export interface StaticAssetResponseHeader$instance {
    readonly Name: string;
    readonly Value: string;
}


export const StaticAssetResponseHeader: {
    new(name: string, value: string): StaticAssetResponseHeader;
};


export type StaticAssetResponseHeader = StaticAssetResponseHeader$instance;

export interface StaticAssetSelector$instance {
    readonly Name: string;
    readonly Quality: string;
    readonly Value: string;
}


export const StaticAssetSelector: {
    new(name: string, value: string, quality: string): StaticAssetSelector;
};


export type StaticAssetSelector = StaticAssetSelector$instance;

export interface StaticAssetsEndpointConventionBuilder$instance {
    Add(convention: Action<EndpointBuilder>): void;
    Finally(convention: Action<EndpointBuilder>): void;
}


export const StaticAssetsEndpointConventionBuilder: {
    new(): StaticAssetsEndpointConventionBuilder;
};


export interface __StaticAssetsEndpointConventionBuilder$views {
    As_IEndpointConventionBuilder(): Microsoft_AspNetCore_Builder_Internal.IEndpointConventionBuilder$instance;
}

export interface StaticAssetsEndpointConventionBuilder$instance extends Microsoft_AspNetCore_Builder_Internal.IEndpointConventionBuilder$instance {}

export type StaticAssetsEndpointConventionBuilder = StaticAssetsEndpointConventionBuilder$instance & __StaticAssetsEndpointConventionBuilder$views;


