// Generated by tsbindgen - Architecture
// Namespace: Microsoft.AspNetCore.Mvc.Razor.Compilation
// Assembly: Microsoft.AspNetCore.Mvc.Razor

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { RazorCompiledItem } from "../../Microsoft.AspNetCore.Razor.Hosting/internal/index.js";
import type { IList } from "@tsonic/dotnet/System.Collections.Generic.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Attribute, Object as ClrObject, String as ClrString, Type } from "@tsonic/dotnet/System.js";
import type { Task } from "@tsonic/dotnet/System.Threading.Tasks.js";
import type { IChangeToken } from "@tsonic/microsoft-extensions/Microsoft.Extensions.Primitives.js";

export interface IViewCompiler$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Mvc_Razor_Compilation_IViewCompiler: never;

    CompileAsync(relativePath: string): Task<CompiledViewDescriptor>;
}


export type IViewCompiler = IViewCompiler$instance;

export interface IViewCompilerProvider$instance {
    readonly __tsonic_iface_Microsoft_AspNetCore_Mvc_Razor_Compilation_IViewCompilerProvider: never;

    GetCompiler(): IViewCompiler;
}


export type IViewCompilerProvider = IViewCompilerProvider$instance;

export interface CompiledViewDescriptor$instance {
    get ExpirationTokens(): IList<IChangeToken> | undefined;
    set ExpirationTokens(value: IList<IChangeToken> | undefined);
    get Item(): RazorCompiledItem | undefined;
    set Item(value: RazorCompiledItem | undefined);
    RelativePath: string;
    readonly Type: Type | undefined;
    get ViewAttribute(): RazorViewAttribute | undefined;
    set ViewAttribute(value: RazorViewAttribute | undefined);
}


export const CompiledViewDescriptor: {
    new(): CompiledViewDescriptor;
    new(item: RazorCompiledItem): CompiledViewDescriptor;
    new(item: RazorCompiledItem, attribute: RazorViewAttribute): CompiledViewDescriptor;
};


export type CompiledViewDescriptor = CompiledViewDescriptor$instance;

export interface RazorViewAttribute$instance extends Attribute {
    readonly Path: string;
    readonly ViewType: Type;
}


export const RazorViewAttribute: {
    new(path: string, viewType: Type): RazorViewAttribute;
};


export type RazorViewAttribute = RazorViewAttribute$instance;

export interface ViewsFeature$instance {
    readonly ViewDescriptors: IList<CompiledViewDescriptor>;
}


export const ViewsFeature: {
    new(): ViewsFeature;
};


export type ViewsFeature = ViewsFeature$instance;

