// Generated by tsbindgen - Architecture
// Namespace: Microsoft.AspNetCore.Mvc.Routing
// Assembly: Microsoft.AspNetCore.Mvc.Abstractions, Microsoft.AspNetCore.Mvc.Core

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { Endpoint, HttpContext } from "../../Microsoft.AspNetCore.Http/internal/index.js";
import type { IActionDescriptorCollectionProvider } from "../../Microsoft.AspNetCore.Mvc.Infrastructure/internal/index.js";
import * as Microsoft_AspNetCore_Mvc_Internal from "../../Microsoft.AspNetCore.Mvc/internal/index.js";
import type { ActionContext, IUrlHelper } from "../../Microsoft.AspNetCore.Mvc/internal/index.js";
import * as Microsoft_AspNetCore_Routing_Internal from "../../Microsoft.AspNetCore.Routing/internal/index.js";
import type { IParameterPolicy, IRouteConstraint, IRouter, RouteDirection, RouteValueDictionary } from "../../Microsoft.AspNetCore.Routing/internal/index.js";
import type { IEnumerable, IReadOnlyList } from "@tsonic/dotnet/System.Collections.Generic.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Attribute, Boolean as ClrBoolean, Int32, Nullable, Object as ClrObject, String as ClrString } from "@tsonic/dotnet/System.js";
import type { ValueTask } from "@tsonic/dotnet/System.Threading.Tasks.js";

export interface IActionHttpMethodProvider$instance {
    readonly httpMethods: IEnumerable<System_Internal.String>;
}


export type IActionHttpMethodProvider = IActionHttpMethodProvider$instance;

export interface IRouteTemplateProvider$instance {
    readonly template: string;
    readonly order: Nullable<System_Internal.Int32>;
    readonly name: string;
}


export type IRouteTemplateProvider = IRouteTemplateProvider$instance;

export interface IRouteValueProvider$instance {
    readonly routeKey: string;
    readonly routeValue: string;
}


export type IRouteValueProvider = IRouteValueProvider$instance;

export interface IUrlHelperFactory$instance {
    getUrlHelper(context: ActionContext): IUrlHelper;
}


export type IUrlHelperFactory = IUrlHelperFactory$instance;

export interface AttributeRouteInfo$instance {
    name: string;
    order: int;
    suppressLinkGeneration: boolean;
    suppressPathMatching: boolean;
    template: string;
}


export const AttributeRouteInfo: {
    new(): AttributeRouteInfo;
};


export type AttributeRouteInfo = AttributeRouteInfo$instance;

export interface DynamicRouteValueTransformer$instance {
    state: unknown;
    filterAsync(httpContext: HttpContext, values: RouteValueDictionary, endpoints: IReadOnlyList<Endpoint>): ValueTask<IReadOnlyList<Endpoint>>;
    transformAsync(httpContext: HttpContext, values: RouteValueDictionary): ValueTask<RouteValueDictionary>;
}


export const DynamicRouteValueTransformer: {
};


export type DynamicRouteValueTransformer = DynamicRouteValueTransformer$instance;

export interface HttpMethodAttribute$instance extends Attribute {
    readonly httpMethods: IEnumerable<System_Internal.String>;
    name: string;
    order: int;
    readonly template: string;
}


export const HttpMethodAttribute: {
    new(httpMethods: IEnumerable<System_Internal.String>): HttpMethodAttribute;
    new(httpMethods: IEnumerable<System_Internal.String>, template: string): HttpMethodAttribute;
};


export interface __HttpMethodAttribute$views {
    As_IActionHttpMethodProvider(): IActionHttpMethodProvider$instance;
    As_IRouteTemplateProvider(): IRouteTemplateProvider$instance;
}

export interface HttpMethodAttribute$instance extends IActionHttpMethodProvider$instance {}

export type HttpMethodAttribute = HttpMethodAttribute$instance & __HttpMethodAttribute$views;


export interface KnownRouteValueConstraint$instance extends IParameterPolicy {
    match(httpContext: HttpContext, route: IRouter, routeKey: string, values: RouteValueDictionary, routeDirection: RouteDirection): boolean;
}


export const KnownRouteValueConstraint: {
    new(actionDescriptorCollectionProvider: IActionDescriptorCollectionProvider): KnownRouteValueConstraint;
};


export interface __KnownRouteValueConstraint$views {
    As_IRouteConstraint(): Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance;
}

export interface KnownRouteValueConstraint$instance extends Microsoft_AspNetCore_Routing_Internal.IRouteConstraint$instance {}

export type KnownRouteValueConstraint = KnownRouteValueConstraint$instance & __KnownRouteValueConstraint$views;


export interface RouteValueAttribute$instance extends Attribute {
    readonly routeKey: string;
    readonly routeValue: string;
}


export const RouteValueAttribute: {
};


export interface __RouteValueAttribute$views {
    As_IRouteValueProvider(): IRouteValueProvider$instance;
}

export interface RouteValueAttribute$instance extends IRouteValueProvider$instance {}

export type RouteValueAttribute = RouteValueAttribute$instance & __RouteValueAttribute$views;


export interface UrlActionContext$instance {
    action: string;
    controller: string;
    get fragment(): string | undefined;
    set fragment(value: string);
    host: string;
    protocol: string;
    values: unknown;
}


export const UrlActionContext: {
    new(): UrlActionContext;
};


export type UrlActionContext = UrlActionContext$instance;

export interface UrlHelper$instance extends UrlHelperBase$instance {
    action(actionContext: UrlActionContext): string | undefined;
    content(contentPath: string): string;
    isLocalUrl(url: string): boolean;
    link(routeName: string, values: unknown): string | undefined;
    routeUrl(routeContext: UrlRouteContext): string | undefined;
}


export const UrlHelper: {
    new(actionContext: ActionContext): UrlHelper;
};


export interface __UrlHelper$views {
    As_IUrlHelper(): Microsoft_AspNetCore_Mvc_Internal.IUrlHelper$instance;
}

export type UrlHelper = UrlHelper$instance & __UrlHelper$views;


export interface UrlHelperBase$instance {
    readonly actionContext: ActionContext;
    action(actionContext: UrlActionContext): string | undefined;
    content(contentPath: string): string;
    isLocalUrl(url: string): boolean;
    link(routeName: string, values: unknown): string | undefined;
    routeUrl(routeContext: UrlRouteContext): string | undefined;
}


export const UrlHelperBase: {
};


export interface __UrlHelperBase$views {
    As_IUrlHelper(): Microsoft_AspNetCore_Mvc_Internal.IUrlHelper$instance;
}

export interface UrlHelperBase$instance extends Microsoft_AspNetCore_Mvc_Internal.IUrlHelper$instance {}

export type UrlHelperBase = UrlHelperBase$instance & __UrlHelperBase$views;


export interface UrlHelperFactory$instance {
    getUrlHelper(context: ActionContext): IUrlHelper;
}


export const UrlHelperFactory: {
    new(): UrlHelperFactory;
};


export interface __UrlHelperFactory$views {
    As_IUrlHelperFactory(): IUrlHelperFactory$instance;
}

export interface UrlHelperFactory$instance extends IUrlHelperFactory$instance {}

export type UrlHelperFactory = UrlHelperFactory$instance & __UrlHelperFactory$views;


export interface UrlRouteContext$instance {
    get fragment(): string | undefined;
    set fragment(value: string);
    host: string;
    protocol: string;
    get routeName(): string | undefined;
    set routeName(value: string);
    values: unknown;
}


export const UrlRouteContext: {
    new(): UrlRouteContext;
};


export type UrlRouteContext = UrlRouteContext$instance;

