// Generated by tsbindgen - Architecture
// Namespace: Microsoft.AspNetCore.Server.Kestrel.Core
// Assembly: Microsoft.AspNetCore.Server.Kestrel.Core

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import * as Microsoft_AspNetCore_Connections_Internal from "../../Microsoft.AspNetCore.Connections/internal/index.js";
import type { ConnectionDelegate, IConnectionBuilder, IConnectionListenerFactory, IMultiplexedConnectionBuilder, MultiplexedConnectionDelegate } from "../../Microsoft.AspNetCore.Connections/internal/index.js";
import * as Microsoft_AspNetCore_Hosting_Server_Internal from "../../Microsoft.AspNetCore.Hosting.Server/internal/index.js";
import type { IHttpApplication_1, IServer } from "../../Microsoft.AspNetCore.Hosting.Server/internal/index.js";
import type { IFeatureCollection } from "../../Microsoft.AspNetCore.Http.Features/internal/index.js";
import * as Microsoft_AspNetCore_Http_Internal from "../../Microsoft.AspNetCore.Http/internal/index.js";
import type { BadHttpRequestException as BadHttpRequestException_Http } from "../../Microsoft.AspNetCore.Http/internal/index.js";
import type { HttpsConnectionAdapterOptions } from "../../Microsoft.AspNetCore.Server.Kestrel.Https/internal/index.js";
import type { KestrelConfigurationLoader } from "../../Microsoft.AspNetCore.Server.Kestrel/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Action, Boolean as ClrBoolean, Double, Enum, Func, IComparable, IConvertible, IDisposable, IFormattable, Int32, Int64, IServiceProvider, ISpanFormattable, Nullable, Object as ClrObject, String as ClrString, TimeSpan, UInt64, Void } from "@tsonic/dotnet/System.js";
import type { EndPoint, IPAddress, IPEndPoint } from "@tsonic/dotnet/System.Net.js";
import * as System_Runtime_Serialization_Internal from "@tsonic/dotnet/System.Runtime.Serialization.js";
import type { ISerializable } from "@tsonic/dotnet/System.Runtime.Serialization.js";
import type { Encoding } from "@tsonic/dotnet/System.Text.js";
import type { CancellationToken } from "@tsonic/dotnet/System.Threading.js";
import type { Task } from "@tsonic/dotnet/System.Threading.Tasks.js";
import type { IConfiguration } from "@tsonic/microsoft-extensions/Microsoft.Extensions.Configuration.js";
import type { ILoggerFactory } from "@tsonic/microsoft-extensions/Microsoft.Extensions.Logging.js";
import type { IOptions } from "@tsonic/microsoft-extensions/Microsoft.Extensions.Options.js";

export enum HttpProtocols {
    None = 0,
    Http1 = 1,
    Http2 = 2,
    Http1AndHttp2 = 3,
    Http3 = 4,
    Http1AndHttp2AndHttp3 = 7
}


export interface BadHttpRequestException$instance extends BadHttpRequestException_Http {
    readonly StatusCode: int;
}


export const BadHttpRequestException: {
    new(): BadHttpRequestException;
};


export type BadHttpRequestException = BadHttpRequestException$instance;

export interface Http2Limits$instance {
    HeaderTableSize: int;
    InitialConnectionWindowSize: int;
    InitialStreamWindowSize: int;
    KeepAlivePingDelay: TimeSpan;
    KeepAlivePingTimeout: TimeSpan;
    MaxFrameSize: int;
    MaxRequestHeaderFieldSize: int;
    MaxStreamsPerConnection: int;
}


export const Http2Limits: {
    new(): Http2Limits;
};


export type Http2Limits = Http2Limits$instance;

export interface Http3Limits$instance {
    MaxRequestHeaderFieldSize: int;
}


export const Http3Limits: {
    new(): Http3Limits;
};


export type Http3Limits = Http3Limits$instance;

export interface KestrelServer$instance {
    readonly Features: IFeatureCollection;
    readonly Options: KestrelServerOptions;
    Dispose(): void;
    StartAsync<TContext>(application: IHttpApplication_1<TContext>, cancellationToken: CancellationToken): Task;
    StopAsync(cancellationToken: CancellationToken): Task;
}


export const KestrelServer: {
    new(options: IOptions<KestrelServerOptions>, transportFactory: IConnectionListenerFactory, loggerFactory: ILoggerFactory): KestrelServer;
};


export interface __KestrelServer$views {
    As_IServer(): Microsoft_AspNetCore_Hosting_Server_Internal.IServer$instance;
}

export interface KestrelServer$instance extends Microsoft_AspNetCore_Hosting_Server_Internal.IServer$instance {}

export type KestrelServer = KestrelServer$instance & __KestrelServer$views;


export interface KestrelServerLimits$instance {
    readonly Http2: Http2Limits;
    readonly Http3: Http3Limits;
    KeepAliveTimeout: TimeSpan;
    MaxConcurrentConnections: Nullable<System_Internal.Int64>;
    MaxConcurrentUpgradedConnections: Nullable<System_Internal.Int64>;
    MaxRequestBodySize: Nullable<System_Internal.Int64>;
    MaxRequestBufferSize: Nullable<System_Internal.Int64>;
    MaxRequestHeaderCount: int;
    MaxRequestHeadersTotalSize: int;
    MaxRequestLineSize: int;
    MaxResponseBufferSize: Nullable<System_Internal.Int64>;
    get MinRequestBodyDataRate(): MinDataRate | undefined;
    set MinRequestBodyDataRate(value: MinDataRate);
    get MinResponseDataRate(): MinDataRate | undefined;
    set MinResponseDataRate(value: MinDataRate);
    RequestHeadersTimeout: TimeSpan;
}


export const KestrelServerLimits: {
    new(): KestrelServerLimits;
};


export type KestrelServerLimits = KestrelServerLimits$instance;

export interface KestrelServerOptions$instance {
    AddServerHeader: boolean;
    AllowAlternateSchemes: boolean;
    AllowHostHeaderOverride: boolean;
    AllowResponseHeaderCompression: boolean;
    AllowSynchronousIO: boolean;
    ApplicationServices: IServiceProvider;
    get ConfigurationLoader(): KestrelConfigurationLoader | undefined;
    set ConfigurationLoader(value: KestrelConfigurationLoader);
    DisableStringReuse: boolean;
    EnableAltSvc: boolean;
    readonly Limits: KestrelServerLimits;
    RequestHeaderEncodingSelector: Func<System_Internal.String, Encoding | undefined>;
    ResponseHeaderEncodingSelector: Func<System_Internal.String, Encoding | undefined>;
    Configure(): KestrelConfigurationLoader;
    Configure(config: IConfiguration): KestrelConfigurationLoader;
    Configure(config: IConfiguration, reloadOnChange: boolean): KestrelConfigurationLoader;
    ConfigureEndpointDefaults(configureOptions: Action<ListenOptions>): void;
    ConfigureHttpsDefaults(configureOptions: Action<HttpsConnectionAdapterOptions>): void;
    Listen(address: IPAddress, port: int): void;
    Listen(address: IPAddress, port: int, configure: Action<ListenOptions>): void;
    Listen(endPoint: IPEndPoint): void;
    Listen(endPoint: EndPoint): void;
    Listen(endPoint: IPEndPoint, configure: Action<ListenOptions>): void;
    Listen(endPoint: EndPoint, configure: Action<ListenOptions>): void;
    ListenAnyIP(port: int): void;
    ListenAnyIP(port: int, configure: Action<ListenOptions>): void;
    ListenHandle(handle: ulong): void;
    ListenHandle(handle: ulong, configure: Action<ListenOptions>): void;
    ListenLocalhost(port: int): void;
    ListenLocalhost(port: int, configure: Action<ListenOptions>): void;
    ListenNamedPipe(pipeName: string): void;
    ListenNamedPipe(pipeName: string, configure: Action<ListenOptions>): void;
    ListenUnixSocket(socketPath: string): void;
    ListenUnixSocket(socketPath: string, configure: Action<ListenOptions>): void;
}


export const KestrelServerOptions: {
    new(): KestrelServerOptions;
};


export type KestrelServerOptions = KestrelServerOptions$instance;

export interface ListenOptions$instance {
    readonly ApplicationServices: IServiceProvider;
    DisableAltSvcHeader: boolean;
    readonly EndPoint: EndPoint;
    readonly FileHandle: ulong;
    readonly IPEndPoint: IPEndPoint | undefined;
    readonly KestrelServerOptions: KestrelServerOptions;
    readonly PipeName: string | undefined;
    Protocols: HttpProtocols;
    readonly SocketPath: string | undefined;
    Build(): ConnectionDelegate;
    ToString(): string | undefined;
    Use(middleware: Func<ConnectionDelegate, ConnectionDelegate>): IConnectionBuilder;
}


export const ListenOptions: {
    new(): ListenOptions;
};


export interface __ListenOptions$views {
    As_IConnectionBuilder(): Microsoft_AspNetCore_Connections_Internal.IConnectionBuilder$instance;
    As_IMultiplexedConnectionBuilder(): Microsoft_AspNetCore_Connections_Internal.IMultiplexedConnectionBuilder$instance;
}

export interface ListenOptions$instance extends Microsoft_AspNetCore_Connections_Internal.IConnectionBuilder$instance {}

export type ListenOptions = ListenOptions$instance & __ListenOptions$views;


export interface MinDataRate$instance {
    readonly BytesPerSecond: double;
    readonly GracePeriod: TimeSpan;
    ToString(): string;
}


export const MinDataRate: {
    new(bytesPerSecond: double, gracePeriod: TimeSpan): MinDataRate;
};


export type MinDataRate = MinDataRate$instance;

