// Generated by dotnet-bindgen - Architecture
// Namespace: Microsoft.AspNetCore.Cryptography.KeyDerivation
// Assembly: Microsoft.AspNetCore.Cryptography.KeyDerivation

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Import types from other namespaces
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Byte, Enum, IComparable, IConvertible, IFormattable, Int32, ISpanFormattable, Object as ClrObject, String as ClrString } from "@tsonic/dotnet/System/internal/index.js";

export enum KeyDerivationPrf {
    HMACSHA1 = 0,
    HMACSHA256 = 1,
    HMACSHA512 = 2
}


export abstract class KeyDerivation$instance {
    static Pbkdf2(password: string, salt: byte[], prf: KeyDerivationPrf, iterationCount: int, numBytesRequested: int): byte[];
}


export type KeyDerivation = KeyDerivation$instance;
