// Generated by tsbindgen - Architecture
// Namespace: Microsoft.AspNetCore.Components.Sections
// Assembly: Microsoft.AspNetCore.Components

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import * as Microsoft_AspNetCore_Components_Internal from "../../Microsoft.AspNetCore.Components/internal/index.js";
import type { IComponent, ParameterView, RenderFragment, RenderHandle } from "../../Microsoft.AspNetCore.Components/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { IDisposable, Object as ClrObject, String as ClrString, Void } from "@tsonic/dotnet/System.js";
import type { Task } from "@tsonic/dotnet/System.Threading.Tasks.js";

export interface SectionContent$instance {
    ChildContent: RenderFragment;
    get SectionId(): unknown | undefined;
    set SectionId(value: unknown);
    get SectionName(): string | undefined;
    set SectionName(value: string);
    Dispose(): void;
}


export const SectionContent: {
    new(): SectionContent;
};


export interface __SectionContent$views {
    As_IComponent(): Microsoft_AspNetCore_Components_Internal.IComponent$instance;
}

export interface SectionContent$instance extends Microsoft_AspNetCore_Components_Internal.IComponent$instance {}

export type SectionContent = SectionContent$instance & __SectionContent$views;


export interface SectionOutlet$instance {
    get SectionId(): unknown | undefined;
    set SectionId(value: unknown);
    get SectionName(): string | undefined;
    set SectionName(value: string);
    Dispose(): void;
}


export const SectionOutlet: {
    new(): SectionOutlet;
};


export interface __SectionOutlet$views {
    As_IComponent(): Microsoft_AspNetCore_Components_Internal.IComponent$instance;
}

export interface SectionOutlet$instance extends Microsoft_AspNetCore_Components_Internal.IComponent$instance {}

export type SectionOutlet = SectionOutlet$instance & __SectionOutlet$views;


